// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y923LcOJYo+iuInBPhqpjMlCz5Ula/HLcvVaq2yxpL7jonWhVKJInMhEUCbAJUOtvh",
	"iPmI8ydnT8R+2PO0f6Dmj3ZgLQAESTAvsiWr3NMP1VaSxGVhYd0vHweJzAspmNBqcPRxoJIFyyn886lS",
	"fC5YekbVpfk7ZSopeaG5FIOjxlPCFaFEm39RRbg2f5csYfyKpWS6InrByK+yvGTleDAcFKUsWKk5g1kS",
	"medUpPBvrlkO//i/SjYbHA3+Za9e3J5d2d4z/GDwaTjQq4INjga0LOnK/P1eTs3X9melSy7m9veLouSy",
	"5HoVvMCFZnNWujfw18jngubxB+vHVJrqauN2DPxO8U2zI6ou+xdSVTw1D2ayzKkeHOEPw/aLn4aDkv29",
	"4iVLB0d/cy8Z4Ni9+LUFW2hBKQBJuKphfV6/+Xnl9D1LtFng0yvKMzrN2M9yesq0NsvpYM4pF/OMEYXP",
	"iZwRSn6WU2JGUxEEWUie4D+b4/y6YILM+RUTQ5LxnGvAsyua8dT8t2KKaGl+U4zYQcbkjchWpFJmjWTJ",
	"9YIg0GByM7dHwQ7w28iWshmtMt1d19mCEfsQ10HUQi6FXQypFCvJ0qw9ZZqVORcw/4IrB5IxDh+MGZ/C",
	"/7Knpcw0L+xEXNQTGXwsZzRhMChLuTZbxxHt+mc0U2zYBa5esNIsmmaZXBLzaXuhhM60eWfByHs5JQuq",
	"yJQxQVQ1zbnWLB2TX2WVpYTnRbYiKcsYfpZlhH3gCgek6lKRmSxx6PdyOiRUpIaAyLzgmXmH6/G5qBF9",
	"KmXGqIAdXdGsC5+TlV5IQdiHomRKcQnAnzJi3q6oZqmBkSxT3KA7BwY7aR6dX5c/m2EXNcywx2Imuwt5",
	"zTQdpVRTOxAj98zL94KldTG+c/T2oAaD9ik9r/8y92i5oDo+iaHIqTTrJ8dAnmmmpMGQ1FDsIqMJW8gM",
	"4ME+aAMUg0qIpmbAnIqKZoSLotJkxpk5U0UWPE2ZIN9NWUIrheAdSTHC86/xQcv5PGMpkcJxA4Ob3zfO",
	"tIammfkVF5d/rrRuQSCKqi+EQWlVb9zMg0u4Z6cmUxiLTNmCXnFZdo+VPG29uuRZZlDGX6k/Z0ykrLyn",
	"cGwLVn+9CJCjeqdDWM/ErGcSHgSM28Q4u4Z7CnFuTF4DtLNVcOlqeslhp4IISTIp5qwkhVSKTzOG94YL",
	"pRlNga6K8MRwRfcC4N1z1M8AwuxzfC6emmtD8yKDQ7KzES1HUzYqAQIsJbOS5oyUVMzZkCwXPFmYg3U3",
	"h1Za5lTzBPYwk4Z+4DAqYcJ/N600Sag5FCKvWFkiMuVu75ZEKsPG4re/xedaeNNEkxi3umSr7o09TpnQ",
	"fMZZ6a+shfyQ5JXSZrmV4H+vkH9YWvve8q8oecjolEWI1CvzM0ySclVkdNXhA+R4RoTURBUsMUuyR3jJ",
	"VuZc4PZqSeZMsJJqRigpGVUSrgOBSccopciClvMIB30qVoR90CUltJxXuZFLHJeaFqux+VCNT2XOTpA+",
	"rb77nphD9VMnJTMTw6ItDVsFIKhBXZ/TDoyH5zlLOdUsW5GSmaEIBUinbMYFNx8MDZrD9GbKIRyJrLRd",
	"ES01T6qMlh6iPVxEVVMndK2T1SLizan90gsIO49wZj+/4nCJrzHCX82XPDNiW/tOGBS3K9tSXjutQdES",
	"26rpyDxBiCPKe0R9VpUlEzpbEWkELOrGBfQORCw1JpOfnp7+9OL5xcvjVy8uTp6e/TRB9SHlJUu0LFek",
	"oHpB/pVMzgd7/wL/Ox9MCC0KQ30sKWCiys3+ZjxjF+Z9c9156f4JP1tRd0HVgqUX9Zu/Ra5o37l0JS8L",
	"gWD3AV1AuZIqcvzcXRnYdsA/xuQXSQRTRghRuqwSXZVMke9ArlRDkvLETEVLztT3hJaMqKooZKnbW7eL",
	"HxqV4/DAbDqTVA+GgNfbbjJAnYak4ZBxGJO5nXTQpFUT+83kiNBsSVfIUsZkUrPLyRGiB3xtKee7Y9QA",
	"AKBWbizJdxm/NATNAo3QNB1J8f2YTJZsGhtmyaY1Mwasy6mgc2aIGrIaQ0iBp9hZHF99L6djMkFRZnJE",
	"BLtiJQz9pzYuW9JoVoqiqXkRgANqr5ld0KxJa9xp1QDFmQZAdCxcBsPBkk03nlkcI53qVOMJCllcGTmC",
	"zllp5QINFJHmRvZQW0idn61wxCRlTSMa4U9ULUKyApzUML8WnVHEcmRgbiRZoCABezUjo3CFP4/JmfnZ",
	"8UkpagzzGgETqioN+7Jis9dbmpOaS1gVoClQzXqkVs/ktzcfuAm2Nn3E1OuOZtriAJYK4vKCOe1ZbOIK",
	"BuciksMrrrQjg0DX+7Gvi2nOsnC9jZ812G3PruspYhu0VOWE6sWzBUsu3zJlNfmW6cFoNd3Nd7SulZM3",
	"9MIg3HdC6u8tM4jeAhDK45cM5XXAyCVVaN4wmDfjIsVZHB+JDqwucNqotQTlqgXzC7X8SpaGOI6jkhFw",
	"zOhKYRC/0JmsRBpdk5JVmWwUa4IjOcUP2keKQLMr8sOGex7aA9tw5C+5SOsT3wr/ehAmYhXq7uPoY1Na",
	"oUrJhFONdN/s5oKJqytaDixi9EspzvTZOQ/7gJTM6Jkgx1Oi0M5mDXZA7z6wpNJsk0m2397p2Ufw2ME4",
	"TneCT2LH8qIsZdndz49GpeEJYeYxKZkqpFAsZjxOI6j+09nZCUELJzFveB3BD0SODb9OsipFUxBeilUm",
	"aUqURKz2AMTVNmCbZXZpXKAtlkujOz8zkz3cP/Rcx9tPUqrplKI+Pa3UynAnRmChblGWeUmhKReEkntv",
	"mS5Xo6czzcp7+OqCUTDRmOVxkfKEaqasEQ61cM1ztCmYo2DKK9gl0yVn6Zi8BG3cyT52QK5AOjJoQo0E",
	"7gSGe8ryPfNuknEmwDSUSqJkzozyO2+onEZmYx/w8nCakSlNLuVshhzTG62dvNq1mOdMKTqP4V4LueDc",
	"6/ejmHXFhH5Jy/x0KzN8/eZbZviYH+JnOX1XGL4f1YgU096APSQGO8CWQU5lcsn08Zu91/92doZogCIu",
	"CifKHERJBFuaH9WQTIqSXXFZqQvE24m3P7EPiKYIxLbIljHNLuxZs/SCRrjK8czqzBkDjmWotf/CCk/O",
	"ysNzpjTNC2KoOiKUwTWHTOZTpWWJ8tTLjOZMJNIz+uYxG5iNzIhRRhUhYu/eHT93UuDP4KzY4OeoRavm",
	"QL/QPNRSYx+2wL0JO4y85X00odfHa0wP92MIXbJZydTiAmzckaPxd9iLoPaWqQXYze33QHDsbu4ptJjX",
	"8i1gHWo8ylxYA3g1NEgHcmtKQdVhNFkA0bjiaUUz9NYtYRZvQNJSGiKwcoNYq3lR0gSseb3mk92B2O/j",
	"gqkj6HHmkVPOSEaVtqvcGueWVF3gjUl7nEl4RQ2WvzcavX25viPmtmtJJrqs2MQqKPZJbaEDpREsrTy9",
	"V9vKFdNDS5nNTXK3Oy/0aivrJlwAB5zAgWfdcoHjrol0vbTxFVX6rTXo9lE4i6CyrBHUQL42BPOczmv+",
	"6qBnlxmX/LdyYQ4HelHlU0F5tgVahVs5NisCZ0xMJ8C5qLq0//KT9IOJz9izVRITqT0BzPiMjRLzEmFX",
	"YHCw/gWjPQJXVIsKLQ6pXIqhEU5K+LMqhoTpJEbctzEn+sXBUlEzau261/aHn1B1+UrO+84fnPuZnJNk",
	"UYlLy+C0JJQAX9Oy4Mme43WklDInKUOaluJ7VoYyIB/CL1eSp2acFGSQFsGJwSGTEYvBM7MeR+O1XeWY",
	"vKYrL0HlVaZ5AWKJYAreZR90VEVxCLGWJUEYxHBH33uNamYba49hGynjDMC4QcwAcHTkDKAG1xU0DP2/",
	"agY6bM/LtwPccBfisJnva5z0cxl/MzrjOt/cFD+LsQdP4azyFWEX/iR7cRG1wjPaSxTwBXJG5xtQkWuP",
	"hjH6hpbAdZD0S9mWfYMNcEv2vZnl9tnHAjBtc2nxzY3XdolgXQOxhIoLIz3QUq+z73BlpwTlj1ZajuxX",
	"cROPhVNUeXAyJtrbma41WrtcA207wPiLSf+4/G1ohrk3F4oxEXOvKu30Ya7C9Zr3nQ0kMFJut/bNpGfp",
	"Vv+5xAfBsCv5iX91gXi1y8fP4Iu3qPvdrGh+xUpl/Q5bkLl+6ubGGTbuSuwONy0DzkAH1BGMiinYE5cU",
	"4i8M3VQZYwWY6MyVpPa9SlwKuRS4BhDpooa7jnXBzIlRFhB0aReC035q33u1owWjGxmBP0fhYGXYv9Yn",
	"ECxszsEZeDg+GD1+NJqn6eGD9OHhD+4Mjgb/r6xKd4cGELpTan+Yg8Px4YhmxYLuB2cT/ky+64z9fXf/",
	"sIqdHCuNZXxci29NTLZg8BqN96DljFote1HlVBgpU1U5fIYyVskyRhUj04pnqQuCBaeSIQ1UkUm4qgmq",
	"CBJIdv0JRGVZwyR+PZlzPSH2KzA3Rv1PrQOv70EDFP7qGIjGsOFnDKClWfZmNjj623qEO3XeMvPVp+HH",
	"NTLjWv+J0yqJ+4JI4fXJqLyOYScxO7h5AM49R5G2JkH/9La0axhxdmYI27NZZKIXuwmJMWbhcGWDNPzp",
	"N0T/P2cyucy40v0+T1yatdnRkoHtHIJkWUoSVoL2CUoYekalke6sgShxOL2V2ylczwuhy1XM49R9qePH",
	"XB9VbkG9pepl3+6hva0TqIcOg8h7KM9ze6vikbTmV0KnstIY5urUVit8OsHUWqF4QyptsdMFzam4SBYs",
	"uZSVXu8qPYWXiXs5iFJyCyhZLq9YSmgmxRxjyl1YyTYxi8219IAmbuDqLPyFkNV8ETqlgMvQwHdTcJYw",
	"ouUct5jy2YyVYHGGEwSTr/maULKQYOnLQNYh796+cp6giAlwTM4k8ESIaMLAnrevhuanhGomqGbkfPBx",
	"ShX7tPdRCi8sq2o24x+Y+nQ+iKk85oMmWpZZlHjZYRoe3Q0h/K2jgKmCkXqO4jVVymHqKctYEg+YOfF+",
	"T4wwN8+mzDKC93KqnIm/RmGDLoHsBaqNpVkXOf0wOBoc7B8cjvYfjfbvn90/PLr/4Oj+w3/dPzja3+/K",
	"TN2vO8GfWYYLQR8+K1lIqc3CZrKE4ADHjmuW1rp84+1tFlGQMk1TqilIDWkKgZ00O4lYQxv8urGZcsp1",
	"ScsVye1gDqHH5LXZhqGuGfsQhtxZ12guzS4gbKVSXMzJhI6n42RiyHp9h2zcbeuMilLCPo4Gp0XJNSMv",
	"Sz5faMNsFCvHLAf79UCtpiUT//fURm7Icu7esGL0KbxATvX//l9XLBv0wOnE2vifeVWueeahYyqnH3hu",
	"lJr7+/vDQc4F/hXxUrWugR+kB/9Pg6Cl+GHpsmI93/YrXAkViTkGzDAq0MwzHMwoxx8LWqn6HyMvdA2G",
	"g79XrMIPYYzGM/h3xVCHqwz0R55KNcPCa8zyC+2DM7q841Ex+CzIL7BhCBiT9kXkrrhyN3TL6js3Lcte",
	"xmEfAufw4Zgust/LpubCVAriIJHpmbeQQ7CUzHjGFLJhwRKmFC1XMZLeYnlRu/u9Z47fHj+/F4RSgDDn",
	"ghfarDlMIRqTp9yoVAJX6j6JsXFn0LJig2Pns1Lmfut9OlcM0GdUXarTKs9puYolv+VFBp5Ckll5EhOg",
	"HNTH5Bk6MDDMxJrtXQCr+ckdEnh0zfNxxLZq/c1biZlgsLYL3iKwrpc1qn+rGO45ZGM8N+r7w+EgD8h8",
	"H+H8NBxAWtbFdAWpi5aBQVxzbcWwJi0uGiTE0wFLNH7rMkVcy8eaHt6Ph6F8Nj96yTNtNPuaHw0dd3l1",
	"/JcXNXOJZkvI2Uyx5kKj4QU1qD7ukLiotqTgfTsKY2N32VVwau1b8ZbpqhRoZQaZBMRo6qgntwIIbGEX",
	"7akdbxAgdT8C90WDAupve6fQJnLNuxRx6wY8EwPbyxFYHKtiMKx/WVQ6lcs4W7OWhWdSzPi8KqmTW5ub",
	"5OolL5V+W4kNLgauQN7nqAQYAjozH9YRaHY+UlYiCFbxmW8gcFEyY0syo4YUqyGxQf9CihGkhxq9JAnX",
	"C0zGiKROzfYx2lMGQS55oQ1JN2/pBVtZIVvc02TKeqNXgI9gFmG6lTYIq9AlFWrGSvL05BgyWFyM8rgn",
	"RgZY7CuZ0LjG8NyzJOB3hpuZmwZz2Y/HGw1/7VnauxuGBxxDPXtqf6Uld3HEbQS50Eu5pBHe9kaw0ZKu",
	"yJX9GCPnIX1UKg2BqNJccpuoCLktHDINSwYpqDlEMhnGO/loJONPE6ty8hJTI51IsoBsIOVcZ64GgY+W",
	"dk63MTlbysiawM5qJ007WSFe+mF2+UVGtdFvRt6Kg8nBIC7YQaYrv+g+RIOPNhtNrI22BrT7covzelql",
	"nIlm1LG1V1mVQ60jDm4YtY71rSN7bfTpMMbXtCgMjOGU3aEQs2XI+NM+j5BjLYDIhld/Yax4WwkRrS5Q",
	"x9Qtg4trvX85XZFLxgpDlIQTCuMiVN6Zp3ugtSLQI9U3XGgx4tKKAKRNfaG2LXsddGnx+tjHCIJEvmBk",
	"svS+OzYh1kmFeS51ujFeHzMJwHsuzX8F+6Ab0WzoIR+SSRMIE/L63emZ0ZknkLo52SpwrQVID7U+GMWw",
	"3AfeH7vMiZbma7MU1l+sVlx9ZPhbTwT5avkaoAmxdDNHsekW22VZvGVzw7ZLlloXfgeSNE1LptSOdVYs",
	"/Y3fNDnTS1qyNddwZ5e5y2W68EZrtZuM/VmVWiwDcKAKq7U4QAwHCWbcXthAJw+FntXHTuuUJVXJ9con",
	"YbQo4LbR+OvC8E+ZroqnSnGlqdAofMbyV0IhT06NbOd0cJC7zCjED9Ol1ta09gISXOgWadT9GT1fS1Dr",
	"biEKTxDnnvX6Lk4x6sgaY6wzgpfk9KenBw8f4bVXVT4kiv8D0pKnK4gWNwKZLbZAMrsolxnTtZq0zKAw",
	"G/iLkfwM6gT98VyiEDo4Ghw+nO4/eHI/OXg83T88PEzvz6YPHs6S/cc/PKH3DxK6/2h6P330YD89ePjo",
	"yeMf9qc/7D9O2cP9B+nj/YMnbN8MxP/BBkf3Hxw8AIczzpbJ+ZyLeTjVo8Pp44Pk0eH0yYODB7P0/uH0",
	"yeHj/dn00f7+oyf7P+wnh/T+w8f3HyezQ5o+eHDw6PDh9P4Pj5NH9IcnD/cfP6mnOnj8qWtIcBA5iVJb",
	"82sgPTpFyPLrsGaCG8dVZfHeFutpaZu4gIZT5ZUidB6HcUzkWBAs5GKd/sp5WuxYGAzlYuTMg3O/HXL8",
	"/HyAxiancvvIA59KRHEVoKtNrB1npLJqvgfVPUaGeu1hhYzR8fNJT7qsRZkttWlc+0uesdOCJRsVaxx8",
	"2Dymzbep5v4xu655hla61qnESlZdAz2so7qNGKA4W9DX3jq9oML6QZshCFQ1BgVHjU1zpq5uSX2NyVkg",
	"XXw+8m0RmbLlkfij7hI4q4JRJ3VRpLyWVtlFB3Q4Lim2XPuyHg9NGfWI3jcbLVVEIytsktpwzOgYQGc+",
	"ds1trEmjBxtdN2Y1drxhv7DbBPCvXC9qt8xWoHZKeOL8l1HQD62YOiQpK2y4P9AR5xP5xs9mW9kzOI4e",
	"/07nVIfrAvo64wWWgDpasSoySVPUxzAKKWoWwMHe4mqgPpALB72u4AGCRgN2vbLEDQkNtyIg3AJ76z/8",
	"5nlhdnGcq+FpgZhNSRl85ljKMDxKa5uQzevOyisjd7zkGQtiogDRDCexr5nfXIZJLdeHmd23hQP1xfT3",
	"4WbQIpzIX7cvjCsB+f5crMGynE3C0fYS4/nvynO/FCFcS/RKlp5u0tzarETBZzXHoqkRiq1OF8TsUWtV",
	"JefV/v7BI28PttJZpQzmdwzNWtoBI3OhMOXvgRWg7qmmuyOaihVYeHewxHrD8KfhIAsAtKOt5RZcJa1T",
	"z2oN2W+9YQhprimKHTbd5rSarilxdMoEWPF9OiMGzSmI3d5TwbcTzPK0Jee0tKWmHJUM3jQP38upT28k",
	"z9yYWCFrznT4HFUvMPVSdemzsN3fmZwrdGsJxmxBjyLjCdfZyk07ZRiODo4V82g19BsxWgQm8rh3zRhS",
	"YOzDd1BKUDennrnU3/dy+j3wbvO6eeWegsRQMFprnrPxuXA+PiE1mkamK8gTBa3E8hGqSVFKLROZuZJL",
	"Hlrom0Fg+rrRkCI1LSWkUJmRmzEZzcshi41UJoILb5ytfNsqfrFBXFkiZ/nrj8fGuhlaNo9hj1Si/sFQ",
	"hvHO2aayWFfsb/3WAzHRLwNipuq/ohJiHygixIFqcslFapMrtoaBjxXLsp/lFMK2s+xX79SyFR6ouszk",
	"HB+G4bLh62d0Hnd/NVIZohXWaotWUCVMyxobmxLMNrEunx8kaB8c/v7/kf/699//4/f//P1//P4f//Xv",
	"v//P3//z9/8/LAoA5SnCuA+YBbSeo8EehvLuqdneezlVaMa5f3A4hpfAjFKJywuUaw4DnDz55UeDooUa",
	"HBmxCorCGmnn/uj+PhZevICMN7ZUvtgnRAtjMUb2QTNhU4LGhXUNmZVcyEr7OkiN9eEUfoV78Z3bqpGd",
	"8Uop9drxbClQrEF4UXPCQcZF9SG4fuC1HtmjsqHQ3RhcQBiaXafGSIg/Gz7y0bPbVqrfULMkRJNN63Wv",
	"1mbzrXZZRyL2ALwTWYBkSsyJWinN8jp63H7bqvYHEYqJnAuuWFcysy/XAdiUZHLJylFCFfMWTzuFW5SN",
	"TjlHXDgfDMn5YMlFKpcK/0hpueQC/y0LJqYqNX8wnYzJqZ9K5gXV3Fef/1HeU2RSVgJY6I9v3pxO/kTK",
	"SpAJuGZlRlKuNIQKTohl0NRHDrrCz36RanwunionutKMmB0NG/sg5y5c6Hzg7Iq2iD6adVxsNxRyLEpI",
	"rqCKnA+agqob73xQwz6XyogiIBFdMqKZ0nspm1ZzWyZTEUYVh4KUVpBxIaXo+OYJSWUChYghaybLGjuL",
	"lm7oy2oxP1xsX25ySBJZ8FA3nbSLDo7NaBNf57hbsPLM/lVnhhi6z1LCrWsdi8GkkilxT5Oc6gRzRWii",
	"K5r5kTo2/TOsrwxSp2rXsQQ8klkaxOQ1y/K3a5X6suyuTMu5OG4skCsic2Rxw9rMBqXLVgVVqlWPuy9p",
	"K1o1QNM5SoH29rmSdHXgbpDKf/zcR/XYujqW7aPmSTXxRT+njBgSk1YZXn+zFLQ3QmQDBobJMtiYwS6X",
	"ymXQ0H3hV9JMwdtKALOe225NngiRi4lo8VYrZ67GCTZXgdA45ZRvZ+l3FeaGhI/Z2GVv+AibIMJqvFt5",
	"jy/ZoOUmEjcx2vdiurpwgU67xD3bOIXIWrfMh9uhagnk5GhZGTzdkDOJgW1i5csWmP9L60wcG7K0W8mC",
	"r9+/5qbzRXc58W2TRdtFVWKtc8IGOf4ybeiVY0svbcx2hIw7afvkBOWUPqu6VtyxYQgN2OZbhZWGDWN9",
	"F1OC+kkbZ67KLD7xu7evwlTpenbCtWLZzDtB5VJkkqbbBC/V5Zf8KWICIey/71Q+I03J5yAoOdOjdvZS",
	"TPWsJ7xL6Ubhrb5GvlGYUdJVpyulCeumqtbojsnTslHgvS59COJvF/t3LB11l4jhdes9bUmR3Ex9J7Wu",
	"+hs+82UmIWbfiXLSUmlUxRDzrIUcTJVAseDEoJQsinrYbMdI9v70wOwnC4w1/hOR1rrSeoHPBVRL+A7k",
	"G+mCtSeO3tpKZkJqwkpqg2J9SYm21G6W9f2mUmfd8PaMC9ubxAbuQhDGPUUS3wADY9N5mAsO5Jq8uWLl",
	"suSaoSzPZaWgqJIIKl+4pNWo+BArhPdKzm2BO08DsNaek4pd3wyzaDgVmJDRMuM9RcR1gwTuQCWiyFUH",
	"gkb1gZJBREvCQCcE5Z0LDOjHcSJxAutiSD+PCqy5ZG7S2CWq97hd5RQbb+pT7jo5FsVFsMeWZHBC7LNO",
	"tay1vpztDCr9Y31+TKymsR5EZxQpheP7dfUy6AqTs3yKeLqVSN+oGNddAGpX2wygLrcjucFRNbxSQQWe",
	"aDjup9+GkXz8Ljt01LZGs1fbFCfpXppdlaM2jq53LrvR+28HhoYHzobaWG7N2PaXka+fFjHAKpaUDDil",
	"HAmpR5pl2YiKlRQsDII+GhyOD/pgf/Q3F2trJLdZXrC5bRk0qnvGDIaDnKskkkR6zSh1u/CPX/5mteUz",
	"nKnpI41NYZG5/8hO+Vy8aR9WowihNerbA3x6cgw9YIKTuKirfqklnc9ZOar4DR1MqzxiNzeiv15YZ7U3",
	"f0yOkMRPprOiNaeUMVacWttXxK1tHnvbmItsQDXSJcmdGpiBd5eJFDM4vXzjaln5jPOUrpp6mh/bEGxQ",
	"lMbkaVFknNm6kZhiL82HHOxWk5Su1IWcXSwZu5xApCC80/zdvOzqY0dWCDKhIAcPRgtZleSnn45ev64T",
	"kLH5Uo224ciDo0Euia4IhGCAhzG9AKn7aHD/h6P9fcx3sUqfzYYGvHJv7T+JFl1pTtINp6QJGylW0BID",
	"fZdylDFod+WK71ioQ6FoukK+yNhlD5jJd+eDXKLHQVfO2fD9mLwAa2fOqFDkfMCuWLky47kSO92uTH7/",
	"gegEAO1JWnKg+RgvBu8BtXm4No/1Yw+b0GyMG6x4zb3QVLM+ndrmopdhZt72GUJRjTgYbKtFpX1FIOmS",
	"Xl67CuQWC92wvKblw5e1HNp1BaUwoQWKOVKm7CtyNjPKCBgH2rU3awTqLzIaKQyA1fKQbNWKp82PrKOJ",
	"obCvLWkdsQ2oi4z+Y7U+YqmZemn9E6jNha0ogVzVHhaUVmoN0Cq8isy44GrR17t0+AXPc+j3t+Zk+6wx",
	"f6aKJ2sEz/FnlCFe7lKGeBcj+lep+Pulkgu/WD3ebaqY+uI9Lc2q9Om417AzbV9mt9bHYopfqLCQp+is",
	"pMKbgrKVDcFcOWmDzgnXgeMeCrqAbWPsXYPWTFwYgUHO6jYARv0kipu/qWBgfOlKCR2NrFHs0QydSvLj",
	"yTuCMR/eyvPixV9fvBjXdXF/PHk3gt8iQkKzz+LO5Tw1nY/JM9s32XozW9WRqK34j4Z7m61Bwc1eUpHK",
	"nMCA3kSkFJ8LR6m+kO1kg25xRudbkv6a2nskUB07gd2BQYTmiWo6v+Ap6BYPDu8fpI9+SEaMPkpHDx4+",
	"ejR6Mp09GrEns/0nU/bgh4RNI2qFHyEQ9Td3L1kn+rsR10LHqfmdxeyqwkeNIZ/WTI1Gku0sWc3SUR+v",
	"65CKd2qJGEnO0A3uTztgU59Qy4aMZqMO5aHd44JWsdyid4qVUHvCFu21LOP4+ZAUVKmlLFNfxhnUalti",
	"xOg/zn5ZmzUM6gFggLMZvlrvdKF1Mfj0CZo/osMP+pQkOjCAeFp9xmhuXVX4pTra25u5SMMgQnCvW2AD",
	"4x7JS1rmNpQWwq4Hw0HGE2YzQTyVenV12JlouVyO56KC8e03am9eZKPD8f6YifFC51iikOussezc1wGv",
	"tf774/0xaEqyYIIWHEwz5ifMZYIj2qMF37s63EvapYnmaDHxtSyOU+gNqJs1jEDYhDQSGO1gf9+Blwn4",
	"nhplFKPI995bVxoi8JZB9M354BSbQBcGvTOfzoK46CQus2IMo2lmuc86bVLxdv8Nov+AEtVjvBBpIbkt",
	"QT7HSJ/ugJ0y0gbyUfDuQUzPnrO39AH7JRfpn31i+glmn90YuONNOiPwfikrUeepg57s26LCyzbC8Qut",
	"CwskRNZx6tsgLo3ovyylmI9bp/+S26h5WZJclow8e3XsmnKi1wYC4BRZUgidA2HKbSeGFIVUkZOCJObI",
	"UQET/bNMV18MGq1iLBGwuHaksrROPwhBwgIkEqPJsHzOzeNRo7hDd6W/NC/uEBeJ8W5wpDMu2N3Dqb/S",
	"jIPnlYbYdB1kauGpdd9e1eO7Duz1QW4kKpjqNAoigtegbCN166ti7cmt4ec/BWJihluNkc0EuA3sbodx",
	"epER0xu2lCJeYgb4Zx35DuWQPw0bY61onjXHagvImxCkfRBvoeHvFYsLHl05Ye1pPE0SppRvBBypyBgZ",
	"koTpYLixe+Dcf1Mw8fTk2CW7ZZlc2l4nEHIuaLZnJUl7oBNS0OTSHPa56D9uxXRVjKirEdRPdk7pFYuW",
	"JboZwhOdKso0Q7Aa2k2vEL1bSPkg0n6qhQwQir5kU1oUzlqSGl1pVmVZ3VRW22plRq68e6TkXR1b1JMe",
	"i1WLrPkJOu4I2OGKzCqR4E2E8u4b0NsgRAyze6tP9eNgg/PtfXQZq5/2Pjpv7Kd1JKnBDJvd040mzg3s",
	"bAkIq8IFObG1Bm09VruoON08YaPORyYMvMr9E7ap1283yEzjud+7U0ynpbUStbNGznjYEqqRLW6+tLYB",
	"lyxukNNniqMTYEf9bt1yGvXJexPI+1HVZ0PtjqV1ldD/xtBrbEB9BnLW1QXa5gPyTtVJ005op2k6Qmay",
	"Jh0OyagvMMqmmPo1o9AoxjCOWBYJmVJVV4CalnKpGnlh18f4eo+747ir0d3D+SELB/th3Qirb3RE6x7y",
	"z3Jqc55zrjvoeZMax5oFgX+sMhIe8k6bLmZENRvnGnSMVwDtB/cPbl5GOPMU1efFMU3nkD4HMmWdP9d8",
	"IZo9x7ERd7YiaeUrnNm2SAlNFg75/FBwH6QkmRFNzsWtikfwgLiymk1KgDhmXTxQd1KWnTuCtSEgsy6U",
	"fbDgfGO4n5vJhMxeys6lQtV+i6sFeu3XvV9JsIR11+tBPNV/xwvh0z4NFcVeHgsjUP7y5gzTLG2XP5vH",
	"UOfp6YWs5ov/vlB/lAsFaLXhOgH2+32bkcCUBmVYltycuK7dtDxyzRq91frN8kwnix8zOaWNWheQS3az",
	"XCTeiW4rgWYYv3Jnrmefy4uG20PFKtpnrkcugu50kFbMyivbOjXyudpwfG+g8jB22KnTkeYA6J7ltM4v",
	"p0qNsC0abtX9q3mA0EGO2XZyN0Qte5vVRW2fzXZ1zXrx2CZO2nZv42uTVoVt5kLimlNIbDU3xXVVtRTx",
	"0a1QxJLhmoQMmuHVhNCey/jOUKvXtLzElYYgG9bSuOuMkpRcs5LTDRgP4+Xmtu00KPIAJy3UmVdYycAw",
	"BUAVRwltZSsohmZO3PyeNw+9S3Jh0KKUaHtcMP+uz32f0uRyXspKpONz8YuE+Sje2Um7AeKEeFUV4p/M",
	"VywlVQGyktC8BB+/FKmrD5JTRE/02nXAgzV4V7Ii7EPBEj3EMg+Ml2RS962a1BntytbvNUpahnui0BoW",
	"Zm3ZNoGY/N3104rLXNCtyJZEuiECYlt6xUx47eKwTVIxZ3p82xpOo31TP0sCqAaeFRswhiUioLQKnxlk",
	"BhEGSIFtcAQf3h1SAEKArwVjAL8dd6sbbM2gpxdEjImUKAmRvl2eZsS3vY/mv7/QnK01DdlSKVsZhtyA",
	"d8ZO0y740qti4LO2HGKTKrzAa2AKDW08JDacT5D032wYjfVloueitjgNNbhFoEWtW/4lvxsVAWCAyrZ1",
	"NqhUQFK3BmI9lWcofrwuCD9iqNmnrWS1rbDaFxrox+lNwXC/bSNOPUcSFNAxz5h8gR9d8vncSKu3S7Te",
	"CeSILCWQItD1TWJkZ8BJUQUYEi6SrEpROVJWm4ZeYUYdkHMsWIwqty2a5Acx7NpF63fEA/KL9E06VKd3",
	"+Hcrpr9vGiw9ZvXrX18VI27FNMhRt+synZaC5Hqdrzcz4UciJUEyX9993Js2+/DHb+Zb6NXa6Np/mwdy",
	"IxJXvZWYwlIVBn+/w+DToS2UsSrY90bmCprRe9+lh+OWnmR3N2mSsALqZDGhS86sUQvIip3krhEV6Ejs",
	"Vmtrmps7H4Bg1/v9dfDq5i76WuQCW8oaBDOq1VxqhGdQjApu/11CBaRRYAJqZsXX5endHgBNUgnBtFbH",
	"9VtWzR2ulzowQsajmnfPOeDEqdwO1r627Q1Nfd8CUv7BTYrNo76GeTE6aKOZeT8CKabDukU9vhnQBE7q",
	"4kB/cBbpdmKTe3tcHYItiYPNNU2WbiKfgESVZ4xopTw46KvL5Rp3uiW4SDj83sfRfmWiuQZZvSRQb8GC",
	"oRnvshFB6zTJdeh56otY/bGRs1HLrQc1m5nGEJ1hzczXQtPTxnDXQdLmgiymgufKH7ZLb1a+CYiX/P8g",
	"aNzc5C5IDHroRvZ8Bm99GzwZ9uIT++KyIsKYMxXWVFMdyeeOiYXUrhsqwdEsC1fdwIZt5L34juNItFxQ",
	"PVrKKkutf3CUyl6c8janXxdU/2o+OtbPvxWBz3kk++Q87LdgzToRG4RBvkCGwjaILiXc2XQgIxpHgUgE",
	"V17aRWtgUdEh2JkyObdRcL3yGJiMbNeWepZ6ODQsQSFD4d1fKUmkcDkB2cpNwVXQntt6H1zZeuysiIKn",
	"rHSPUerLwCLEVeyis+ca6u1hJdw1TLvZh/aG4n2ak8S8UGHXORejQWxTzttzPkX7iMZi/F0vTWjBbRt+",
	"Bu5w5Nf7T26eWPqV0KxkNF3ZquJWYHhwq753PD0IQRNzCGQlE9WCaN2abhJcE0R5niyIFNa8f2vspmqx",
	"mxaReoZtfmndbRWvv1rlGReXProAOi4jBDC+TCNRsUCpjOiSZYH1DXvJIbWwTbZssfeEZpm/4HUkX00/",
	"EKjt7Ae7IEpUeJlgMY3uz7RkdC3NCBsIbks5wpO9USoSa2K5LUH5CrQk2sMxtt5qao8NmnxIEOfDgxiG",
	"RcXMO7bpoXWl3KkrAz1C6wbLIQxs51lM+ClkqZW9+DXjtRvbiPBPMeOMumhFzzbaA/o2dS4CEntd4ipq",
	"sgPvKm0EBL+E7i2BYfc+uj6on/Y+wi/8H2sc6mFLRFkyF1rbkgG37nALVVS7AqN7dSc//LAzb1A33jWH",
	"9CXjI7O63W8za93w+Lcbv3idNphbGiLv1CUK65nV7TqjjVsbAmZwX9YRb4+R/9zIOIwZVSxRcfUzrc/B",
	"ts9P2YyVxHeDdU13MpuxeT442P/hfOARq46rA6UC/Hu6KoUT6evtKS/HYVilb7/bOXCMxKOZkjiGkjmT",
	"ghGWKRinLmQeWyZgCwBwwSiWFLAg/H9GOM3oGRWj52afo3cwwCACw6DZZwyGsuRzLmgGc5rxoYcPVkrP",
	"ZFhZ3bcp5jpoXGXbDPOQalslzxXDEoRyeAP6U805xqRv2tsbu7DRS7uwwcZYpW3kGZlopkdKl4zmTQrh",
	"NfUpF+Z+Dzcnhj/DOVSrt/k17IpODO2aFA/2f9j0ukXHBiJakoPxvY+jI5T2c6MOYBjulOkls8huwRlE",
	"A3mt3YaDzHxvdll26I4XnR0ug7LzMNKOCC+xS51ef2vdDaxvjkU8F7sqZ2TKzId+/umqce9Qopj0XqEj",
	"Ys5sYksZAnVpRCffcjbFBg4EnMHmU/TzHdKM1208hPs5k2XCp9mKJJm03Rx+Ojs7IYkUAgPZXZckCRUn",
	"LeG1ZTdV47wYYR9ooomiObOSpJauoxpJZWWEPPxAQSNbfAtTDfE21UUHIydApjJd9bLSMKfdTFFrF12w",
	"NCRH7zjpC/B7Scv8tO7HckOCUT3LWxC9r18BK3QecFVH6M1omW9I0sepO6Ow9iAB/MA6u/fRNgH6tN6A",
	"D3Xvtgpb9T2F7qaB1fYuiDqesDatmMk7aplvdrdaY/aMfLHm5Pds65T1p++acX0rSOD2sw4XoL2Ww4ee",
	"gLC2xAkfLqgiAjrKkBXTdwudwgiOTiczjHTPGWZ14N43OBBtJZ1W2IYbcrwB8TS0d94C+c7Mi3cH+TT7",
	"oPeKjHKxY2WiszZwvhW8CuLKqNJkxpa29VKAZNgWfyvqFX7ix3PtnNZi1XZBFUF3plvFqi9vwe30yPvm",
	"4yqQBX4DgRXY+szn04Ebg81mLNFOLYB2xjgCVWTJsqydXWi+ZdRWCllUORUKY8hBuAcX/BWn3eoldU1w",
	"c0egQ4C7URgQChervlcTwoXSjLZz8YI6670lcXxF9JuTwq2c66a6thDuBeZGp/O6lMx6ORxVY+U7d2PL",
	"OWdC17Y0gM8DpfV0EQ0Hj2GUz/WepnNzEvPtsnHq0tbbGjI0ndeJMXc5gj3sXQC13uEyVAKrXqtG32of",
	"5m92h74RM4aC0gL1MdZg3hDyvgasXw6Rg7LkcTIebD6Cwl7oD1/r3es2fG/+BdheUUVgiiXsmkD98txx",
	"IzxtNnILYNc0CBpMs20//XXCCid3JzPWlg6kAqMaoM7gNsjSQLSh3Sb0e7Hp7LSJm32EbEOsoD8wdSvX",
	"7FVPvkfdkV+N12RjLsPX+u9ZvMIvBEF89QuwG+LfIqUzlykIBUJ7sosLgm4nyrt8hkTJ2l6a0CyzhtJL",
	"IZcQxvbu3fHzu3MJfQCMYMtdrx9KIk3Ui9+2oK3lpgt3C7et76r9Bbwgbq2b7praCkY2mcR96kTdhsMl",
	"1gagC7y9j7ZJxg6i11YqpR/25tOhO/WyLe54HmVjIe+mxOe0paVtyHis8eYnMs9992bwAScQsgwOKFvj",
	"tjagLH0/HC7IxPZim4ByhR7U5ksYsmIbQQ0NEy8I12TGS6XH5KlYoUUGXwt7rgTDOJ8rkPXKNzu7ntz5",
	"VXHqS5OCNRx327TqpW/Ato28QlKmKdSpW9bT7HDzt7EqWZ2/25Xsto/upoSIaKe1u2BsuiN2oF4E3M4a",
	"5DB6J6R0AnWvobMhT38TaNjpjtaDg10ZnRw/Vw0TQu23ds3UiZz9c+JoUFHeQAqhoRa88BawX3fHz4yx",
	"YqSC9subuFyzX/O3xPKaO9umqQl48xsNqtcldbNQqBMy9uXdRMENlOurYsSNcdJNyOBytNuneG3LlG+Q",
	"/VXtUtekTUaAk6WzrDUaC0fQvOXGwCaErBzh3+vkN3zRy9s3d/5vg8aI66xPkrjV36ppxkGCpf3iesed",
	"cndi7NzyG+aVjqLQkdHqIzEsr/5SRZDK6HsjOZutEb34XLyZzbZywdw9WNpWoUBiG01C/wZ9R1slUgOd",
	"lypS9zlfC/BnNMsw2tNZZ7QkmXXDuTKnYL7TC7a6VzIyh1I0dvhx76mIDYcibvRq2yn6L3XONE2ppl/B",
	"2Bp2/f9DXOmt0fBppRdMaMgqcH36DDa4UNQ+a8Fn4yQGcmsJM9gcZhlwKl4feBRjtU0kjgrGwakNvjZy",
	"wEqdduODOHoFUiFJ/xd3G6t2xxCXIee6+7MSs07EqgcIvagwwjfTfhLWOax0cNM2Hz9RTGup/RfK4+nO",
	"EuofmPJYqm7PzdmTISwh8cYFRWhiyEbGUqztiIlnlqKMmjFRDl3At8pFnfBkqQwrR5lMaAYEjmbqS1O1",
	"K9bYTRVzL0Fw0Bo+a+VxGzd+c/V1reG9N6wbytUF7V76yNUv0tVT9WmtvshYYPd4sH/4BVsfIor1IuYJ",
	"K13nmedMcCSdtv5B3HSOIXSW5dFE8yu0xDJwj7oaW1kml+irsGCxWy/5fKGJkEsbwHd4uwzGXSQqIKcP",
	"HXhGCofVYWYeZPzPJfS2t5kteOF2vLTWPUj9+AE0Nt0mwCmncJbxpkDRCLr+62KGRPvbtxCManfSdx2t",
	"bMQFLtEFBl7LqmHH6kafxm5JneOhGh47h0murKeSNh/Oj12Xprttg8lnMqeGUVddDoleFTyB2EPbrQkE",
	"5qKU85IpNYR2Tq7BhSzJjPKsKtlGDuP4imIibTjqDLjd6FB9m5Vs803Zy+lqxEdl1R9W+pqurCmlEt9E",
	"UspruvoLY8Vb9Dh/Y+oZBn5bMabO/g4k5sD1HjCoshJkj1wyVjhXfB0ATt4UrnYUJCJSLhShBF3toUzq",
	"nTIx/3sPInckelD2gpW11sRVHZW+HrVlpYtKj4pSplWyTtA3xPINvHzi3r0TzAFqfu29L9h812zsof22",
	"EPOvlch9sGUiN0h/NkXZtf14cP/+zV+0V0zM9cIXP/pT2Dku5Sn2CzdUlhILgpH9BPPy7UoPb36lJ3QF",
	"+brQto6Wtt/Xg/sPb8ONoKqikKU5qNcs5ZScrQrrMQMUI4hRTpic+nTzugtsGP314ODJ7XQYdPUvkFMC",
	"6ZASO0zNzMW2hfasW1ovSql1xmw5vj+U5IF57gbQuVSalCzB7H9fOhD2i/JAkO3OATjYd8p8XDtCmFBY",
	"+w9zKEB6t6dsvrynSMrnTEHx4PYZk2e++gDEiZ388iPA+eeTFz8Si0pm0CKjQsTjtNYJPHpR5VNBeab2",
	"ipJdcbZ0ZImXWDDRUXuC1N+JQQDR8spR86rMBkeDvUFghGoTq+NmEFSnLZjDFM8OIEmlW0jkZzl1ZlKQ",
	"0f5esZIb9KvbnQ5b7SjGjSqaKjLo05PjZn/I0EQm87wSKG5CgZL20sdtB25kAosNr/2ayNOT42F/d2Zs",
	"ZmW2Ye5KKTO3os5k4HSMlMrB8gN+FuATde0EC0Hfs/K9nPqKcOEcttzBp98+/Z8AAAD//1Ql8ZBSEgEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
