// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y923LcOJYo+iuInBNhOyYzJUu+lNUvx+1LlartssaSu86JVoUSSSIzYZEAmwCVznY4",
	"Yj7i/MnZE7Ef9jztH6j5ox1YCwBBEsyLbMl29fRDtZUkcV3368dBIvNCCia0Ghx9HKhkwXIK/3yqFJ8L",
	"lp5RdWn+TplKSl5oLsXgqPGUcEUo0eZfVBGuzd8lSxi/YimZroheMPKrLC9ZOR4MB0UpC1ZqzmCWROY5",
	"FSn8m2uWwz/+r5LNBkeDf9mrF7dnV7b3DD8YfBoO9Kpgg6MBLUu6Mn+/l1Pztf1Z6ZKLuf39oii5LLle",
	"BS9wodmcle4N/DXyuaB5/MH6MZWmutq4HXN+p/gmfMMKdWFey5hmad/A5iUtNc3iL5ib6N9OVfE08uDT",
	"cFCyv1e8NNP+Dd/CI7Un4HcUbLx1tsFBhqsY1rfc3WJzP7/5W5XT9yzRZsFPryjP6DRjP8vpKdPaLLcD",
	"j6dczDNGFD4nckYo+VlOiRlNRcBuIXmC/2yO8+uCCTLnV0wMScZzrgF6r2jGU/PfiimipflNMWIHGZM3",
	"IluRSpk1kiXXC4KHCpObuT1gdy6jDcIpm9Eq0911nS0YsQ9xHUQt5FLYxZBKsZIszdpTplmZcwHzL7hy",
	"RzLG4YMx41P4X/a0lJnmhZ2Ii3oiA2vljCYMBmUp12brOKJd/4xmig27h6sXrDSLplkml8R82l4ooTNt",
	"3lkw8l5OyYIqMmVMEFVNc641S8fkV1llKeF5ka1IyjKGn2UZYR+4wgGpulRkJksc+r2cDgkVqSFLMi94",
	"Zt7henwuBv4OplJmjArY0RWiVnP1Jyu9kIKwD0XJlOISDn/KiHm7opql5oxkmeIG3T0w2Enz6vy6/N0M",
	"u6Bhhj0WM9ldyGum6SilmtqBGLljXr4TLK0L8Z2rtxc1GLRv6Xn9l8Gj5YLq+CSGzqfSrJ8cA9GnmZIG",
	"QlLDB4qMJmwhMzgP9kGbQzGghGBqBsypqGhGuCgqTWacmTtVZMHTlAlyd8oSWik83pEUI7z/Gh60nM8z",
	"lhIpHI8xsHmvcaf1aZqZX3Fx+edK69YJREH1hTAgreqNm3lwCXfs1GQKY5EpW9ArLsvutZKnrVeXPMsM",
	"yHiU+nPGRMrKOwrHtsfq0YsAOap3OoT1TMx6JuFFwLhNiLNruKMQ5sbkNZx2tgqQrqaXHHYqiJAkk2LO",
	"SlJIpfg0Y4g3XCjNaAp0VYQ3hiu6ExzeHUf9zEGYfY7PxVODNtSQfHNJdjai5WjKRiWcAEvJrKQ5IyUV",
	"czYkywVPFuZiHebQSsucap7AHmbS0A8cRiVM+O+mlSYJNZdC5BUrSwSm3O3dkkhl2Fwc+1t8sAU3TTCJ",
	"catLtupi7HHKhOYzzkqPsvbkhySvlDbLrQT/e4X8w9La95Z/RclDRqcsQqRemZ9hkpSrIqOrDh8gxzMi",
	"pCaqYIlZkr3CS7Yy9wLYqyWZM8FKqhmhpGRUSUAHApOOUfaRBS3nEQ76VKwI+6BLSmg5r3Ij7TguNS1W",
	"Y/OhGp/KnJ0gfVrdvUfMpfqpk5KZiWHRloatgiOoj7q+px0YD89zlnKqWbYiJTNDEQonnbIZF9x8MDRg",
	"DtObKYdwJbLSdkW01DypMlr6E+3hIqqaOiFsnQQYEW9O7ZdeQNh5hDP7+RUHJL7GCH81X/LMiHVtnDAg",
	"ble2pbx2Wh9FS2yrpiPzBE8cQd4D6rOqLJnQ2YpII2BRNy6AdyBiqTGZ/PT09KcXzy9eHr96cXHy9Oyn",
	"CSolKS9ZomW5IgXVC/KvZHI+2PsX+N/5YEJoURjqY0kBE1Vu9jfjGbsw7xt056X7J/xsReEFVQuWXtRv",
	"/hZB0b576Upe9gSC3Qd0AeVKqsjxc4cysO2Af4zJL5IIpowQonRZJboqmSJ3Qa5UQ5LyxExFS87UPUJL",
	"RlRVFLLU7a3bxQ+NOnF4YDadSaoHQ4DrbTcZgE5D0nDAOIzJ3E46aNKqif1mckRotqQrZCljMqnZ5eQI",
	"wQO+tpTz3TFqAHCgVm4syd2MXxqCZg+N0DQdSXFvTCZLNo0Ns2TTmhkD1OVU0DkzRA1ZjSGkwFPsLI6v",
	"vpfTMZmgKDM5IoJdsRKG/lMbli1pNCtF0dS8CIcDyrSZXdCsSWvcbdUHijMNgOjYcxkMB0s23XhncYh0",
	"qlMNJyhkcWXkCDpnpZULNFBEmhvZQ20hdX62whGTlDWNaIQ/UbUIyQpwUsP8WnRGEcuRgbmRZIGCBOzV",
	"jIzCFf48JmfmZ8cnpaghzGsETKiqNOzLis1eb2lOapCwKkBToJr1SK2eyW9vlHATbG1QianXHc20xQEs",
	"FcTlBXPau9jEFQzMRSSHV1xpRwaBrvdDXxfSnOXhehs/a7Dbnl3XU8Q2aKnKCdWLZwuWXL5lymryLdOD",
	"0Wq6m+9oXSsnb+iFAbi7Qup7lhlEsQCE8jiSobwOELmkCs0bBvJmXKQ4i+Mj0YHVBU4btZagXLVgfqGW",
	"X8nSEMdxVDICjhldKQziFzqTlUija1KyKpONYk1wJaf4QftK8dDsivyw4Z6H9sI2XPlLLtL6xreCvx6A",
	"iViFuvs4+tiUVqhSMuFUI903u7lg4uqKlmZTK6VZfpHJxD2HXXsJx/LnGKNwxtbOXdkHpGRGBwUZnxKF",
	"Njhr7ANa+IEllWabjMD9FlbPWoLH9fmDzfBCaVZcJLISEej/pcqnrDQIBVZGBHa3QLs6Zan6gipr0eFG",
	"UzVMHm06Zun2mzuqfkgRV0WwNXJXS7AxzQVXDE0nlJyDifN8QLi6NzRcfcmyjHhEtDPQSi8kyLSJTFmb",
	"c5Gf6RU9RbnAigdmLi5SnhhtyUgtORUrv8/6Hri4slePrKxg5UyW+b3xubCqoLV3SlBpzBnsD5sjKHiN",
	"fShYolFJU0ykxM1n1LR5yZQak2Nhz5gqNgxPBqbGr/CbqkhBv9TEGoMt5QsmbnBFb+CO86IAVCKAEcPe",
	"F2Upyy7I/Gg0X54QZh6TkqlCCsVinos0QhF/Ojs7IWgoD+4RHCJ2IHJsxLokq9Iaugq6yiRNiZJI/Dwu",
	"4WobaJZldmlcmGuEix2fi2dmsof7h1448Wa2lGo6pWh2mVZqZcCdEVioW5SVcaTQlAtCyZ23TJer0dOZ",
	"ZuUdfHXBKFjyzPIc1Clrq0VjjeY5mp7M7TDl7TAl0yVn6Zi8BKONE5HtgBa2zHVTo6g5ufKOsuIRwEPG",
	"mQDITCVRMmd6YYYJLRNGtGcfkMZympEpTS7lbIYghAeFQARqTddpkjOl6Jxt9ozAvdfvRyHrign9kpb5",
	"qfcBWfMX+NjsjwOeZszZUmq42s5vFIzeMVnhz70L+1lO3wHuRdVxQwGc92RoEFaDIY2cyuSS6eM3e6//",
	"7ewMgQv1K5SMlbnekgi2ND+qIZkUJbvislIXuJ6JN36yDwj8eDVtfSFjml1YCGLpBY0Q9eOZNdhYomFE",
	"Bf+FldydiZHnTGmaF4bOWDA1EOxA1HyqtCxRmH+Z0ZyJRHopswk85sxGZsSolBThku/eHT93JO1n8KT1",
	"yvEttkXzkAPEPmwd7yZ4McK9dzOGjkuvnj/cj6FFyWYlU4sLcKhErsJTAq/vWFxVC3DS2O+BbNnd3FHo",
	"nqmVKYAyVK+VsoxBDQ2QgZKUUtCrGU0WQHqueFrRDB3OS5jFWyu1lMgG7SCWoRclTcB03Gur2/0Qv5Cv",
	"ttdNCxuIANWZB2k5IxlV2u51a0hdUnWBeJb2+D8RsQ1uvK+UJvblGrOslDDRZcUmVqe2T2qjMtg5wDnA",
	"0zu1e0cxPbRcwuCfowl5oVdbGeTBLe0OJ/BJW09z4Itugu51PM9ALl9Rpd9aH0Uf3bRoIMsaDczN1L4N",
	"ntN5LQu407XbiCuzUS/9cKAXVT4VlGdbAGu49GOzAvAnxtRaOFXw2OO//CT9x8Jn7NkqiWmFnoxmfMZG",
	"iXmJsCuwmVkXmZgr5NhqUaHRLJVLMTSCUwl/VsWQMJ3EWMQ2FnG/OFgqKvetXfear/ETqi5fyXnffUPU",
	"SybnJFlU4tKySS0JJcAdtSx4suc4JimlzEnKkFKm+J6V78yRD+GXK8lTkI9BPmqRsdg5ZDJi9Hpm1uM4",
	"h7arHJPXdOWlu7zKNC9AZBJMwbvsg45q2Q4g1jI2iA8abhCaatAyy1577NvIJmdwbBuEE9h+RzoBanBd",
	"8cRwkatmxM/2EkD8oIbrkH2zdKB7Bt1RPGiHIX2t0KUb5Hqghm6zJ1RY44zH00qrdUYYkYeRa3McXMAZ",
	"7SU/VqU+o/MNSMC1R4AYJUWz+brz8EvZVnAAg/mWgsNmZt9nTA6OaRtygW9uJBgIIutOLKHiwsgttNTr",
	"jKFcOauHUYFppeXIfhW3h9pziio7TkZG5xTTtV5vl2tO2w4w/mLaisWBqEtC6QvFmIjFHijtrABchesz",
	"7zsjYGDB326tm4ngsne1O5JB3PauhDD+1QXC0S4fP4Mv3qJuerPk8IqVyjrl1nPuDdTOjTNs4EYMZ1v2",
	"EGu9BmoJFvcUjO1LCsFJho6qjLECrNUGBal9rxKXQi4FrgGExajlup7tLSskouu3YYNx0vFf6xsIFjbn",
	"4Ck/HB+MHj8azdP08EH68PAHdwdHg/9XVqXDoQHEtZXaX+bgcHw4olmxoPvB3YQ/k7udse919w+r2Mnr",
	"2FjGx7Xw1oRkewxeN/Lu5ZxRaxVYVDkVRn5VVQ6foTRXsoxRxci04lnq4s7B42pIA1VkEq5qgsqHBBJd",
	"fwIhi9Yci19P5lxPiP0KjKxR52zrwms8aByFRx1zojFo+Blj1mmWvZkNjv62HuBOnSvZfPVp+HGNdLrW",
	"uej0U+K+QC8GaqZRTQBjsmKOIPMAPN+OIm1Ngv7pbH1fzci0MxvZljnHeIUDlc8Ujj/9htjx50wmlxlX",
	"uj9eANm/NUHSkoFDAQLMWUoSVoLaC9ogRhVII+xZS1XiQH4rl224nhdCl6uYt7b7UicGYH2GBu6nTye0",
	"T3tIcetG6qHChIweQvTcIlk86tz8SuhUVhr9mk5ftrKnk0uteYs3hNIWd13QnIqLZMGSS1np9WEFp/Ay",
	"cS8HEX1uASXL5RVLCc2kmGP+hQvB2ia+t7mWnqOJW9I6C38hZDVfhJ45YDo0cGAVnCWMaDnHLaZ8NmMl",
	"GMzhBsFibb4mlCwkmBAzEH3Iu7evnDssYlsckzMJLBKi/zAI7u2rofkpoZoJqhk5H3ycUsU+7X2UwsvO",
	"qprN+AemPp0PYhqP+cD8v6cGVZlFaZsdphH9sCHdpXUVMFUwUs9VvKZKOUg9ZRlL4sFlJ94fjNkY5tmU",
	"Wb7wXk6V81DUIGzAJRDFQNOxNOwipx8GR4OD/YPD0f6j0f79s/uHR/cfHN1/+K/7B0f7+10Rqvt1J1A6",
	"y3AhGO/CShaSYLOwmSwhkMZx55rDtZBvB3odPVKmaUo1BSEiTSEImmYnEbNrg303NlNOuS5puSK5HcwB",
	"9Ji8NttAQv8hDE+1/uFcml1AiFeluJiTCR1Px8nEkPEah2yMeuuOilLCPo4Gp0XJNSMvSz5faMN8FCvH",
	"LAdD+UCtpiUT//fURjnJcu7esFL1KbxATvX//l9XLBv0nNOJdS4885pd885Dv1pOP/Dc6Dj39/eHg5wL",
	"/Gt/YzyDH6QH/k+DAL/4ZemyYj3f9utfCRWJuQbM1vM8eUY5/ljQStX/GHkZbDAc/L1iFX4IYzSewb8r",
	"hipdZU5/5KlUM4Wihiy/0L5zRr9/PIIMnwW5ODYWA+M3v4hYFtf1hm5ZffemZdnLOOxD4Bw+dNllwXhR",
	"1SBMpSBmGJmeeQs5BEvJjGdMIRsWLGFK0XIVI+ktlhc18N955vjt8fM7QTwJCHcugqPNmsN0uzF5yo2G",
	"JXCl7pMYG3f2LCs2OHY+K2Xut96ngsUO+ozOa8BpGY3AATAHhwskMKMzBtb7DKkReCKDE0Yj+5zchZC2",
	"RaVITi+ZX3AjkJtmmRNG77UIlaUzv7ClNaY272STRqHpvOFntRFbd8ywdxwnM2LvlOGz8fUsaX3z8HTb",
	"WXovRV2q0yrPabmKZe/mRQZ+Y5JZoR4zOB0qjMkzdF9hAJR14rgIfPOTwxyIEjDPxxF7t41h2ErWB/eG",
	"XfAWkcG98or6t4rhnkPZgudcD44eDgd5wHv7uNmn4QDySi+mK8jNtlIFJGbUliZrduSiQdc9cbaU/Leu",
	"pIJr+VgzqfvxAKnPFhJe8kyz0jB6N9jQsfxXx395UXP8aLqXnM0Uay40GrJSH9XHHTKv1ZZstW9HYXD/",
	"LrsKbq2NFW+ZrkqBln8QFEG3oY6lcSsVwhZ2UWFr80IHqPsBuC+cHUB/W5xCu9U1cSni1A8EGczMKUdg",
	"Fa6KwbD+ZVHpVC7jsoa1/jyTYsbnVUmdMtEiz+olL5V+W4kNbh+ILhaKo2ZmKOrMfFjHRtr5SFmJIADK",
	"p+6CFEzJjC3JjBr+qIbEZi0JKUaQ326UxSRcL3B+oyc4W4dPMpkyCJwClrZcmLf0gq0sJRd3DCHvjYgC",
	"5o5p0OlWKjqsQpdUqBkrydOTY0jBc/xx3BN3BXLPKxeb3rVcejkBhBAjYhhMg7nsx+ONdqn2LO3dDcML",
	"joGevbW/0pK7RIg2gFzopVzSCG97I9hoSVfkyn6MqT+Q/y4VBD/nEEZuM60hOQ9izEnJIIc+h+g4Iw1N",
	"PhoO/mli7QC8xNxuJycuIJ1ROXemK83i0z2cI3RMzpYysiawhdtJ005amxdJmV1+kVFtlM6RN6VhdQOQ",
	"4ewg05VfdB+gwUebLVnWjl4ftPtyi/t6WqWciWbahJXTrB6o1hEHN4xax/rWkb02+HQY42taFOaM4Zbd",
	"pRCzZUhZ1j4RmmMxk8iGV39hrHhbCREtj1LHaS4DxLUe2pyuyCVjhSFKwknqcREq78zTvdBaO+tRtRpu",
	"zhhxaUWV0qYSV9v/vWFgaeH62Medgpq0YGSy9P5VNiHWkYiJenW9BEQfMwmc91ya/wr2QTdkYYxaGJJJ",
	"8xAm5PW70zMjEk8g93yyVRhj6yD9qfWdUQzKfebQsUv9apkjbJrVesRqpS9Hhr/1TLavlnAG6ilLN3MU",
	"mzu1XZrYWzY3bLtk6a8+CKnluUvTkim1Y/kpS3/jmCZneklLtgYNdw5rcMmYF96ToHaTsXcqPWUJvjua",
	"sPyU2/hwkGCJgAsbBud33bPa2O2csqQquV75dKAWxds2L2RdQsgp01XxVCmuNBUahc1YUl0o1MmpkeWc",
	"IQTkLDMK8cN0qbO1b76AvDa6Rd2H/hTEryWYdbcQPU8Q3571OpBOMfLLWsSsR4iX5PSnpwcPHyGaqyof",
	"EsX/AXUUpivIODACmK0OQ1y+pM8A7JiuWiYemA18+EhuBnVFkfFcotA5OBocPpzuP3hyPzl4PN0/PDxM",
	"78+mDx7Okv3HPzyh9w8Suv9oej999GA/PXj46MnjH/anP+w/TtnD/Qfp4/2DJ2zfDMT/wQZH9x8cPIAg",
	"AJwtk/M5F/NwqkeH08cHyaPD6ZMHBw9m6f3D6ZPDx/uz6aP9/UdP9n/YTw7p/YeP7z9OZoc0ffDg4NHh",
	"w+n9Hx4nj+gPTx7uP35ST3Xw+FPXcOBO5CRKXc2vgbToFB/Ln8MiL24cV0bKu7ysu6ttZwSaTZVXgtCh",
	"H8aWkWNBsPKUDcRQzsBlx8IANRenaB6c++2Q4+fnAzQuORXbR4P4pDaKqwDdbGLtNiOVVfM9KEc0MtRr",
	"D0v6jI6fT3ry+y3IbKk949pf8oydFizZqEjj4MPmNW3Gpprbx4zr5hla5Vq3Equxdw3wsNEDbcA4w5xS",
	"OPraZaoXVFhndDMshKrGoOAts3UZqCu0VKMxOQukic8Hvi2ihba8En/VXQJnVS7qpCyKlNfSKrvogA7H",
	"JcNWPIWsx0PTRT2id5BHa6vRyAqbpDYcMzoG0JmPXfMaa9LozfnAZjV2vGG/cNs84F+5XtS+sa2O2ind",
	"iXMiR49+aMXSIUlZYZM7gI44x9Qf/G62lTWD6+hxsnVudbguyLIzXqD51xGkVZFJmqL+hZFhUTMADvYW",
	"VwMFzVyI7nUFDxA0GmfXK0vckNBwKwLCLbC3/stv3hfmuce5Gt4WiNmUlMFnjqUMw6u0tgjZRHdWXhm5",
	"4yXPWBCIBoBmOIl9zfzm8otquT6sMXBbMFAjpseHmwGLcCKPbl8YVgLy/blQg3WEm4Sj7arH+9+V534p",
	"QriW6JUsPd2kubVZiYLPao5FUyMUW50uCJSk1opKzqv9/YNH3v5rpbNKGcjvGJa1tANG5kJhyuOBFaDu",
	"qKZ7I5qIF1h0d7C8ekPwp+EgCw5oR9vKLbhGWrceFO/xW28YQpprikKHTXk6raZrarKdMgFWe5+8ipGL",
	"CuLp91Tw7QRzem2NTC1tbTxHJYM3zcP3cuqTWckzNyaW9JszHT5H1QtMu1Rd+kx+93cm5wrdWIIxW2Wo",
	"yHjCdbZy004ZpgiAI8U8Wg39RowWgclU7l0zhhQYz3EXap/q5tQzl9j9Xk7vAe82r5tX7ihIAwYjteY5",
	"G58L59MTUqNpZLqCrGCs/MOdubEopZaJzFyNOH9a6IvBw/Tl8yFNbVpKSGMzIzcDY5rIIYuNVCYCC2+c",
	"bXzbsqOxQVwdNWfpWxPRssBE5+Y17JFK1D8YyrDZiCSLddVI1281EAv9tBCoVv8VlQj7th4hBlSTSy5S",
	"m+Cy9Z59gF6W/SynEDufZb96p5WtCkLVZSbn+DCMUQ5fP6PzuHurkU4SLQFZW7CCMoZa1tDXlFi2iWX5",
	"/MhM++Dw9/+P/Ne///4fv//n7//j9//4r3///X/+/p+///9hCQgoaRLGdcAsoOUcDfYwfnpPzfbey6lC",
	"s839g8MxvARmk0pcXqAccxiE15788uNgOJgVanBkxCioWm2km/uj+/tYGfYCsg7ZUvlqxBCijdVi2QfN",
	"hE3LGhfW9WNWciEr7cuyNdaHU/gV7sV3bsvadsYrpdRrx7O1irFI6kXN+QYZF9WHAP3AKz2yV2XjzyOh",
	"bAZgoPrWztkuIfxs+MiHLG/boGNDnZsQTDat171am8m32mUd/tlz4J3IASRTYk6whF8dsm+/bZUjbdSe",
	"60hi9uU66p2STC5ZOUqoYt7Caadwi7LRJ+cIC+eDITkfLLlI5VLhHyktl1zgv2XBxFSl5g+mkzE59VPJ",
	"vKCa+/YYP8o7ikzKSgDL/PHNm9PJn0hZCTIB16vMSMqVhlDACbEMmfrIQFeZ3i9Sjc/FU+VEVZoFxefc",
	"K+TchQOdD5wd0cY2ohnHBdRDpdmihIwWqsj5oCmYuvHOB/XZ51IZ0QMkoEtGNFN6L2XTam4L9SnCqOJQ",
	"MdcKLi6OFx3bPCGpTKBSOqQmZVljZ9HCHH2pQ+aHi+3r4Q5JIgse6qKTdlXUsRlt4guxdyvqntm/6nSc",
	"91glkFvXOZb+SSVT4o4mOdUJJujQRFc0qysctm34Z1gAHqRM1S60C3AkszSIuWv2DWkXU/Z9I1zRHah+",
	"GCyQKyKRww1rqxrUzFsVVKlWv4BOPlb0zG0VAAg5NoKART5XFrMOlg6qJxw/DwJvQVC1XB8VTaqJL0o8",
	"ZcRQmLTKEPvNUtC8CIELGPcly3pfQYAyAKH7wC9kC9u19ct26y1FSFpMIIv3kzpz9WqwgxQEuimnWjs7",
	"vqtkOCR8zMYuQcbHywTxUuPdSrd8yS5UN5Eqi7G7F9PVhQtb2iWK2RU06a61J8WQi5R9uODiotlRq9Uw",
	"q+djSHzSsjKAuSHjFAPVxMqXijD/l9bpTjYEabcyEX+UNl03lbP7pUrhxPJ8fXmcBgStbSAWtgkLsoM/",
	"q2OYrd61MY8Vciml7RYWVOTaqSBb3Dti6BkY+Fu1uIYNi38PUPTMVJVZfKJ3b1+FOe/1bIRrxbKZ95zK",
	"pcgkTbeJcKordvlLxdRP2G/fqX9GgplPVFBypkftvLOY/lpP+C0lioWk4hqZYmHaSVcnr5QmrJtkXIMz",
	"prnLRhuLuuYmyNBd6L42G/jj0tzbpKRt6tginj3EMqyucB0Cua62IT7zpVkhJ8HJstJV7gZVFJHGegTA",
	"NAvEFIANijijrIvd0Ixm4wEPzJyywFjqPzkZtf0Cnwuo2HEXJD7pgtEnjlXYun1QnrykNujXlzVpay1m",
	"Wfc2Ffbrhu9nXNjmUa7c+nJBzeYS36EIY+95WIAAOAl5c8XKZck1Q12Gy0pBIS8RVF9xmdLReluxMo+v",
	"5NyWb/TkCytJOrXANTYyi4ZbgQkZLTPe0+Uhgl99pfThcrHOvH8fa0xilfiE2dwXayEPoLGf6Z1eh7hG",
	"AbsOso0qYyWD6KGEgT4OhhMuMFkCx4nEZKyLz91QunH76lpukhjC1nvarlKQjd316YudfJXiIthTS0A6",
	"IfbZ5mpwuxuv+sf6/PhiTWMN6c4oUiUnHtXV+aBFWM4MXG+dP9eoiNhdAOq22wygLrfkBvVVNTx+QcWp",
	"aKjzp9+GkYITXanBUfYazF5tU22niyS7qqZtGF3vuHej92MHhtkHjp1O9rX9ZeTrBUaM3YolJQPGL0dC",
	"6pFmWTaiYiUFCwPMjwaH44O+sz/6m4tjNgLuLC/Y3PaPG9UNxAbDQc5VEknIvWbEv134xy+PWW0xFmdq",
	"+p9jU1hg7r+yUz4Xb9qX1SiyaR0o9gKfnhxDQ7DgJi7qKndqSedzVo4qfkMX0yr/2c0z6a+P11ntzV+T",
	"IyTxm+msaM0tZYwVp9bQGAkZMI+9IdJFjaA27RIOT82ZgeeciRSzYb0s5Wq3+ez9lK6a6qwf2xBs0CfH",
	"5GlRZJzZuqhYQ0KaDzlYDScpXakLObtYMnY5gShMeKf5u3nZVZ6PrBDkT0EOHowWsirJTz8dvX5dJ3Nj",
	"J74abMORB0eDXBJdEQhvAW9uegFKxNHg/g9H+/uYO2R1Y5tZDnDl3tp/Eq0q1JykG6pKEzZSrKAlBlEv",
	"5Shj0PvQVZeypw4l1+kK+SJjlz3HTO6eD3KJ3h1dOcfOvTF5AablnFGhyPmAXbFyZcZzNaS6Lfr8/gPV",
	"Cg60JwHMHc3HeLMGf1Cbh2vzWD/2sHmajXGDFa/BC0016zM92Lz+Msxy3D7bKmo4CAbbalFpX9FTuqSX",
	"1656usVCNyyvaSDyZVyHdl1B6VdodGSulCn7ipzNjOIDNpR2rdkagPqL6kaKLGB1SCRbtZJrc03rSG0o",
	"XG2LxUdMKOoio/9YrY8Ga6axWmcQao5hX2IgV7U3C6WVWtu0yrUiMy64WvQ1sh5+wfsc+v2tudk+o9Wf",
	"qeLJGsFz/Blltpe7lNle57D4KhWtv1Ri5herN71NlV5fjaqlSZU+lXl7lfcaZaRr/Sum6IUKCnmKjmAq",
	"vJkpW9lw1pWTLuiccB0ERUAxHLCbjL3f1VrPCyMgyFndQMOom0Rx8zcVDAw7Xamgo4E1qpWaoVNJfjx5",
	"RzCexluQXrz464sX47ru848n70bwW0QoaDbZ3blcLRR9suWvnBmuWe2L2tYZ6L6wiS8UIhhKKlKZExjP",
	"W5+gtlavx3w708gG1cFX+dpI2Wti7u9cdcwAdsXm3psXqOn8gqegOjw4vH+QPvohGTH6KB09ePjo0ejJ",
	"dPZoxJ7M9p9M2YMfEjaNaA1+hGtL8m6EtafhtPbO5Ltq5FHbxqc1U6PNYzvDVLOq1sdt3WzxlkURG8cZ",
	"xhD42wy4zCdUkiHZ22gzeWi2uKBVLO3qnWIllOGwNaYtBzh+PiQFVWopy9RXHQet2FZbMeqLMzfWVgkD",
	"WnAQwJgMW6zRY6F1Mfj0Cdwu6LaEhj2JDuwXnvSeMZpbhxx+qY729mYuKDMIptzr1hrBEFHykpa5jTKG",
	"iPTBcJDxhNkkGU90Xl0ddiZaLpfjuahgfPuN2psX2ehwvD9mYrzQOZbQ5DprLDv3Zetrpf3+eH8Mio4s",
	"mKAFB8uK+QnTvOCK9mjB964O95J2laY5Gjx8WY/jFBp46mY5J5AVIcMGRjvY33fHy7BnLDW6JAbY7723",
	"DkME2C3zC5rzwS02D10YuSDzmT4Ii05gMiu2bU8bBQBmnZbXiM1/g0BJoDT1GC9EWkhuK+bPMSiqO2Cn",
	"6rk5+ejx7kH8054zl/Qd9ksu0j/7nP0TTMy7seOON1yOnPdLWYk6hR/UXN/i+lPd8/hLrQtrR0TWcep7",
	"lS6N5L4spZiPW7f/ktuEAlmSXJaMPHt17DrgooMHYgUVWVKIMgTZyG0nBhSFVJGbgvzuyFUBk/yzTFdf",
	"7DRadWkix+LaR8vS+gchfgtrsUiMvMNKQjcPR426F92V/tJE3CEuEmMD4UpnXLBvD6b+SjOO7ZVDaLoO",
	"MLXg1Hp6r+rx7bfBRW4kKpgFNgqCp9eAbCOr7atC7cmtwec/BWBi8l8Nkc3cwA3sbodxeoERM0G2lCJe",
	"YnL8Z135DuW6Pw0bY61onjXHagvImwCkfRFvoSu3LXC8hZwQ4zNV5NwwdCR+dNdD2hbr8CEXGoqHQKad",
	"o0dhsXjX9mUqU1viI6FZxkqSYxAVVAPpbp4rHCxSZq97xmedz6EmIWRLUvLz6ZtfBqHiYm66SzYexOPT",
	"muOCzalKEqbUrAI7Bnay0ZI4ud+6sMoxAMttIv474SpgKxqFKMC0JvwFcTHx96EaUCoZZlKizT5bkZJB",
	"p3zzjWDLVqbweprxFI7P95SPlFCNAD4J8znxJO5AxMibgomnJ8cuWzXL5NI2kIIcEkGzPXshluxMSEGT",
	"S0OSzkU/UVJMV8WIuiJf/czxlF6xaF2xm2GP0amiol14rBYkxoOtwL5NsgBrl2xKi8KZ6FKj0RsMqDuL",
	"a1te0Gg/3x7De1cHy/Xkt2PZMWvzhDZmgiCOzyqRIL+AJhkbwPu0B/d6y8f1w2BDPtv76FLOP+19dC7/",
	"T+sYZ0NkA0Xe9WIB+xA3Z2druFhDQ5DU3iSXw90U8W6i/6dhdMIgdKF/wjaP/e0GRb548Ybd+bqzJbQq",
	"LWSNog9hn71GuQfzpbVguWoPBjh9qQc06O5ohVi3nEaXh94KEP2g6tMbd4fSuqzvf0PoNTagPgM46/Ig",
	"bSMXeafqqgdOtaRpOkJmsia/FcmorwjMppjLOaPQbsswjliiGJlSVZdwm5ZyqRqJnteH+HqPu8O4K6of",
	"N7kxnSxsTYAbu+x23f/+u/67eSvQQ5Owjwrk7EIiqJHVsTcf9DK4XUYND4ir0NqESYhrpK4Xl02ZcJmG",
	"IcvFxgS99jWspoCtH29EAGs0/+zu8Wc5taUlcq63UDu+KKz0Laijtti0XCNB23j6K55W1LZ0Aah4cP/g",
	"5iHizDM6n3/MNJ3XCkedp9x8IZqlzBXkyWcrkla+cqTt+ZfQZOFogh8KyJSUJDMS47n4ZpABgcz6e6Ge",
	"ryw7pAtr7kAKcxQ/6uF+biZtGwJtKAI0pbB0s0P30Ea4Ru9xeAYGsq+LbEmwhB1V/Otgh8+1h15U0CBp",
	"YYT+X96cYW67NQq0iNiQ6IWs5ov/xq7vBbsArjbgFoC/37cZCexWUOtqyc2N6zqAg0fwrNFFdL208WMm",
	"p7RRYAhya2+Wp8R7rm4ldA77zGq2O60rRgHYQ8Uq2lG1R3aFPqxQzIGVV9Z6Fflcbbi+N1DeHduW1emb",
	"czjonuW07i+nSo2wAShu1f2reYHQK5XZxqk3RC5727JGvSjNxqzNJhzYEFXaxqbja9NWhQ1VG9Q1p1Be",
	"wKCK6yduSeKjWyGJJcNFWREYoaimhPZivh3J+DUtL3Gl4ZENa5XJ9ZtKSq5ZyekGkIfxcoNuOw2KTMDJ",
	"C3W+J9aPMVwBYMWRQls/EEpOmhs3v+fNS+/SXBi0KCUaiBfMv+s1gilNLuelrEQ6Phe/SJiPItJO2r1+",
	"J8TbEyAy0nzFUlIVIDkJzUsIF5IidVWZcorgiQEAnePBSucrWRH2oWCJHlqdipdkUncDnNSVRZStkm40",
	"6Qz3RKHrOczaMkADNTGMc++j+e8vNGdrDSe2MtBWZhM34DdjxWjXN+qV7vBZmwPYvBYvahhJDPoz+ZPY",
	"gARB+YlmE3ospxS9F7XFbdyoNaB9aFHbj3/J70ZFDtBV8fLvoDALsLz1IdZTeUz243WP8COGC37aiktu",
	"BdW+JMbnwPSDWOskIPuBNcVTAF+/Spd8PjdywfiWfXxIelhKICuj609Gd2tAslDYGhIukqxKUQxVVm+B",
	"VndG8JJzrL+Nyo2tCeYHMXTRJUh06DD5RfqeM6rdEp3cXTF9r2m+85C01q52exBwKyYYjlJzI5LH7LQt",
	"er6X0y20efxIpCTIl+zDt71pJpPLzGcTxzHvLfRZ/llO/+zfvskLuBHht156TPKrCgOfdzEgeGhLtKwK",
	"ds+IA1AxL+h4DTDuhtvSb+pwjyYJK6DQGxO65MyaB4Bs2Em+NaIBPbbdam0JfoPTwRHsir+3A0c3h8hr",
	"gQm00DUAZWTSudR4fkEtNcDub+nqkQaB8twsLFB3T3B7ALBIJQQ0W+XAb1k1d7heasD4Dw9a3vnkDidO",
	"xXawk7StFmgk+R6B8Ds3vjSv9hqGmOigvtjOeoBRTIf1r3rM2CC5n9S1nb4zludWbvOfe4zAgi2JO4tr",
	"GnPcRD6JiyrP6NB8c3DQV+HN9Yl1S3BxXPi9j1X+ykRxDXB6zl5vwR5DM1pjI0DWmaXrwPHUF2j8voCx",
	"UQWwBxSbydcQS2DtbdcCy9PGcNcByuaCLGSCDd9frsv4Vr7njJfUvxOwbW5yR6C1NZXXQewZnX9/4Opz",
	"V3vJJs0hHQhYXpCpa7NwITTWBrEgD5RZCg+uGW5M558DyJBE/d0SVl1vHmtArAdLMF9slALP4K3vU/SD",
	"tfsc3bgKggfJmQorK6qOQP2NaRvUrhvqQdIsC1fdIErbqBHxHceBZrmgerSUVZZah90olb0w5E2Rvy6o",
	"/tV8dKyff696hHMJ9qkP2GXGWvsipioDbIFojs1eXbEGZ+qDYgU4CoQCuKr6LlwCqyAPwfyYybkNFewV",
	"88GSaHtT1bPUw6G9EcqXCu9+SkkihUvvyVZuCq6Iv10XGueadWD/WNRnZKV7bJVf5ixC2MReYXuubege",
	"VvJew2mb3bZvKOKmOUks2j7sremCJIhtPXx70W7RbsmxRAjXMdiwVNfWOPRHI3vdf3Lz1NEvhWYlo+nK",
	"tlew/P3BrTq/8fogIkzMIdyXTFTrSOsOnJMATxDmebIgUrBbDiCtWvylRaWeYTdzWjeVRvxXqzzj4tK7",
	"96GxPJ4ARnhppCr2UCobiVpbbbFlJpIL20vQdr1IaJZ5DK+D6WoCgofazhGxC6JEhdgEi2k0uaclo2uJ",
	"RtgndVvSEd7sjZKRWK/ebSnKVyAm0Va1sfVWU3tt0NtIgvQdXsQwrO9n3rG9Xa2L7ZtCGWiFXPeRD8/A",
	"NtjGtKhCllpZxK85r93YRoB/inl51MULer7RHtB343QxiNjSF1dRkx14V2kjIfgldLEEht376No9f9r7",
	"CL/wf6wJrAg7v8qSuejWltC3dSNvKGjclRDdqzvJiMPOvEFnC9cD1ze1iMzqdr/NrHVf999uHPE63X63",
	"NHB/U0gUlhasuxJH+1M3JMwAX9YRbw+R/9zAOIzmaCNRcaVsre+K27pubMZK4pteu15jmc1rPR8c7P9w",
	"PvCAVQe2gVYBfmFdlcLJ9PX2lJfjMK7RdxnvXDiGwtFMSRxDyZxJwQjLFIxT9y+ILROgBQ5wwSiWB7FH",
	"+P+McJrRMypGz80+R+9ggEHkDIOexrEzlCWfc0EzmNOMD73LsEFCJsOGCr4bO9dBvz7bTZ2HVNtqea5Q",
	"nSCUwxvQlm8Ogufrd6dnhHEoJTll5Onps+NjqEcjEgnBekY+JW9fPiMH+w8ek7v0kpLXx69f4AtczO+N",
	"ybGwSiSU2E1c+wn3Bs4xZeTd2cvRD9sc5xt7FqOX9iwGX8RAKRPN9EjpktG8SZR8vcopF4akDDfXlXiG",
	"c6gQ5a5f5QAgumN0PNj/YdPrFgMasG+pHMb0Po6OUNrPjQaCobdTppfM4perGVHTOW8psJFJsABs7FR2",
	"SJ2X1h36gH71MFLEAumGy2lfTygc0tfIamHdxavKGZky86Gff7pqoDoKMZNerD0i5s4mtrApELRGRPIt",
	"p1BsYHrAjGwSRT+rI80Y3cZDIAkzWSZ8mq1IkkmLuD+dnZ2QRAqB0euuP50EImFpvS26qxr3xQj7QBNN",
	"FM2ZFV61dL0rSSorI1fiBwpahONbmAOK2FSXII3cABYx6ePeYbEBKI7hFZrusTSEVe8T7IstfUnL/LRu",
	"WnVDslg9y1uQ9q9fQC/0k3FVB4fOaJlvqJ6AU3dGYe1BgvMDC/DeR9sp7dN6pwCUydwqYto3Xvs2jLi2",
	"U0nUT4WVqMVMfqPW/mZLvzWm1cgXa256zzZlWn/brgPh93rpbv3r7h56DLr774lNbAux8OGCQt0m8/2K",
	"6W8LfMJgo077RjDryZxhpgbufYOn0RbaakUYuSHHGwBNQ6P8LYDtzLz49YBNsw96r8goFzsWKjtrH8Yf",
	"BY6CEEeqNJmxpW3aFgDVHYXb3oI6hZ/48VwjuLVQtF38T9Bb7Uah6MsbfTuNQP/wIUDI0v4AMUDYJNHn",
	"wIHng81mLNFOrIfG7zgCVWTJsqydEWi+ZdSWYFlUORUK0xNAOAc3/RWn3bIwdYV/gxPQ38NhEMYiAyLV",
	"eDQhXCjNaDt/Luia0FtryPc3uDkp2sqpbqprC9Fe4L2qmz6ENXrWy9Go2mLThErZxhne6q5tPr/P3aT1",
	"dBENBa9hlM/1nqZzcxPz7RK56kr22xoiNJ3XOVbfcrJE2IkEYsEAGSqBRe9Vo8e/zygxu0N3ihlDQT2A",
	"+hrrY96QXbHmWL8cIAddCOJkPNh8BIS9EB++1rvXbfjc/Bpsbk1t1OYhfnluuPH8bMZw64CuacAzkGUb",
	"Anv0wTIk304iu63BSAUGPkDBxm2AowFYQ7tN6M5kU85pExb7CNeGeEF/YepW0OpVT2rRr34rarwmcXcZ",
	"vtaPV/GC3hAn8dURYDfAv0XKZpApCBeyZYtt7JANs3VeoSFRsrZv2trGhuteCrmEULd3746ffztI6GNk",
	"BFvuin4oeTRBL45tQRPaTQh3C9jWh2p/Aa+FW+smXFNbnZHNY3KfOtG24SCJdf3oHt7eR9sTZwdRayuV",
	"0Q/75TPnO+XwLax4nmTjI79Nic5pQ0vbLvVYI6YnMs99H3dwCycQtgwOIlscuDaILH07Ky7IxHZKnIDy",
	"hE7V5ksYxWLbtg0N0y4I12TGS6XH5KlYuUbvEA4btFQKhnFuWCDjle/4dT258lZh6Euj+hqOum0G/tK3",
	"Q9xGHiEp0xSKxS3raXbA7G2sQlaH7/YMvOmruimhINr38FswFn0jdpxegNvOmuMgeCcgdAJyr2GyIR9/",
	"l2DXaVbYA3NdGZscP1cNlb/2E1OSs3zKSiJn/5wwGZTWNyeFp6EWvPAWq193h8eMsWKkgmbnm7hWszv6",
	"98zCmjvZpucQeMsb7d/X5f+zUCgTMvbltwlyGyjTrULAjXHGTZfv0vnbt3Zty5FvN/9V7UbXpD1GAJOl",
	"s3w12nRHwLrlVsCeoKwc4d/r5C980cvHN3f/b4M+peusQ5K41d+q6cSdBEv7xe2Oe+PbiVlzy2+YPzqC",
	"fkfmqq/EsLT6SxUBKqOfjeRstkaU4nPxZjbbyiXy7Z2l7dwLJLXRs/dv0Aa4VWY00FGpIlYX3nTgz2iW",
	"YfSks55oSTLrFnOlQsG8phdsdadkZA5Viezw495bERsuRdwoatsp+pE6Z5qmVNOvYAw1Iijr99p/x2D4",
	"tNILJjQkBri2mQYaXGhnn7b/2TCJgdFawgw2D1kGnIrXFx6FWG2TgaOCb3Brg68NHLBSp734oIpeAVRI",
	"0v/Ftw1Vu0OIS3JjELvsWyVSseo5hF5QGOGbaT8J61xWOrhpG46fKKal1P4F5eF0Zwn1O6Y8lqrbe3P2",
	"XwgTSLzxwOj6hmxkLMUynpg7ZinKqBmj5MAFfJ9c1DlLlsqwcpTJhGZA4GimvjRVu2KN3VQx9w8E66zh",
	"s1Yet3HYN1cq2RrKe8OmoXJh0EClj1z9Il2pXJ+Z6uvPBXaNB/uHX7DHI4JYL2CesNL1cnnOBEfSaUsY",
	"xE3fGNJmWR428USIAvelqxqUZXKJvgV7LHbrJZ8vNBFyaQPqDm+XwThEogLS8tDBhjWY1KWtMw9J+3Np",
	"1u4yRRDhdkRa676jfvzgNDZhE8CUUzjLeGudaERbP7qYIdG+9j0Gg9qV96GflYW4wPQ3F5h3LSuGHasb",
	"/RnDijpnQjU8ag5yXEVXJW0+mR+7Lq512waSz2RGDSOtuhwSvSp4ArF/tsURCMhFKeclU2oIPZBcUwhZ",
	"khnlWVWyjRzF8RHFRNpwrJnjdqNDIXVWss2YsZfT1YiPyqo/rPM1XVnTSSW+yySP13T1F8aKt+gB/oOp",
	"XxhobcWUOkE7kIgDV3jAgMpKkD1yyVjhXON1wDV5U7j6TpC4R7lQhBJ0fYcyp3eqxPzhPYDbkdhBmQtW",
	"1loTV3UU+HpQlpUuKj0qSplWyTpB3hDHN/DyiXv3qxB/qMO1975g812zlYf220LMv1ai88GWic4gzdkU",
	"Xi7mNmv5/s0j1ism5nrh6xH9KWynlvIUG50bKkqJPYKR/QTz1u1KD29+pSd0hc3epSQZLW0TrAf3H96G",
	"W0BVRSFLc1GvWcopOVsV1uMFIEYQopxwOPXp2HX72jDa6sHBk9tpu+dKUiAnBFIhJXZdmhlEtsXvrBtZ",
	"L0qpdcZsibzvSrLAPHBz0LlUmpQswex4X84P9ov8PsgG53A42IvJfFw7NphQWI8PcxRAGre3bL68o0jK",
	"50xBedP2HZNnPjsf4rROfvkRzvnnkxc/EgtKZtAio0LE46TWCTR6UeVTQXmm9oqSXXG2dGSJl1jE0FF3",
	"gtTeiTlwouWVo95VmQ2OBnuDwKjUJlbHzaCkTqssByme/EMSSLe2x89y6syeIIP9vWIlN+BXNwQdtjqJ",
	"jBuVLFVk0Kcnx82miaHJS+Z5JVCchJoh7aWP2w7YyAQWGl77NZGnJ8fD/rbS2P3YbMPgSikzt6LOZOBE",
	"jFSvwfR8Pwvwibq2gD1B38jxvZz6Im3hHLYcwKffPv2fAAAA//+apf3s0xsBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
