// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y923LcOJYo+iuInBPhqpjMlCz5Ula/HLcvVaq2yxpL7jonWhVKJInMhEUCbAJUOtuh",
	"iPmI8ydnT8R+2PO0f6Dmj3ZgLQAESTAvsmWr3NMP1VaSxGVhYd0vHweJzAspmNBqcPRxoJIFyyn886lS",
	"fC5YekbVpfk7ZSopeaG5FIOjxlPCFaFEm39RRbg2f5csYfyKpWS6InrByK+yvGTleDAcFKUsWKk5g1kS",
	"medUpPBvrlkO//i/SjYbHA3+Za9e3J5d2d4z/GBwPRzoVcEGRwNalnRl/n4vp+Zr+7PSJRdz+/tFUXJZ",
	"cr0KXuBCszkr3Rv4a+RzQfP4g/VjKk11tXE7Bn6n+KbZEVWX/QupKp6aBzNZ5lQPjvCHYfvF6+GgZH+v",
	"eMnSwdHf3EsGOHYvfm3BFlpQCkASrmpYn9dvfl45fc8SbRb49IryjE4z9rOcnjKtzXI6mHPKxTxjROFz",
	"ImeEkp/llJjRVARBFpIn+M/mOL8umCBzfsXEkGQ85xrw7IpmPDX/rZgiWprfFCN2kDF5I7IVqZRZI1ly",
	"vSAINJjczO1RsAP8NrKlbEarTHfXdbZgxD7EdRC1kEthF0MqxUqyNGtPmWZlzgXMv+DKgWSMwwdjxqfw",
	"v+xpKTPNCzsRF/VEBh/LGU0YDMpSrs3WcUS7/hnNFBt2gasXrDSLplkml8R82l4ooTNt3lkw8l5OyYIq",
	"MmVMEFVNc641S8fkV1llKeF5ka1IyjKGn2UZYR+4wgGpulRkJksc+r2cDgkVqSEgMi94Zt7henwuakSf",
	"SpkxKmBHVzTrwudkpRdSEPahKJlSXALwp4yYtyuqWWpgJMsUN+jOgcFOmkfn1+XPZthFDTPssZjJ7kJe",
	"M01HKdXUDsTIPfPyvWBpXYzvHL09qMGgfUrP67/MPVouqI5PYihyKs36yTGQZ5opaTAkNRS7yGjCFjID",
	"eLAP2gDFoBKiqRkwp6KiGeGiqDSZcWbOVJEFT1MmyHdTltBKIXhHUozw/Gt80HI+z1hKpHDcwODm940z",
	"raFpZn7FxeWfK61bEIii6gthUFrVGzfz4BLu2anJFMYiU7agV1yW3WMlT1uvLnmWGZTxV+rPGRMpK+8p",
	"HNuC1V8vAuSo3ukQ1jMx65mEBwHjNjHOruGeQpwbk9cA7WwVXLqaXnLYqSBCkkyKOStJIZXi04zhveFC",
	"aUZToKsiPDFc0b0AePcc9TOAMPscn4un5trQvMjgkOxsRMvRlI1KgABLyaykOSMlFXM2JMsFTxbmYN3N",
	"oZWWOdU8gT3MpKEfOIxKmPDfTStNEmoOhcgrVpaITLnbuyWRyrCx+O1v8bkW3jTRJMatLtmqe2OPUyY0",
	"n3FW+itrIT8keaW0WW4l+N8r5B+W1r63/CtKHjI6ZREi9cr8DJOkXBUZXXX4ADmeESE1UQVLzJLsEV6y",
	"lTkXuL1akjkTrKSaEUpKRpWE60Bg0jFKKbKg5TzCQZ+KFWEfdEkJLedVbuQSx6WmxWpsPlTjU5mzE6RP",
	"q+++J+ZQ/dRJyczEsGhLw1YBCGpQ1+e0A+Phec5STjXLVqRkZihCAdIpm3HBzQdDg+YwvZlyCEciK21X",
	"REvNkyqjpYdoDxdR1dQJXetktYh4c2q/9ALCziOc2c+vOFziG4zwV/Mlz4zY1r4TBsXtyraU105rULTE",
	"tmo6Mk8Q4ojyHlGfVWXJhM5WRBoBi7pxAb0DEUuNyeSnp6c/vXh+8fL41YuLk6dnP01QfUh5yRItyxUp",
	"qF6QfyWT88Hev8D/zgcTQovCUB9LCpiocrO/Gc/YhXnfXHdeun/Cz1bUXVC1YOlF/eZvkSvady5dyctC",
	"INh9QBdQrqSKHD93Vwa2HfCPMflFEsGUEUKULqtEVyVT5DuQK9WQpDwxU9GSM/U9oSUjqioKWer21u3i",
	"h0blODwwm84k1YMh4PW2mwxQpyFpOGQcxmRuJx00adXEfjM5IjRb0hWylDGZ1OxycoToAV9byvnuGDUA",
	"AKiVG0vyXcYvDUGzQCM0TUdSfD8mkyWbxoZZsmnNjAHrcironBmihqzGEFLgKXYWx1ffy+mYTFCUmRwR",
	"wa5YCUP/qY3LljSalaJoal4E4IDaa2YXNGvSGndaNUBxpgEQHQuXwXCwZNONZxbHSKc61XiCQhZXRo6g",
	"c1ZauUADRaS5kT3UFlLnJyscMUlZ04hG+BNVi5CsACc1zK9FZxSxHBmYG0kWKEjAXs3IKFzhz2NyZn52",
	"fFKKGsO8RsCEqkrDvqzY7PWW5qTmElYFaApUsx6p1TP57c0HboKtTR8x9bqjmbY4gKWCuLxgTnsWm7iC",
	"wbmI5PCKK+3IIND1fuzrYpqzLNxs42cNdtuz63qK2AYtVTmhevFswZLLt0xZTb5lejBaTXfzHa1r5eQN",
	"vTAI952Q+nvLDKK3AITy+CVDeR0wckkVmjcM5s24SHEWx0eiA6sLnDZqLUG5asH8Qi2/kqUhjuOoZAQc",
	"M7pSGMQvdCYrkUbXpGRVJhvFmuBITvGD9pEi0OyK/LDhnof2wDYc+Usu0vrEt8K/HoSJWIW6+zj62JRW",
	"qFIy4VQj3Te7uWDi6oqWZlMrpVl+kcnEPYddewnH8ucYo3Bm0c5Z2QekZEYHBRmfEoU2OGvMA1r4gSWV",
	"ZpvMtf22UM9agscO/nGaFHwSO7IXZSnL7n5+NOoOTwgzj0nJVCGFYjHDchq5Bj+dnZ0QtH4S84bXH/xA",
	"5Njw8iSrUjQT4YVZZZKmREnEeA9AXG0Dtllml8YF2mm5NHr1MzPZw/1Dz5G8bSWlmk4p6trTSq0M52IE",
	"FuoWZRmbFJpyQSi595bpcjV6OtOsvIevLhgF841ZHhcpT6hmyhroUEPXPEd7gzkKprzyXTJdcpaOyUvQ",
	"1J1cZAfkCiQngybUSOdOmLinLE807yYZZwLMRqkkSubMKMbzhjpq5Dn2AS8WpxmZ0uRSzmbITb1B28my",
	"XWt6zpSi8xjutZALzr1+P4pZV0zol7TMT7cy0ddvvmWGx/khfpbTd4WRCaLakmLaG7eHxGAH2DnIqUwu",
	"mT5+s/f6387OEA1Q/EXBRZmDKIlgS/OjGpJJUbIrLit1gXg78bYp9gHRFIHYFucyptmFPWuWXtAIxzme",
	"WX06Y8DNDCX3X1jBylmAeM6UpnlBDMVHhDK45pDJfKq0LFHWepnRnIlEeiGgecwGZiMzYpSJRYjYu3fH",
	"z52E+DM4Mjb4QGqxqznQLzQPNdjYhy1wb8IOI4t5/03oEfLa1MP9GEKXbFYytbgA+3fkaPwd9uKpvWVq",
	"ATZ1+z0QHLubewqt6bXsC1iH2pAyF9YAXg0N0oFMm1JQgxhNFkA0rnha0Qw9eUuYxRuXtJSGCKzcINai",
	"XpQ0AUtfr2lldyD2+79g6gh6nHnklDOSUaXtKrfGuSVVF3hj0h5HE15Rg+XvjbZvX67viLntWpKJLis2",
	"scqLfVJb70ChBCssT+/VdnTF9NBSZnOT3O3OC73ayvIJF8ABJ3DuWZdd4NRrIl0vbXxFlX5rjb19FM4i",
	"qCxrBDWQr43EPKfzmr866NllxrWCrdybw4FeVPlUUJ5tgVbhVo7NisBRE9MXcC6qLu2//CT9YOIz9myV",
	"xMRtTwAzPmOjxLxE2BUYI6zvwWiWwBXVokJrRCqXYmiEkxL+rIohYTqJEfdtTI1+cbBU1Jpau+61C+In",
	"VF2+kvO+8wfHfybnJFlU4tIyOC0JJcDXtCx4sud4HSmlzEnKkKal+J6VoQzIh/DLleSpGScFGaRFcGJw",
	"yGTEmvDMrMfReG1XOSav6cpLUHmVaV6AWCKYgnfZBx1VXxxCrGVJECIx3NEvX6Oa2cbaY9hGyjgDMG4Q",
	"MwAcHTkDqMFNBQ1D/6+aQRDb8/LtADfchThs5vsaJ/1Uxt+M3LjJN7fFz2LswVM4q3xF2IU/yV5cRK3w",
	"jPYSBXyBnNH5BlTk2qNhjL6hlXAdJP1StmXfYB/ckn1vZrl9trMATNtcWnxz47VdIljXQCyh4sJID7TU",
	"62w/XNkpQfmjlZYj+1Xc/GPhFFUenIyJtnima43WLtdA2w4w/mzSPy5/G5ph7s2FYkzEXK9KO32Yq3C9",
	"5n1nAwkMmNutfTPpWbrVfyrxQTDsSn7iX10gXu3y8TP44i3qfrcrml+xUlmfxBZkrp+6uXGGjbsSu8NN",
	"y4Az3gF1BINjCrbGJYXYDEM3VcZYAcY6cyWpfa8Sl0IuBa4BRLqo4a5jXTBzYgQGBGTaheC01+17r3a0",
	"YHSjJvDnKBysDPvX+gSChc05OAoPxwejx49G8zQ9fJA+PPzBncHR4P+VVenu0ADCekrtD3NwOD4c0axY",
	"0P3gbMKfyXedsb/v7h9WsZPTpbGMj2vxrYnJFgxeo/HetZxRq2UvqpwKI2WqKofPUMYqWcaoYmRa8Sx1",
	"AbLgcDKkgSoyCVc1QRVBAsmuP4GILWuYxK8nc64nxH4F5saob6p14PU9aIDCXx0D0Rg2/IzBtTTL3swG",
	"R39bj3CnzpNmvroeflwjM671rTitkrgviBRen4zK6xiSErODmwfg+HMUaWsS9E9vS7uBEWdnhjD+BOHW",
	"HfoGsfb6N8TjP2cyucy40v2OTWTU1vhGSwZGcIiEZSlJWAlqJGhT6P6URkyzlp7EIedWvqVwPS+ELlcx",
	"t1L3pY6zcn3oOO5nWx3Kvt1DRFsnUA8dRor3kJDn9nrEw2XNr4ROZaUxltXpn1aKdBKmNSfxhnjZ4osL",
	"mlNxkSxYcikrvd4fegovE/dyEIrkFlCyXF6xlNBMijkGjrvYkW0CE5tr6QFN3FLVWfgLIav5IvQuAbug",
	"gROm4CxhRMs5bjHlsxkrwXQMJwi2W/M1oWQhwWSXgdBC3r195Vw6EVvemJxJYG4QtoTRO29fDc1PCdVM",
	"UM3I+eDjlCp2vfdRCi/1qmo24x+Yuj4fxHQX80ETLcssSoXsMA237YY4/dZRwFTBSD1H8Zoq5TD1lGUs",
	"iUfFnHgHJoaRm2dTZin6ezlVzlZfo7BBl0CIAh3F0qyLnH4YHA0O9g8OR/uPRvv3z+4fHt1/cHT/4b/u",
	"Hxzt73eFn+7XnQjPLMOFoKOelSwkuWZhM1lCBIDjqzVval2+HehzFKRM05RqCuw/TSF6k2YnEbNmg/E2",
	"NlNOuS5puSK5Hcwh9Ji8Ntsw1DVjH8K4OuvjzKXZBcSmVIqLOZnQ8XScTAxZr++QDa5tnVFRStjH0eC0",
	"KLlm5GXJ5wttmI1i5ZjlYIgeqNW0ZOL/ntrwDFnO3RtWHj6FF8ip/t//64plgx44nVhj/TOvkzXPPPQw",
	"5fQDz412cn9/fzjIucC/Iu6m1jXwg/Tg/2kQmRQ/LF1WrOfbfs0poSIxx4BpRAXaa4aDGeX4Y0ErVf9j",
	"5KWnwXDw94pV+CGM0XgG/64YKmOVgf7IU6lm7HeNWX6hfXBG33U89AWfBUkENp4AA88+iwAV19KGbll9",
	"56Zl2cs47EPgHD7m0oXveyHTXJhKQbAjMj3zFnIIlpIZz5hCNixYwpSi5SpG0lssL2pAv/fM8dvj5/eC",
	"mAgQ5lwUQps1h3lCY/KUG91I4ErdJzE27ixTVmxw7HxWytxvvU95igH6jKpLdVrlOS1XsQy3vMjA5Ucy",
	"K09ilpOD+pg8Q08ExotY+7uLUjU/uUMC16x5Po4YSa3jeCsxEyzPdsFbRM/1skb1bxXDPYdsjOdGD384",
	"HOQBme8jnNfDAeReXUxXkJ9oGRgEL9fmCGub4qJBQjwdsETjty5TxLV8rOnh/Xg8ySfzo5c800ZFr/nR",
	"0HGXV8d/eVEzl2hKhJzNFGsuNBonUIPq4w7ZiWpLCt63ozAAdpddBafWvhVvma5KgeZikElAjKaOenIr",
	"gMAWdtGe2oEDAVL3I3BfyCeg/rZ3Co0bN7xLEf9swDMxer0cgemwKgbD+pdFpVO5jLM1ayJ4JsWMz6uS",
	"Orm1uUmuXvJS6beV2OAr4ArkfY5KgCGgM/NhHUpm5yNlJYKoE5/eBgIXJTO2JDNqSLEaEhvZL6QYQQ6o",
	"0UuScL3AZIxI6tRsH4g9ZRCtkhfakHTzll6wlRWyxT1Npqw3DAX4CKYKpltpg7AKXVKhZqwkT0+OIU3F",
	"BSKPe4JdgMW+cvGbXfOWZ0nA7ww3MzcN5rIfjzeaPNqztHc3DA84hnr21P5KS+6ChdsIcqGXckkjvO2N",
	"YKMlXZEr+zGGx0OOqFQaIkqlueQ2GxESWDikE5YM8kxzCEkyjHfy0UjG1xOrcvIS8x+dSLKAlB/lfGCu",
	"0IAPiXbeszE5W8rImsBgaidNO6kfXvphdvlFRrXRb0beioMZwCAu2EGmK7/oPkSDjzYbTayxtQa0+3KL",
	"83papZyJZmixtVdZlUOtIw5uGLWO9a0je2306TDG17QoDIzhlN2hELNlSOvTPlmQY8J/ZMOrvzBWvK2E",
	"iJYQqIPjlsHFtW68nK7IJWOFIUrCCYVxESrvzNM90FoR6JHqG76wGHFphfLRpr5QG4m9Drq0eH3sg/1A",
	"Il8wMll6JxybEOttwmSWOqcYr4+ZBOA9l+a/gn3QjbA0dHUPyaQJhAl5/e70zOjME8jPnGwVgdYCpIda",
	"H4xiWO6j649dekRL87WpCOsvVivFLzL8F8/2+GpJGaAJsXQzR7H5BdulUrxlc8O2S5ZaX3wHkjRNS6bU",
	"jsVULP2N3zQ500tasjXXcGfft0tYuvBGa7WbjP1J5VgsA3CgCkuyOEAMBwmm1V7YiCUPhZ7Vx07rlCVV",
	"yfXKZ1O0KOC2YfXr4ulPma6Kp0pxpanQKHzGElFCIU9OjWzndHCQu8woxA/TpdbWtPYCMlXoFrnS/Wk7",
	"X0tQ624hCk8Q5571+i5OMXzIGmOsM4KX5PSnpwcPH+G1V1U+JIr/A3KPpysI+zYCma2oQFyOkUtx6VpN",
	"WmZQmA0cv0h+BnUW/nguUQgdHA0OH073Hzy5nxw8nu4fHh6m92fTBw9nyf7jH57Q+wcJ3X80vZ8+erCf",
	"Hjx89OTxD/vTH/Yfp+zh/oP08f7BE7ZvBuL/YIOj+w8OHoDnGGfL5HzOxTyc6tHh9PFB8uhw+uTBwYNZ",
	"ev9w+uTw8f5s+mh//9GT/R/2k0N6/+Hj+4+T2SFNHzw4eHT4cHr/h8fJI/rDk4f7j5/UUx08vu4aEhxE",
	"TqLU1vwaSI9OEbL8OiyM4MZxpVe8t8V6WtomLqDhVHmlCL3AYUASORYEq7VY771ynhY7FkY1uWA38+Dc",
	"b4ccPz8foLHJqdw+hMDnBFFcBehqE2vHGamsmu9BCY+RoV57WAZjdPx80pMTa1FmS20a1/6SZ+y0YMlG",
	"xRoHHzaPafNtqrl/zK5rnqGVrnUqsbpUN0AP66huIwYozhb0tbdOL6iwftBmLAFVjUHBUWNzmakrTlJf",
	"Y3IWSBefjnxbhJhseST+qLsEzqpg1EldFCmvpVV20QEdjkuKLde+rMdDU0Y9ovfNRusR0cgKm6Q2HDM6",
	"BtCZj11zG2vS6MFG141ZjR1v2C/sNgH8K9eL2i2zFaidEp44/2UU9EMrpg5Jygobtw90xPlEvvGz2Vb2",
	"DI6jx7/TOdXhusi8zniBJaAOO6yKTNIU9TEMJ4qaBXCwt7gaKALk4jpvKniAoNGAXa8scUtCwxcREL4A",
	"e+s//OZ5YZpwnKvhaYGYTUkZfOZYyjA8SmubkM3rzsorI3e85BkLYqIA0Qwnsa+Z31yqSC3XhynaXwoH",
	"6ovp78PtoEU4kb9unxlXAvL9qViDtTebhKPtJcbz35Xnfi5CuJbolSw93aS5tVmJgs9qjkVTIxRbnS6I",
	"2aPWqkrOq/39g0feHmyls0oZzO8YmrW0A0bmQmHK3wMrQN1TTXdHNKcqsPDuYIn1huHr4SALALSjreUL",
	"uEpapx4UvPBbbxhCmmuKYofNmzmtpmvqGJ0yAVZ8n5eIQXMKgrD3VPDtBNM1bV05LW09KUclgzfNw/dy",
	"6vMUyTM3JpbBmjMdPkfVC0y9VF36dGr3dybnCt1agjFbmaPIeMJ1tnLTThnGlYNjxTxaDf1GjBaBGTnu",
	"XTOGFBj78B3UC9TNqWcuh/e9nH4PvNu8bl65pyDDE4zWmudsfC6cj09IjaaR6QoSPkErsXyEalKUUstE",
	"Zq6ukocW+mYQmL44NOQ6TUsJuVBm5GZMRvNyyGIjlYngwhtnK9+2VF9sEFd7yFn++gOrsQCGls1j2COV",
	"qH8wlGG8c9qoLNZV9Fu/9UBM9MuAmKn6r6iE2AeKCHGgmlxykdosia1h4GPFsuxnOYWw7Sz71Tu1bKkG",
	"qi4zOceHYbhs+PoZncfdX42chGgZtdqiFZQC07LGxqYEs02sy6cHCdoHh7//f+S//v33//j9P3//H7//",
	"x3/9++//8/f//P3/D7P7oc5EGPcBs4DWczTYw1DePTXbey+nCs049w8Ox/ASmFEqcXmBcs1hgJMnv/xo",
	"ULRQgyMjVkHlVyPt3B/d38fqiheQusaWylf0hGhhrLjIPmgmbG7PuLCuIbOSC1lpX9qosT6cwq9wL75z",
	"WxqyM14ppV47nq33iYUGL2pOOMi4qD4E1w+81iN7VDYUuhuDCwhDs5sUCwnxZ8NHPnp223L0G4qPhGiy",
	"ab3u1dpsvtUu60jEHoB3IguQTIk5wTJYdfS4/bZV0g8iFBM5F1yxrmRmX64DsCnJ5JKVo4Qq5i2edgq3",
	"KBudco64cD4YkvPBkotULhX+kdJyyQX+WxZMTFVq/mA6GZNTP5XMC6q5LzH/o7ynyKSsBLDQH9+8OZ38",
	"iZSVIBNwzcqMpFxpCBWcEMugqY8cdNWd/SLV+Fw8VU50pRkxOxo29kHOXbjQ+cDZFW2lfDTruNhuqNZY",
	"lJBcQRU5HzQFVTfe+aCGfS6VEUVAIrpkRDOl91I2rea2FqYijCoOVSetIONCStHxzROSygSqDUPWTJY1",
	"dhatwdCX1WJ+uNi+puSQJLLgoW46aVcWHJvRJr6Ycbcq5Zn9q84MMXSfpYRb1zpWdUklU+KeJjnVCeaK",
	"0ERXNPMjdWz6Z1hEGaRO1S5WCXgkszSIyWvW3m8XJPW11129lXNx3FggV0TmyOKGtZkNapCtCqpUq+h2",
	"JzcoCnSbW67pHKVAe/tcbbk6cDfIyT9+7qN6bIEcy/ZR86Sa+MqeU0YMiUmrDK+/WQraGyGyAQPDZBls",
	"zGCXS+UyaOi+8Ctp5tJtJYBZz223uE6EyMVEtHg/lTNXrAQ7qEBonHLKt7P0u1JxQ8LHbOyyN3yETRBh",
	"Nd6tTsfn7MJyGxmYGO17MV1duECnXeKebZxCZK1b5sPtUH4EcnK0rAyebkh+xMA2sfL1B8z/pXUmjg1Z",
	"2q32wNdvUnNbiZ+O9Oxy4tsmi7aro8T644RdcPxl2tAQx9ZQ2pjtCBl30jbDCeoifVKZrLhjwxAasM23",
	"KiQNG8b6LqYEhZA2zlyVWXzid29fhTnP9eyEa8WymXeCyqXIJE23CV6q6yj5U8QEQth/36l8QpqSz0FQ",
	"cqZH7eylmOpZT3iX0o3CW32DfKMwo6SrTldKE9ZNVa3RHZOnZaOKe13DEMTfLvbvWAPqLhHDm+a2b0mR",
	"3Ex9J7WujBs+8/UiIWbfiXLSUmlUxRDzrIUcTJVAseDEoCYsinrYUcdI9v70wOwnC4w1/hOR1rrSeoHP",
	"BZQ9+A7kG+mCtSeO3tqSZEJqwkpqg2J9bYi21G6W9f2mmmXd8PaMC9uAxAbuQhDGPUUS3+UCY9N5mAsO",
	"5Jq8uWLlsuSaoSzPZaWgOpIISli4pNWo+BCraPdKzm2lOk8DsGiek4pdcwyzaDgVmJDRMuM9lcJ1gwTu",
	"QCWiyFUHgkb1gZJBREvCQCcE5Z0LDOjHcSJxAutiSD+NCqy5ZG7S2CWq97hdCRQbb+pT7jo5FsVFsMeW",
	"ZHBC7LNO2au1vpztDCr9Y316TKymsUZDZxQpheP7dRkyaP2Ss3yKeLqVSN8o/dZdAGpX2wygLrcjucFR",
	"NbxSQSmdaDju9W/DSD5+lx06aluj2attipN0L82uylEbR9c7l93o/bcDQ8MDZ0NtLLdmbPvLyBdCixhg",
	"FUtKBpxSjoTUI82ybETFSgoWBkEfDQ7HB32wP/qbi7U1ktssL9jc9gUa1Y1hBsNBzlUSSSK9YZS6XfjH",
	"z3+z2vIZztT0kcamsMjcf2SnfC7etA+rUU3QGvXtAT49OYZGL8FJXNTlu9SSzuesHFX8lg6mVeewmxvR",
	"X/irs9rbPyZHSOIn01nRmlPKGCtOre0r4tY2j71tzEU2oBrpkuRODczAu8tEihmcXr5xRal8xnlKV009",
	"zY9tCDYoSmPytCgyzmwBSEyxl+ZDDnarSUpX6kLOLpaMXU4gUhDeaf5uXnaFriMrBJlQkIMHo4WsSvLT",
	"T0evX9cJyNhhqUbbcOTB0SCXRFcEQjDAw5hegNR9NLj/w9H+Pua7WKXPZkMDXrm39p9Ei640J+mGU9KE",
	"jRQraImBvks5yhj0tHLFdyzUoeIzXSFfZOyyB8zku/NBLtHjoCvnbPh+TF6AtTNnVChyPmBXrFyZ8VyJ",
	"nW7rJb//QHQCgPYkLTnQfIxXdfeA2jxcm8f6sYdNaDbGDVa85l5oqlmfTm1z0cswM2/7DKGoRhwMttWi",
	"0r5qjnRJL29cznGLhW5YXtPy4etTDu26gpqW0MvEHClT9hU5mxllBIwD7SKaNQL1VwuNFAbAsndItmrF",
	"0+ZH1tHEUKHX1qaO2AbURUb/sVofsdRMvbT+CdTmwn6TQK5qDwtKK7UGaBVeRWZccLXoa1A6/IznOfT7",
	"W3OyfdaYP1PFkzWC5/gT6gkvd6knvIsR/auU7v1cyYWfrbDuNuVIffGelmZV+nTcG9iZtq+XW+tjMcUv",
	"VFjIU3RWUuFNQdnKhmCunLRB54TrwHEPBV3AtjH2rkFrJi6MwCBndT1/o34Sxc3fVDAwvnSlhI5G1ij2",
	"aIZOJfnx5B3BmA9v5Xnx4q8vXozrArc/nrwbwW8RIaHZTHHnupyazsfkmW2ObL2ZrepI1JbuR8O9zdag",
	"4GYvqUhlTmBAbyJSis+Fo1SfyXayQbc4o/MtSX9N7T0SqI6dwO7AIELzRDWdX/AUdIsHh/cP0kc/JCNG",
	"H6WjBw8fPRo9mc4ejdiT2f6TKXvwQ8KmEbXCjxCI+pvbkKwT/d2Ia6Hj1PzOYnZV4aPGkOs1U6ORZDtL",
	"VrN01MebOqTiLVciRpIzdIP70w7Y1DVq2ZDRbNShPLR7XNAqllv0TrESak/Y6ruWZRw/H5KCKrWUZerr",
	"MYNabUuMGP3H2S9rs4ZBPQAMcDbDV+udLrQuBtfX0OERHX7QcCTRgQHE0+ozRnPrqsIv1dHe3sxFGgYR",
	"gnvdAhsY90he0jK3obQQdj0YDjKeMJsJ4qnUq6vDzkTL5XI8FxWMb79Re/MiGx2O98dMjBc6xxKFXGeN",
	"Zee+oHet9d8f749BU5IFE7TgYJoxP2EuExzRHi343tXhXtIuTTRHi4mvZXGcQpM/3axhBMImpJHAaAf7",
	"+w68TMD31CijGEW+99660hCBtwyib84Hp9gEujDonfl0FsRFJ3GZFWMYTTPLfdbphYq3+28Q/QeUqB7j",
	"hUgLyW0t8bnt998ZsFMP2kA+Ct49iOnZc/aWPmC/5CL9s09MP8Hss1sDd7wTZwTeL2Ul6jx10JN979Pr",
	"uhnm51oXFkiIrOPU9zNcGtF/WUoxH7dO/yW3UfOyJLksGXn26th110SvDQTAKbKkEDoHwpTbTgwpCqki",
	"JwVJzJGjAib6Z5muPhs0WsVYImBxfUVlaZ1+EIKEBUgkRpNh+Zzbx6NGcYfuSn9pXtwhLhLj3eBIZ1yw",
	"u4dTf6UZB88rDbHpJsjUwlPrvr2qx3dt1uuD3EhUMNVpFEQEr0HZRurWV8Xaky+Gn/8UiIkZbjVGNhPg",
	"NrC7HcbpRUZMb9hSiniJGeCfdOQ7lEO+HjbGWtE8a47VFpA3IUj7IN5C594rFhc8unLC2tN4miRMKd/R",
	"N1KRMTIkCdPBcGP3wLn/pmDi6cmxS3bLMrm0TUsg5FzQbM9KkvZAJ6SgyaU57HPRf9yK6aoYUVcjqJ/s",
	"nNIrFi1LdDuEJzpVlGmGYDW0m14hereQ8kGkj1QLGSAUfcmmtCictSQ1utKsyrK6O6y21cqMXHn3SMm7",
	"OraoJz0WqxZZ8xO0zhGwwxWZVSLBmwjl3Tegt0GIGGb3Vp/qx8EG59v76DJWr/c+Om/s9TqS1GCGzTbo",
	"RhPnBna2BIRV4YKc2FqDth6rXVScbp6wUecjEwZe5f4J29Trt1tkpvHc790pptPSWonaWSNnPOzt1MgW",
	"N19a24BLFjfI6TPF0Qmwo363bjmN+uS9CeT9qOqzoXbH0rpK6H9j6A02oD4BOevqAm3zAXmn6qRpJ7TT",
	"NB0hM1mTDodk1BcYZVNM/ZpRaBRjGEcsi4RMqaorQE1LuVSNvLCbY3y9x91x3NXojhszmE4WNoX41g67",
	"XUa8/6z/bt4KJHzruMBUJUjxg7wxVjLbZQpKo39ZRg0PiCvw2MRJCDmjrouMDdN2aUghy8U6572WC0y+",
	"xnZjtyKANRrOdff4s5zaTPSc6w7RuL5dXOlbEHgtKyN3o0Rjk/iMAG2jj4OG/IgUD+4f3D5CnHk+57MV",
	"maZzSGoESb/Oamy+EM1p5NjnPFuRtPJ152yzqoQmC0cS/FBApaQkmREYz8WduQuIY9bxBtVAZdmhXFix",
	"A/Ido9ejHu7nZoqnoc+GIECJe0s2O2QPjS9r1B53zcDy8HXvWhIsYd1VexAvxrDj5fCJuQaO2G1lYUT+",
	"X96cYSKsbajYImFDoheymi/++3L9US4XoNWGqwXY7/dtRgJjJxTKWXJz4rp2pPPINWt0v1sva/yYySlt",
	"VCOBbL/b5SjxXoFbiZzD+JU7c10VXeY63B4qVtFOgD2SK/QPhMRvVl7ZLrWRz9WG43sDtaGxB1KdMDYH",
	"QPcsp3V+OVVqhI3rcKvuX80DhB5/zDb8uyVq2dtOMGqdbjYUbFb0x0Z+0jbkG9+YtCpsBBgS15xC6rG5",
	"Ka6BraWIj74IRSwZrsnKv4hENSG053J3xOLXtLzElYYgG9b6kutdk5Rcs5LTDRgP4+Xmtu00KPIAJy3U",
	"uXFYa8IwBUAVRwlt7TEoV2dO3PyeNw+9S3Jh0KKUaB1eMP+uVwemNLmcl7IS6fhc/CJhPop3dtJuUTkh",
	"3pgAEWrmK5aSqgC5SWheQhSGFKmr4JJTRE/0q3bAg1WSV7Ii7EPBEj20ChUvyaTuLDapaw4oW2HZqNEZ",
	"7olC816YtWV9BmJi+ObeR/PfX2jO1lpNbBWRrWwmbsA7Y8Jo10Lple3wWZsB2HwDL2kYQQx6vXhIbLgE",
	"QT58s5cyll6Jnova4jRu1RTQBlrU8ONf8rtREQC6ij/+HZRlAZe3BmI9lb/JfrwuCD9iFNb1VkxyK6z2",
	"Ofj9OL0pTuy3bfjYc2QDgWnFUwRf+0aXfD43YsKXZRzvBJIilhKInu+67TDoMSBhKHsNbX9/lEqVVWOg",
	"jZaRw+Qca/mirmPrCflBDJ10gewdukx+kb5/heq01f5uxfT3TVuex6y1RravhxFfxD7DUahuBFCYnbcl",
	"U9cGfL2ujx+JlAR5bn33cW/abFEfv5lvoY1po6H9lzyQW5GV663EJMWqMPj7HcZlDusG/N8b8SHo0+7d",
	"eh6OWzpZ3d2kScIKKCHFhC45s9YEICt2krtGVKBZr1utLfdt7nwAgl3v99fBq9u76GuRC5TYNQhmZNq5",
	"1AjPoE4T3P67hApIo0D3biaM15Xb3R4ATVIJcaZWufBbVs0drpc6MHjEo5r3XDngxKncDmaWttEDbSzf",
	"AlL+wW05zaO+gV0nOmijz3c/Aimmw5I+PUZx0ARO6ro5f3AW6XZi8157bMyCLYmDzQ1tRW4in5tDlWeM",
	"aB46OOgrWeV6WroluCAx/N6HmH5lorkGWb0kUG/BgqEZCrIRQesMwnXoeerrO/2xkbNR5qwHNZtJuBC4",
	"YO17N0LT08ZwN0HS5oIspoLLwB+2y/xVvj+Gl/z/IGjc3OQuSAx66Eb2fAZvfRs8Gfbic97isiLCmDMV",
	"lhtTHcnnjomF1K4biqTRLAtX3cCGbeS9+I7jSLRcUD1ayipLrWNmlMpenPI2p18XVP9qPjrWz78Vgc+5",
	"gvrkPGxFYM06ERuEQb5AhsIOgS5b2tl0IFkYRwEXsKu87NzkWG9zCHamTM5tgFivPAYmI9vQpJ6lHg4N",
	"S1DjT3i/Q0oSKVy4fLZyU3AVdK62AVGuojs2HUTBU1a6xyj1eWAR4io2mNlzveb2sEjsGqbdbNF6S4EW",
	"zUliMdZhQzbnHCe2X+WXi3GKttiMhb+7NpPQndr2wgz8kMiv95/cPrH0K6FZyWi6sgW3rcDw4Is6PfH0",
	"IA5IzCHGk0xUC6J117ZJcE0Q5XmyIFKwLxw1WLXYTYtIPcMOuLRuRIrXX63yjItL79aFZsQIAQzs0UhU",
	"LFAqG35YW9+wzRpSC9t/ytZBT2iW+Qteh1DV9AOB2k4MsAuiRIWXCRbTaIxMS0bX0oywt962lCM82Vul",
	"IrH+jtsSlK9AS6LtDWPrrab22KD/hQRxPjyIYVhvy7xj+wFaV8qdujLQPrPuPRzCwDZlxVyYQpZa2Ytf",
	"M167sY0I/xSTsagLE/Nsoz2g7+DmQs+wDSSuoiY78K7SRkDwS+jeEhh276NrEXq99xF+4f9Y41APuwXK",
	"krmYxpYMuHXzVygw2hUY3as7+eGHnXmDkuqub6Kvph6Z1e1+m1nrXsC/3frF63SI3NIQeacuUVjqq+5k",
	"Ge1p2hAwg/uyjnh7jPznRsZhzKhiiYorLWl9DrazfMpmrCS+UarrR5PZZMbzwcH+D+cDj1h1QBMoFeDf",
	"01UpnEhfb095OQ7j2Xxn2s6BYwgUzZTEMZTMmRSMsEzBOHWN79gyAVsAgAtGMdvegvD/GeE0o2dUjJ6b",
	"fY7ewQCDCAyDPpgxGMqSz7mgGcxpxof2NlhEPJNh0XHfwZfroKeT7cDLQ6ptlTxXJ0oQyuENaN00B8Hz",
	"9bvTM8I4lHabMvL09NnxMZR3EImEIC0jn5K3L5+Rg/0Hj8l39JKS18evX+ALXMy/H5NjYXVIKHmZuBLt",
	"7g2cY8rIu7OXox+2AecbC4vRSwuLwcbwqG1EKJlopkdKl4zmTaLkjQNTLgxJGW5O036Gc6hWp/EbmDKd",
	"5Nu1Yh7s/7DpdXsDGrhvqRzGcj6OjlDaz40GgiGXU6aXzN4vC84gAMkbCmwEysx3Spdlh9R5ad1dH9Cv",
	"HkaaAyHdcInM6wmFu/T1ZbW47uIU5YxMmfnQzz9dNa46CjGT3lt7RMyZTWxhQSBojUjULxw5v4HpATOy",
	"sfP9rI40YzMbD4EkzGSZ8Gm2Ikkm7cX96ezshCRSCAxadj2LJBAJS+ttEUzVOC9G2AeaaKJozqzwqqXr",
	"b0ZSWRm5Ej9Q0FYW38LEP7xNdQnAyAmQqUxXvdw7zDA3U9QKTRcsDWHV+2r6Ygpf0jI/rbuj3JIsVs/y",
	"FqT9m9ejCv0VXNVBgTNa5htS5nHqziisPUgAPzAI7320LXmu1/sMoArdVpGyvsPP3bTp2k4CUV8XVooV",
	"M3lHnQHNXlNrLK2RL9ac/J5tZLL+9F1rrG8FCdx+1uECNLty+NATg9YWcuHDBVVEQH8XsmL6bqFTGDTS",
	"6SsGZj+ZM4zgx71v8FnaujatSBE35HgD4mlotrwF8p2ZF+8O8mn2Qe8VGeVixzpBZ23gfCt4FYSyUaXJ",
	"jC1tI6QAybBJ/VbUK/zEj+eaK63Fqu3iOIJeSV8Uqz6/0bjTse6bD+VAFvgNxHJgIzKfOwWeEzabsUQ7",
	"tQCaC+MIVJEly7J2Jpn5llFbt2NR5VQoDFsH4R68/lecdmuJ1BW6zR2Bev3uRmEMKlys+l5NCBdKM9rO",
	"uwqqnvcWqPH1yW9PCrdyrpvqxkK4F5gbfcfrwi7r5XBUjZXvo40N4JzVXts0cJ/zR+vpIhoOHsMon+s9",
	"TefmJObbJQDVhaa3NWRoOq9zce5y0HzYSQAqr8NlqATWoFaNLtI+s8DsDt0xZgwFaeT1MdZg3hBlvwas",
	"nw+RgyLhcTIebD6Cwl7oD1/r3es2fG/+GdheUUVgigXlmkD9/NxxIzxt5mkLYDc0CBpMs004/XXCahZ3",
	"JyHaFvKjAgMpoOrfNsjSQLSh3SZ0X7Gpy7SJm32EbEN4oj8w9UWu2aueFJO6P74ar0kAXYav9d+zeL1d",
	"iLv46hdgN8T/gpTOXKYg+gjtyS4UCXqPKO9lGhIla3tpQrPMGkovhVxC5Ny7d8fP784l9DE3gi13vX4o",
	"iTRRL37bgiaTmy7cF7htfVftL+AFcWvddNfUVjCy+SvuUyfqNhwusaL8XeDtfbQtK3YQvbZSKf2wt5+B",
	"3alebXHH8ygbfnk3JT6nLS1te8RjjTc/kXnueymD2zmBKGlwQNmKs7UBZem703BBJrYz2gSUK3TaNl/C",
	"KBnblmlomHhBuCYzXio9Jk/FCi0y+FrYASUYxrl5gaxXvvXYzeTOr4pTn5sUrOG422ZyL307tG3kFZIy",
	"Dd3//RE7u+52N38bq5LV+bs9wr700d2WEBHte3YXjE13xA7Ui4DbWYMcRu+ElE6g7jV0NuTpbwINO73K",
	"enCwK6OT4+eqYUKo/dautTmRs39OHA3quxtIITTUghfeAvbr7viZMVaMVNAMeROXa3ZP/pZYXnNn27QY",
	"AW9+o130ujxyFgp1Qsa+vJsouIFyfVWMuDVOugkZXFp4+xRvbJny7aq/ql3qhrTJCHCydJa1RpvfCJq3",
	"3BjYEpCVI/x7nfyGL3p5+/bO/23QpnCd9UkSt/ovappxkGBpv7jecafcnRg7t/yGeaWjKHRktPpIDMur",
	"v1QRpDL63kjOZmtELz4Xb2azrVwwdw+WtnEnkNhGy86/QRfQVjnMQOelitRdx9cC/BnNMoz2dNYZLUlm",
	"3XCupCWY7/SCre6VjMyh+o0dftx7KmLDoYhbvdp2iv5LnTNNU6rpVzC2hj34/xBXems0fFrpBRMaEhlc",
	"1zyDDS4Utc9a8Mk4iYHcWsIMNm1aBpyK1wcexVhtc5ejgnFwaoOvjRywUqfd+CCOXoFUSNL/xd3Gqt0x",
	"xCXluV77rMREF7HqAUIvKozwzbSfhHUOKx3cts3HTxTTWmr/hfJ4urOE+gemPJaq23Nz9mQIS0i8cUER",
	"mhiykbEUy0lirpulKKNmTJRDF/CtclHnWFkqw8pRJhOaAYGjmfrcVO2KNXZTxdxLEBy0hs9aedzGjd9e",
	"SV9reO8N64YKeUGbjz5y9Yt0JVx9Jq2vaxbYPR7sH37GRoSIYr2IecJK13HkORMcSactuRA3nWMInWV5",
	"NNH8Ci2xDNyjrqxXlskl+iosWOzWSz5faCLk0gbwHX5ZBuMuEhWQRogOPCOFw+owGRCKDMwldJq3mS14",
	"4Xa8tNY9SP34ATQ23SbAKadwlvEGMNEIuv7rYoZE+9u3EIxqd9J3Ha1sxAUu0QUG3siqYcfqRp/Gbkmd",
	"46EaHjuHSa6SqJI2H86PXVfD+9IGk09kTg2jrrocEr0qeAKxh7YzDwjMRSnnJVNqCK17XDMDWZIZ5VlV",
	"so0cxvEVxUTacNQZcLvRoeA3K9nmm7KX09WIj8qqP6z0NV1ZU0olvomklNd09RfGirfocf7G1DMM/LZi",
	"TJ1wHkjMges9YFBlJcgeuWSscK74OgCcvClcuSpIRKRcKEIJutpDmdQ7ZWL+9x5E7kj0oOwFK2utias6",
	"Kn09astKF5UeFaVMq2SdoG+I5Rt4+cS9eyeYA5QZ23tfsPmu2dhD+20h5l8rkftgy0RukP5sijIXc5uV",
	"ff/2L9orJuZ64est/SnsEpbyFLt3GypLiQXByH6Cefl2pYe3v9ITuoJ8XWhRRkvb2+nB/Ydfwo2gqqKQ",
	"pTmo1yzllJytCusxAxQjiFFOmJz6dPO6J2sY/fXg4MmX6SbnSm4gpwTSISV2E5qZi21r+1m3tF6UUuuM",
	"2QqAfyjJA/PcDaBzqTQpWYLZ/75aIewX5YEg250DcLDHkPm4doQwobDcIOZQgPRuT9l8eU+RlM+ZgnrF",
	"7TMmz3z1AYgTO/nlR4DzzycvfiQWlcygRUaFiMdprRN49KLKp4LyTO0VJbvibOnIEi+xRqOj9gSpvxOD",
	"AKLllaPmVZkNjgZ7g8AI1SZWx80gqE4LKIcpnh1Akkq3dsnPcurMpCCj/b1iJTfoV7e5HLY6YIwbhTtV",
	"ZNCnJ8fNXoChiUzmeSVQ3ISaKO2lj9sO3MgEFhte+zWRpyfHw/5eydjS12zD3JVSZm5FncnA6RipzoPl",
	"B/wswCfq2gkWgr4/4Xs59UXowjlsuYPr367/TwAAAP//+vOjA8URAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
