/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssignedWorker model module.
 * @module model/AssignedWorker
 * @version 0.0.0
 */
class AssignedWorker {
    /**
     * Constructs a new <code>AssignedWorker</code>.
     * @alias module:model/AssignedWorker
     * @param name {String} 
     * @param uuid {String} 
     */
    constructor(name, uuid) { 
        
        AssignedWorker.initialize(this, name, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, uuid) { 
        obj['name'] = name;
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>AssignedWorker</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssignedWorker} obj Optional instance to populate.
     * @return {module:model/AssignedWorker} The populated <code>AssignedWorker</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssignedWorker();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
AssignedWorker.prototype['name'] = undefined;

/**
 * @member {String} uuid
 */
AssignedWorker.prototype['uuid'] = undefined;






export default AssignedWorker;

