/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventTaskLogUpdate model module.
 * @module model/EventTaskLogUpdate
 * @version 0.0.0
 */
class EventTaskLogUpdate {
    /**
     * Constructs a new <code>EventTaskLogUpdate</code>.
     * Task log chunk, sent to a MQTT topic/SocketIO room dedicated to a single task, to avoid sending too many updates. 
     * @alias module:model/EventTaskLogUpdate
     * @param taskId {String} UUID of the Task
     * @param log {String} Chunk of the task log. May contain multiple lines of text.
     */
    constructor(taskId, log) { 
        
        EventTaskLogUpdate.initialize(this, taskId, log);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, taskId, log) { 
        obj['task_id'] = taskId;
        obj['log'] = log;
    }

    /**
     * Constructs a <code>EventTaskLogUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventTaskLogUpdate} obj Optional instance to populate.
     * @return {module:model/EventTaskLogUpdate} The populated <code>EventTaskLogUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventTaskLogUpdate();

            if (data.hasOwnProperty('task_id')) {
                obj['task_id'] = ApiClient.convertToType(data['task_id'], 'String');
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ApiClient.convertToType(data['log'], 'String');
            }
        }
        return obj;
    }


}

/**
 * UUID of the Task
 * @member {String} task_id
 */
EventTaskLogUpdate.prototype['task_id'] = undefined;

/**
 * Chunk of the task log. May contain multiple lines of text.
 * @member {String} log
 */
EventTaskLogUpdate.prototype['log'] = undefined;






export default EventTaskLogUpdate;

