/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobLastRenderedImageInfo from './JobLastRenderedImageInfo';

/**
 * The EventLastRenderedUpdate model module.
 * @module model/EventLastRenderedUpdate
 * @version 0.0.0
 */
class EventLastRenderedUpdate {
    /**
     * Constructs a new <code>EventLastRenderedUpdate</code>.
     * Indicator that the last-rendered image of this job was updated.
     * @alias module:model/EventLastRenderedUpdate
     * @param jobId {String} 
     * @param thumbnail {module:model/JobLastRenderedImageInfo} 
     */
    constructor(jobId, thumbnail) { 
        
        EventLastRenderedUpdate.initialize(this, jobId, thumbnail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobId, thumbnail) { 
        obj['job_id'] = jobId;
        obj['thumbnail'] = thumbnail;
    }

    /**
     * Constructs a <code>EventLastRenderedUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventLastRenderedUpdate} obj Optional instance to populate.
     * @return {module:model/EventLastRenderedUpdate} The populated <code>EventLastRenderedUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventLastRenderedUpdate();

            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'String');
            }
            if (data.hasOwnProperty('thumbnail')) {
                obj['thumbnail'] = JobLastRenderedImageInfo.constructFromObject(data['thumbnail']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} job_id
 */
EventLastRenderedUpdate.prototype['job_id'] = undefined;

/**
 * @member {module:model/JobLastRenderedImageInfo} thumbnail
 */
EventLastRenderedUpdate.prototype['thumbnail'] = undefined;






export default EventLastRenderedUpdate;

