/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FarmStatus.
* @enum {}
* @readonly
*/
export default class FarmStatus {
    
        /**
         * value: "active"
         * @const
         */
        "active" = "active";

    
        /**
         * value: "idle"
         * @const
         */
        "idle" = "idle";

    
        /**
         * value: "waiting"
         * @const
         */
        "waiting" = "waiting";

    
        /**
         * value: "asleep"
         * @const
         */
        "asleep" = "asleep";

    
        /**
         * value: "inoperative"
         * @const
         */
        "inoperative" = "inoperative";

    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "starting"
         * @const
         */
        "starting" = "starting";

    

    /**
    * Returns a <code>FarmStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/FarmStatus} The enum <code>FarmStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

