/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobTagChange model module.
 * @module model/JobTagChange
 * @version 0.0.0
 */
class JobTagChange {
    /**
     * Constructs a new <code>JobTagChange</code>.
     * New tag to assign to a job. Can be empty to remove the tag (and thus make the job available to all workers).
     * @alias module:model/JobTagChange
     */
    constructor() { 
        
        JobTagChange.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobTagChange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobTagChange} obj Optional instance to populate.
     * @return {module:model/JobTagChange} The populated <code>JobTagChange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobTagChange();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * UUID of the tag. If this is given, 'name' should not be given.
 * @member {String} id
 */
JobTagChange.prototype['id'] = undefined;

/**
 * Name of the tag. If this is given, 'id' should not be given.
 * @member {String} name
 */
JobTagChange.prototype['name'] = undefined;






export default JobTagChange;

