/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LifeCycleEventType.
* @enum {}
* @readonly
*/
export default class LifeCycleEventType {
    
        /**
         * value: "manager-startup"
         * @const
         */
        "startup" = "manager-startup";

    
        /**
         * value: "manager-shutdown"
         * @const
         */
        "shutdown" = "manager-shutdown";

    

    /**
    * Returns a <code>LifeCycleEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LifeCycleEventType} The enum <code>LifeCycleEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

