/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskStatus from './TaskStatus';
import TaskWorker from './TaskWorker';

/**
 * The TaskSummary model module.
 * @module model/TaskSummary
 * @version 0.0.0
 */
class TaskSummary {
    /**
     * Constructs a new <code>TaskSummary</code>.
     * Just enough information about the task to show in the job&#39;s task list.
     * @alias module:model/TaskSummary
     * @param id {String} 
     * @param name {String} 
     * @param status {module:model/TaskStatus} 
     * @param indexInJob {Number} 
     * @param priority {Number} 
     * @param taskType {String} 
     * @param updated {Date} 
     * @param stepsCompleted {Number} 
     * @param stepsTotal {Number} 
     */
    constructor(id, name, status, indexInJob, priority, taskType, updated, stepsCompleted, stepsTotal) { 
        
        TaskSummary.initialize(this, id, name, status, indexInJob, priority, taskType, updated, stepsCompleted, stepsTotal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, status, indexInJob, priority, taskType, updated, stepsCompleted, stepsTotal) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['status'] = status;
        obj['index_in_job'] = indexInJob;
        obj['priority'] = priority;
        obj['task_type'] = taskType;
        obj['updated'] = updated;
        obj['steps_completed'] = stepsCompleted;
        obj['steps_total'] = stepsTotal;
    }

    /**
     * Constructs a <code>TaskSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskSummary} obj Optional instance to populate.
     * @return {module:model/TaskSummary} The populated <code>TaskSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TaskStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('index_in_job')) {
                obj['index_in_job'] = ApiClient.convertToType(data['index_in_job'], 'Number');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('task_type')) {
                obj['task_type'] = ApiClient.convertToType(data['task_type'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('worker')) {
                obj['worker'] = TaskWorker.constructFromObject(data['worker']);
            }
            if (data.hasOwnProperty('steps_completed')) {
                obj['steps_completed'] = ApiClient.convertToType(data['steps_completed'], 'Number');
            }
            if (data.hasOwnProperty('steps_total')) {
                obj['steps_total'] = ApiClient.convertToType(data['steps_total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
TaskSummary.prototype['id'] = undefined;

/**
 * @member {String} name
 */
TaskSummary.prototype['name'] = undefined;

/**
 * @member {module:model/TaskStatus} status
 */
TaskSummary.prototype['status'] = undefined;

/**
 * @member {Number} index_in_job
 */
TaskSummary.prototype['index_in_job'] = undefined;

/**
 * @member {Number} priority
 */
TaskSummary.prototype['priority'] = undefined;

/**
 * @member {String} task_type
 */
TaskSummary.prototype['task_type'] = undefined;

/**
 * @member {Date} updated
 */
TaskSummary.prototype['updated'] = undefined;

/**
 * @member {module:model/TaskWorker} worker
 */
TaskSummary.prototype['worker'] = undefined;

/**
 * @member {Number} steps_completed
 */
TaskSummary.prototype['steps_completed'] = undefined;

/**
 * @member {Number} steps_total
 */
TaskSummary.prototype['steps_total'] = undefined;






export default TaskSummary;

