// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/manager/task_state_machine (interfaces: PersistenceService,ChangeBroadcaster,LogStorage)
//
// Generated by this command:
//
//	mockgen -destination mocks/interfaces_mock.gen.go -package mocks projects.blender.org/studio/flamenco/internal/manager/task_state_machine PersistenceService,ChangeBroadcaster,LogStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	zerolog "github.com/rs/zerolog"
	gomock "go.uber.org/mock/gomock"
	persistence "projects.blender.org/studio/flamenco/internal/manager/persistence"
	api "projects.blender.org/studio/flamenco/pkg/api"
)

// MockPersistenceService is a mock of PersistenceService interface.
type MockPersistenceService struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceServiceMockRecorder
	isgomock struct{}
}

// MockPersistenceServiceMockRecorder is the mock recorder for MockPersistenceService.
type MockPersistenceServiceMockRecorder struct {
	mock *MockPersistenceService
}

// NewMockPersistenceService creates a new mock instance.
func NewMockPersistenceService(ctrl *gomock.Controller) *MockPersistenceService {
	mock := &MockPersistenceService{ctrl: ctrl}
	mock.recorder = &MockPersistenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistenceService) EXPECT() *MockPersistenceServiceMockRecorder {
	return m.recorder
}

// CountTasksOfJobInStatus mocks base method.
func (m *MockPersistenceService) CountTasksOfJobInStatus(ctx context.Context, job *persistence.Job, taskStatuses ...api.TaskStatus) (int, int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, job}
	for _, a := range taskStatuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountTasksOfJobInStatus", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountTasksOfJobInStatus indicates an expected call of CountTasksOfJobInStatus.
func (mr *MockPersistenceServiceMockRecorder) CountTasksOfJobInStatus(ctx, job any, taskStatuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, job}, taskStatuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTasksOfJobInStatus", reflect.TypeOf((*MockPersistenceService)(nil).CountTasksOfJobInStatus), varargs...)
}

// FetchJob mocks base method.
func (m *MockPersistenceService) FetchJob(ctx context.Context, jobUUID string) (*persistence.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJob", ctx, jobUUID)
	ret0, _ := ret[0].(*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJob indicates an expected call of FetchJob.
func (mr *MockPersistenceServiceMockRecorder) FetchJob(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJob", reflect.TypeOf((*MockPersistenceService)(nil).FetchJob), ctx, jobUUID)
}

// FetchJobByID mocks base method.
func (m *MockPersistenceService) FetchJobByID(ctx context.Context, jobID int64) (*persistence.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJobByID", ctx, jobID)
	ret0, _ := ret[0].(*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobByID indicates an expected call of FetchJobByID.
func (mr *MockPersistenceServiceMockRecorder) FetchJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobByID", reflect.TypeOf((*MockPersistenceService)(nil).FetchJobByID), ctx, jobID)
}

// FetchJobsInStatus mocks base method.
func (m *MockPersistenceService) FetchJobsInStatus(ctx context.Context, jobStatuses ...api.JobStatus) ([]*persistence.Job, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range jobStatuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobsInStatus", varargs...)
	ret0, _ := ret[0].([]*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobsInStatus indicates an expected call of FetchJobsInStatus.
func (mr *MockPersistenceServiceMockRecorder) FetchJobsInStatus(ctx any, jobStatuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, jobStatuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobsInStatus", reflect.TypeOf((*MockPersistenceService)(nil).FetchJobsInStatus), varargs...)
}

// FetchTasksOfWorkerInStatus mocks base method.
func (m *MockPersistenceService) FetchTasksOfWorkerInStatus(arg0 context.Context, arg1 *persistence.Worker, arg2 api.TaskStatus) ([]persistence.TaskJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTasksOfWorkerInStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].([]persistence.TaskJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTasksOfWorkerInStatus indicates an expected call of FetchTasksOfWorkerInStatus.
func (mr *MockPersistenceServiceMockRecorder) FetchTasksOfWorkerInStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTasksOfWorkerInStatus", reflect.TypeOf((*MockPersistenceService)(nil).FetchTasksOfWorkerInStatus), arg0, arg1, arg2)
}

// FetchTasksOfWorkerInStatusOfJob mocks base method.
func (m *MockPersistenceService) FetchTasksOfWorkerInStatusOfJob(ctx context.Context, worker *persistence.Worker, status api.TaskStatus, jobUUID string) ([]*persistence.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTasksOfWorkerInStatusOfJob", ctx, worker, status, jobUUID)
	ret0, _ := ret[0].([]*persistence.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTasksOfWorkerInStatusOfJob indicates an expected call of FetchTasksOfWorkerInStatusOfJob.
func (mr *MockPersistenceServiceMockRecorder) FetchTasksOfWorkerInStatusOfJob(ctx, worker, status, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTasksOfWorkerInStatusOfJob", reflect.TypeOf((*MockPersistenceService)(nil).FetchTasksOfWorkerInStatusOfJob), ctx, worker, status, jobUUID)
}

// FetchWorkerByID mocks base method.
func (m *MockPersistenceService) FetchWorkerByID(ctx context.Context, workerID int64) (*persistence.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerByID", ctx, workerID)
	ret0, _ := ret[0].(*persistence.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerByID indicates an expected call of FetchWorkerByID.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerByID(ctx, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerByID", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerByID), ctx, workerID)
}

// JobHasTasksInStatus mocks base method.
func (m *MockPersistenceService) JobHasTasksInStatus(ctx context.Context, job *persistence.Job, taskStatus api.TaskStatus) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobHasTasksInStatus", ctx, job, taskStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobHasTasksInStatus indicates an expected call of JobHasTasksInStatus.
func (mr *MockPersistenceServiceMockRecorder) JobHasTasksInStatus(ctx, job, taskStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobHasTasksInStatus", reflect.TypeOf((*MockPersistenceService)(nil).JobHasTasksInStatus), ctx, job, taskStatus)
}

// SaveJobStatus mocks base method.
func (m *MockPersistenceService) SaveJobStatus(ctx context.Context, j *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJobStatus", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJobStatus indicates an expected call of SaveJobStatus.
func (mr *MockPersistenceServiceMockRecorder) SaveJobStatus(ctx, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJobStatus", reflect.TypeOf((*MockPersistenceService)(nil).SaveJobStatus), ctx, j)
}

// SaveTask mocks base method.
func (m *MockPersistenceService) SaveTask(ctx context.Context, task *persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockPersistenceServiceMockRecorder) SaveTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockPersistenceService)(nil).SaveTask), ctx, task)
}

// SaveTaskActivity mocks base method.
func (m *MockPersistenceService) SaveTaskActivity(ctx context.Context, t *persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaskActivity", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaskActivity indicates an expected call of SaveTaskActivity.
func (mr *MockPersistenceServiceMockRecorder) SaveTaskActivity(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaskActivity", reflect.TypeOf((*MockPersistenceService)(nil).SaveTaskActivity), ctx, t)
}

// SaveTaskStatus mocks base method.
func (m *MockPersistenceService) SaveTaskStatus(ctx context.Context, t *persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaskStatus", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaskStatus indicates an expected call of SaveTaskStatus.
func (mr *MockPersistenceServiceMockRecorder) SaveTaskStatus(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaskStatus", reflect.TypeOf((*MockPersistenceService)(nil).SaveTaskStatus), ctx, t)
}

// SaveTaskStepsCompleted mocks base method.
func (m *MockPersistenceService) SaveTaskStepsCompleted(ctx context.Context, jobID, taskID, stepsCompleted int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaskStepsCompleted", ctx, jobID, taskID, stepsCompleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaskStepsCompleted indicates an expected call of SaveTaskStepsCompleted.
func (mr *MockPersistenceServiceMockRecorder) SaveTaskStepsCompleted(ctx, jobID, taskID, stepsCompleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaskStepsCompleted", reflect.TypeOf((*MockPersistenceService)(nil).SaveTaskStepsCompleted), ctx, jobID, taskID, stepsCompleted)
}

// UpdateJobsTaskStatuses mocks base method.
func (m *MockPersistenceService) UpdateJobsTaskStatuses(ctx context.Context, job *persistence.Job, taskStatus api.TaskStatus, activity string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobsTaskStatuses", ctx, job, taskStatus, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobsTaskStatuses indicates an expected call of UpdateJobsTaskStatuses.
func (mr *MockPersistenceServiceMockRecorder) UpdateJobsTaskStatuses(ctx, job, taskStatus, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobsTaskStatuses", reflect.TypeOf((*MockPersistenceService)(nil).UpdateJobsTaskStatuses), ctx, job, taskStatus, activity)
}

// UpdateJobsTaskStatusesConditional mocks base method.
func (m *MockPersistenceService) UpdateJobsTaskStatusesConditional(ctx context.Context, job *persistence.Job, statusesToUpdate []api.TaskStatus, taskStatus api.TaskStatus, activity string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobsTaskStatusesConditional", ctx, job, statusesToUpdate, taskStatus, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobsTaskStatusesConditional indicates an expected call of UpdateJobsTaskStatusesConditional.
func (mr *MockPersistenceServiceMockRecorder) UpdateJobsTaskStatusesConditional(ctx, job, statusesToUpdate, taskStatus, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobsTaskStatusesConditional", reflect.TypeOf((*MockPersistenceService)(nil).UpdateJobsTaskStatusesConditional), ctx, job, statusesToUpdate, taskStatus, activity)
}

// UpdateJobsTaskStepCounts mocks base method.
func (m *MockPersistenceService) UpdateJobsTaskStepCounts(ctx context.Context, jobID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobsTaskStepCounts", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobsTaskStepCounts indicates an expected call of UpdateJobsTaskStepCounts.
func (mr *MockPersistenceServiceMockRecorder) UpdateJobsTaskStepCounts(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobsTaskStepCounts", reflect.TypeOf((*MockPersistenceService)(nil).UpdateJobsTaskStepCounts), ctx, jobID)
}

// MockChangeBroadcaster is a mock of ChangeBroadcaster interface.
type MockChangeBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockChangeBroadcasterMockRecorder
	isgomock struct{}
}

// MockChangeBroadcasterMockRecorder is the mock recorder for MockChangeBroadcaster.
type MockChangeBroadcasterMockRecorder struct {
	mock *MockChangeBroadcaster
}

// NewMockChangeBroadcaster creates a new mock instance.
func NewMockChangeBroadcaster(ctrl *gomock.Controller) *MockChangeBroadcaster {
	mock := &MockChangeBroadcaster{ctrl: ctrl}
	mock.recorder = &MockChangeBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeBroadcaster) EXPECT() *MockChangeBroadcasterMockRecorder {
	return m.recorder
}

// BroadcastJobUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastJobUpdate(jobUpdate api.EventJobUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastJobUpdate", jobUpdate)
}

// BroadcastJobUpdate indicates an expected call of BroadcastJobUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastJobUpdate(jobUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastJobUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastJobUpdate), jobUpdate)
}

// BroadcastTaskUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastTaskUpdate(taskUpdate api.EventTaskUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastTaskUpdate", taskUpdate)
}

// BroadcastTaskUpdate indicates an expected call of BroadcastTaskUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastTaskUpdate(taskUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTaskUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastTaskUpdate), taskUpdate)
}

// MockLogStorage is a mock of LogStorage interface.
type MockLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLogStorageMockRecorder
	isgomock struct{}
}

// MockLogStorageMockRecorder is the mock recorder for MockLogStorage.
type MockLogStorageMockRecorder struct {
	mock *MockLogStorage
}

// NewMockLogStorage creates a new mock instance.
func NewMockLogStorage(ctrl *gomock.Controller) *MockLogStorage {
	mock := &MockLogStorage{ctrl: ctrl}
	mock.recorder = &MockLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStorage) EXPECT() *MockLogStorageMockRecorder {
	return m.recorder
}

// WriteTimestamped mocks base method.
func (m *MockLogStorage) WriteTimestamped(logger zerolog.Logger, jobID, taskID, logText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTimestamped", logger, jobID, taskID, logText)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteTimestamped indicates an expected call of WriteTimestamped.
func (mr *MockLogStorageMockRecorder) WriteTimestamped(logger, jobID, taskID, logText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTimestamped", reflect.TypeOf((*MockLogStorage)(nil).WriteTimestamped), logger, jobID, taskID, logText)
}
