// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/manager/api_impl (interfaces: PersistenceService,ChangeBroadcaster,JobCompiler,LogStorage,ConfigService,TaskStateMachine,Shaman,LastRendered,LocalStorage,WorkerSleepScheduler,JobDeleter,FarmStatusService)
//
// Generated by this command:
//
//	mockgen -destination mocks/api_impl_mock.gen.go -package mocks projects.blender.org/studio/flamenco/internal/manager/api_impl PersistenceService,ChangeBroadcaster,JobCompiler,LogStorage,ConfigService,TaskStateMachine,Shaman,LastRendered,LocalStorage,WorkerSleepScheduler,JobDeleter,FarmStatusService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	zerolog "github.com/rs/zerolog"
	gomock "go.uber.org/mock/gomock"
	config "projects.blender.org/studio/flamenco/internal/manager/config"
	job_compilers "projects.blender.org/studio/flamenco/internal/manager/job_compilers"
	last_rendered "projects.blender.org/studio/flamenco/internal/manager/last_rendered"
	persistence "projects.blender.org/studio/flamenco/internal/manager/persistence"
	api "projects.blender.org/studio/flamenco/pkg/api"
)

// MockPersistenceService is a mock of PersistenceService interface.
type MockPersistenceService struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceServiceMockRecorder
	isgomock struct{}
}

// MockPersistenceServiceMockRecorder is the mock recorder for MockPersistenceService.
type MockPersistenceServiceMockRecorder struct {
	mock *MockPersistenceService
}

// NewMockPersistenceService creates a new mock instance.
func NewMockPersistenceService(ctrl *gomock.Controller) *MockPersistenceService {
	mock := &MockPersistenceService{ctrl: ctrl}
	mock.recorder = &MockPersistenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistenceService) EXPECT() *MockPersistenceServiceMockRecorder {
	return m.recorder
}

// AddWorkerToJobBlocklist mocks base method.
func (m *MockPersistenceService) AddWorkerToJobBlocklist(ctx context.Context, jobID, workerID int64, taskType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkerToJobBlocklist", ctx, jobID, workerID, taskType)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWorkerToJobBlocklist indicates an expected call of AddWorkerToJobBlocklist.
func (mr *MockPersistenceServiceMockRecorder) AddWorkerToJobBlocklist(ctx, jobID, workerID, taskType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkerToJobBlocklist", reflect.TypeOf((*MockPersistenceService)(nil).AddWorkerToJobBlocklist), ctx, jobID, workerID, taskType)
}

// AddWorkerToTaskFailedList mocks base method.
func (m *MockPersistenceService) AddWorkerToTaskFailedList(arg0 context.Context, arg1 *persistence.Task, arg2 *persistence.Worker) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkerToTaskFailedList", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWorkerToTaskFailedList indicates an expected call of AddWorkerToTaskFailedList.
func (mr *MockPersistenceServiceMockRecorder) AddWorkerToTaskFailedList(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkerToTaskFailedList", reflect.TypeOf((*MockPersistenceService)(nil).AddWorkerToTaskFailedList), arg0, arg1, arg2)
}

// ClearFailureListOfJob mocks base method.
func (m *MockPersistenceService) ClearFailureListOfJob(arg0 context.Context, arg1 *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearFailureListOfJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearFailureListOfJob indicates an expected call of ClearFailureListOfJob.
func (mr *MockPersistenceServiceMockRecorder) ClearFailureListOfJob(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearFailureListOfJob", reflect.TypeOf((*MockPersistenceService)(nil).ClearFailureListOfJob), arg0, arg1)
}

// ClearFailureListOfTask mocks base method.
func (m *MockPersistenceService) ClearFailureListOfTask(arg0 context.Context, arg1 *persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearFailureListOfTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearFailureListOfTask indicates an expected call of ClearFailureListOfTask.
func (mr *MockPersistenceServiceMockRecorder) ClearFailureListOfTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearFailureListOfTask", reflect.TypeOf((*MockPersistenceService)(nil).ClearFailureListOfTask), arg0, arg1)
}

// ClearJobBlocklist mocks base method.
func (m *MockPersistenceService) ClearJobBlocklist(ctx context.Context, job *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearJobBlocklist", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearJobBlocklist indicates an expected call of ClearJobBlocklist.
func (mr *MockPersistenceServiceMockRecorder) ClearJobBlocklist(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearJobBlocklist", reflect.TypeOf((*MockPersistenceService)(nil).ClearJobBlocklist), ctx, job)
}

// CountTaskFailuresOfWorker mocks base method.
func (m *MockPersistenceService) CountTaskFailuresOfWorker(ctx context.Context, jobUUID string, workerID int64, taskType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTaskFailuresOfWorker", ctx, jobUUID, workerID, taskType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTaskFailuresOfWorker indicates an expected call of CountTaskFailuresOfWorker.
func (mr *MockPersistenceServiceMockRecorder) CountTaskFailuresOfWorker(ctx, jobUUID, workerID, taskType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTaskFailuresOfWorker", reflect.TypeOf((*MockPersistenceService)(nil).CountTaskFailuresOfWorker), ctx, jobUUID, workerID, taskType)
}

// CreateWorker mocks base method.
func (m *MockPersistenceService) CreateWorker(ctx context.Context, w *persistence.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorker", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorker indicates an expected call of CreateWorker.
func (mr *MockPersistenceServiceMockRecorder) CreateWorker(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorker", reflect.TypeOf((*MockPersistenceService)(nil).CreateWorker), ctx, w)
}

// CreateWorkerTag mocks base method.
func (m *MockPersistenceService) CreateWorkerTag(ctx context.Context, tag *persistence.WorkerTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkerTag", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkerTag indicates an expected call of CreateWorkerTag.
func (mr *MockPersistenceServiceMockRecorder) CreateWorkerTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkerTag", reflect.TypeOf((*MockPersistenceService)(nil).CreateWorkerTag), ctx, tag)
}

// DeleteWorker mocks base method.
func (m *MockPersistenceService) DeleteWorker(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorker", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorker indicates an expected call of DeleteWorker.
func (mr *MockPersistenceServiceMockRecorder) DeleteWorker(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorker", reflect.TypeOf((*MockPersistenceService)(nil).DeleteWorker), ctx, uuid)
}

// DeleteWorkerTag mocks base method.
func (m *MockPersistenceService) DeleteWorkerTag(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkerTag", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkerTag indicates an expected call of DeleteWorkerTag.
func (mr *MockPersistenceServiceMockRecorder) DeleteWorkerTag(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkerTag", reflect.TypeOf((*MockPersistenceService)(nil).DeleteWorkerTag), ctx, uuid)
}

// FetchJob mocks base method.
func (m *MockPersistenceService) FetchJob(ctx context.Context, jobUUID string) (*persistence.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJob", ctx, jobUUID)
	ret0, _ := ret[0].(*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJob indicates an expected call of FetchJob.
func (mr *MockPersistenceServiceMockRecorder) FetchJob(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJob", reflect.TypeOf((*MockPersistenceService)(nil).FetchJob), ctx, jobUUID)
}

// FetchJobBlocklist mocks base method.
func (m *MockPersistenceService) FetchJobBlocklist(ctx context.Context, jobUUID string) ([]persistence.JobBlockListEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJobBlocklist", ctx, jobUUID)
	ret0, _ := ret[0].([]persistence.JobBlockListEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobBlocklist indicates an expected call of FetchJobBlocklist.
func (mr *MockPersistenceServiceMockRecorder) FetchJobBlocklist(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobBlocklist", reflect.TypeOf((*MockPersistenceService)(nil).FetchJobBlocklist), ctx, jobUUID)
}

// FetchJobByID mocks base method.
func (m *MockPersistenceService) FetchJobByID(ctx context.Context, jobID int64) (*persistence.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJobByID", ctx, jobID)
	ret0, _ := ret[0].(*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobByID indicates an expected call of FetchJobByID.
func (mr *MockPersistenceServiceMockRecorder) FetchJobByID(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobByID", reflect.TypeOf((*MockPersistenceService)(nil).FetchJobByID), ctx, jobID)
}

// FetchJobs mocks base method.
func (m *MockPersistenceService) FetchJobs(ctx context.Context) ([]*persistence.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJobs", ctx)
	ret0, _ := ret[0].([]*persistence.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobs indicates an expected call of FetchJobs.
func (mr *MockPersistenceServiceMockRecorder) FetchJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobs", reflect.TypeOf((*MockPersistenceService)(nil).FetchJobs), ctx)
}

// FetchTagsOfWorker mocks base method.
func (m *MockPersistenceService) FetchTagsOfWorker(ctx context.Context, workerUUID string) ([]persistence.WorkerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTagsOfWorker", ctx, workerUUID)
	ret0, _ := ret[0].([]persistence.WorkerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTagsOfWorker indicates an expected call of FetchTagsOfWorker.
func (mr *MockPersistenceServiceMockRecorder) FetchTagsOfWorker(ctx, workerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTagsOfWorker", reflect.TypeOf((*MockPersistenceService)(nil).FetchTagsOfWorker), ctx, workerUUID)
}

// FetchTask mocks base method.
func (m *MockPersistenceService) FetchTask(ctx context.Context, taskID string) (persistence.TaskJobWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTask", ctx, taskID)
	ret0, _ := ret[0].(persistence.TaskJobWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTask indicates an expected call of FetchTask.
func (mr *MockPersistenceServiceMockRecorder) FetchTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTask", reflect.TypeOf((*MockPersistenceService)(nil).FetchTask), ctx, taskID)
}

// FetchTaskFailureList mocks base method.
func (m *MockPersistenceService) FetchTaskFailureList(arg0 context.Context, arg1 *persistence.Task) ([]*persistence.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTaskFailureList", arg0, arg1)
	ret0, _ := ret[0].([]*persistence.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskFailureList indicates an expected call of FetchTaskFailureList.
func (mr *MockPersistenceServiceMockRecorder) FetchTaskFailureList(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskFailureList", reflect.TypeOf((*MockPersistenceService)(nil).FetchTaskFailureList), arg0, arg1)
}

// FetchTaskJobUUID mocks base method.
func (m *MockPersistenceService) FetchTaskJobUUID(ctx context.Context, taskID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTaskJobUUID", ctx, taskID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskJobUUID indicates an expected call of FetchTaskJobUUID.
func (mr *MockPersistenceServiceMockRecorder) FetchTaskJobUUID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskJobUUID", reflect.TypeOf((*MockPersistenceService)(nil).FetchTaskJobUUID), ctx, taskID)
}

// FetchWorker mocks base method.
func (m *MockPersistenceService) FetchWorker(ctx context.Context, uuid string) (*persistence.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorker", ctx, uuid)
	ret0, _ := ret[0].(*persistence.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorker indicates an expected call of FetchWorker.
func (mr *MockPersistenceServiceMockRecorder) FetchWorker(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorker", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorker), ctx, uuid)
}

// FetchWorkerTag mocks base method.
func (m *MockPersistenceService) FetchWorkerTag(ctx context.Context, uuid string) (persistence.WorkerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerTag", ctx, uuid)
	ret0, _ := ret[0].(persistence.WorkerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTag indicates an expected call of FetchWorkerTag.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerTag(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTag", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerTag), ctx, uuid)
}

// FetchWorkerTagByID mocks base method.
func (m *MockPersistenceService) FetchWorkerTagByID(ctx context.Context, id int64) (persistence.WorkerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerTagByID", ctx, id)
	ret0, _ := ret[0].(persistence.WorkerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTagByID indicates an expected call of FetchWorkerTagByID.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerTagByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTagByID", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerTagByID), ctx, id)
}

// FetchWorkerTagByName mocks base method.
func (m *MockPersistenceService) FetchWorkerTagByName(ctx context.Context, name string) (persistence.WorkerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerTagByName", ctx, name)
	ret0, _ := ret[0].(persistence.WorkerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTagByName indicates an expected call of FetchWorkerTagByName.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerTagByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTagByName", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerTagByName), ctx, name)
}

// FetchWorkerTags mocks base method.
func (m *MockPersistenceService) FetchWorkerTags(ctx context.Context) ([]persistence.WorkerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerTags", ctx)
	ret0, _ := ret[0].([]persistence.WorkerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTags indicates an expected call of FetchWorkerTags.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTags", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerTags), ctx)
}

// FetchWorkerTask mocks base method.
func (m *MockPersistenceService) FetchWorkerTask(arg0 context.Context, arg1 *persistence.Worker) (*persistence.TaskJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkerTask", arg0, arg1)
	ret0, _ := ret[0].(*persistence.TaskJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTask indicates an expected call of FetchWorkerTask.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkerTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTask", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkerTask), arg0, arg1)
}

// FetchWorkers mocks base method.
func (m *MockPersistenceService) FetchWorkers(ctx context.Context) ([]*persistence.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWorkers", ctx)
	ret0, _ := ret[0].([]*persistence.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkers indicates an expected call of FetchWorkers.
func (mr *MockPersistenceServiceMockRecorder) FetchWorkers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkers", reflect.TypeOf((*MockPersistenceService)(nil).FetchWorkers), ctx)
}

// GetLastRenderedJobUUID mocks base method.
func (m *MockPersistenceService) GetLastRenderedJobUUID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastRenderedJobUUID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastRenderedJobUUID indicates an expected call of GetLastRenderedJobUUID.
func (mr *MockPersistenceServiceMockRecorder) GetLastRenderedJobUUID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastRenderedJobUUID", reflect.TypeOf((*MockPersistenceService)(nil).GetLastRenderedJobUUID), ctx)
}

// QueryJobTaskSummaries mocks base method.
func (m *MockPersistenceService) QueryJobTaskSummaries(ctx context.Context, jobUUID string) ([]persistence.TaskSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryJobTaskSummaries", ctx, jobUUID)
	ret0, _ := ret[0].([]persistence.TaskSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryJobTaskSummaries indicates an expected call of QueryJobTaskSummaries.
func (mr *MockPersistenceServiceMockRecorder) QueryJobTaskSummaries(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryJobTaskSummaries", reflect.TypeOf((*MockPersistenceService)(nil).QueryJobTaskSummaries), ctx, jobUUID)
}

// RemoveFromJobBlocklist mocks base method.
func (m *MockPersistenceService) RemoveFromJobBlocklist(ctx context.Context, jobUUID, workerUUID, taskType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromJobBlocklist", ctx, jobUUID, workerUUID, taskType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromJobBlocklist indicates an expected call of RemoveFromJobBlocklist.
func (mr *MockPersistenceServiceMockRecorder) RemoveFromJobBlocklist(ctx, jobUUID, workerUUID, taskType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromJobBlocklist", reflect.TypeOf((*MockPersistenceService)(nil).RemoveFromJobBlocklist), ctx, jobUUID, workerUUID, taskType)
}

// SaveJobPriority mocks base method.
func (m *MockPersistenceService) SaveJobPriority(ctx context.Context, job *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJobPriority", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJobPriority indicates an expected call of SaveJobPriority.
func (mr *MockPersistenceServiceMockRecorder) SaveJobPriority(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJobPriority", reflect.TypeOf((*MockPersistenceService)(nil).SaveJobPriority), ctx, job)
}

// SaveJobWorkerTag mocks base method.
func (m *MockPersistenceService) SaveJobWorkerTag(ctx context.Context, job *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveJobWorkerTag", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveJobWorkerTag indicates an expected call of SaveJobWorkerTag.
func (mr *MockPersistenceServiceMockRecorder) SaveJobWorkerTag(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJobWorkerTag", reflect.TypeOf((*MockPersistenceService)(nil).SaveJobWorkerTag), ctx, job)
}

// SaveTaskActivity mocks base method.
func (m *MockPersistenceService) SaveTaskActivity(ctx context.Context, t *persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaskActivity", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaskActivity indicates an expected call of SaveTaskActivity.
func (mr *MockPersistenceServiceMockRecorder) SaveTaskActivity(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaskActivity", reflect.TypeOf((*MockPersistenceService)(nil).SaveTaskActivity), ctx, t)
}

// SaveTaskStepsCompleted mocks base method.
func (m *MockPersistenceService) SaveTaskStepsCompleted(ctx context.Context, jobID, taskID, stepsCompleted int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTaskStepsCompleted", ctx, jobID, taskID, stepsCompleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTaskStepsCompleted indicates an expected call of SaveTaskStepsCompleted.
func (mr *MockPersistenceServiceMockRecorder) SaveTaskStepsCompleted(ctx, jobID, taskID, stepsCompleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTaskStepsCompleted", reflect.TypeOf((*MockPersistenceService)(nil).SaveTaskStepsCompleted), ctx, jobID, taskID, stepsCompleted)
}

// SaveWorker mocks base method.
func (m *MockPersistenceService) SaveWorker(ctx context.Context, w *persistence.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWorker", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWorker indicates an expected call of SaveWorker.
func (mr *MockPersistenceServiceMockRecorder) SaveWorker(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWorker", reflect.TypeOf((*MockPersistenceService)(nil).SaveWorker), ctx, w)
}

// SaveWorkerStatus mocks base method.
func (m *MockPersistenceService) SaveWorkerStatus(ctx context.Context, w *persistence.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWorkerStatus", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWorkerStatus indicates an expected call of SaveWorkerStatus.
func (mr *MockPersistenceServiceMockRecorder) SaveWorkerStatus(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWorkerStatus", reflect.TypeOf((*MockPersistenceService)(nil).SaveWorkerStatus), ctx, w)
}

// SaveWorkerTag mocks base method.
func (m *MockPersistenceService) SaveWorkerTag(ctx context.Context, tag *persistence.WorkerTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWorkerTag", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWorkerTag indicates an expected call of SaveWorkerTag.
func (mr *MockPersistenceServiceMockRecorder) SaveWorkerTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWorkerTag", reflect.TypeOf((*MockPersistenceService)(nil).SaveWorkerTag), ctx, tag)
}

// ScheduleTask mocks base method.
func (m *MockPersistenceService) ScheduleTask(ctx context.Context, w *persistence.Worker) (*persistence.ScheduledTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleTask", ctx, w)
	ret0, _ := ret[0].(*persistence.ScheduledTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleTask indicates an expected call of ScheduleTask.
func (mr *MockPersistenceServiceMockRecorder) ScheduleTask(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleTask", reflect.TypeOf((*MockPersistenceService)(nil).ScheduleTask), ctx, w)
}

// SetLastRendered mocks base method.
func (m *MockPersistenceService) SetLastRendered(ctx context.Context, jobUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastRendered", ctx, jobUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastRendered indicates an expected call of SetLastRendered.
func (mr *MockPersistenceServiceMockRecorder) SetLastRendered(ctx, jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastRendered", reflect.TypeOf((*MockPersistenceService)(nil).SetLastRendered), ctx, jobUUID)
}

// StoreAuthoredJob mocks base method.
func (m *MockPersistenceService) StoreAuthoredJob(ctx context.Context, authoredJob job_compilers.AuthoredJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAuthoredJob", ctx, authoredJob)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAuthoredJob indicates an expected call of StoreAuthoredJob.
func (mr *MockPersistenceServiceMockRecorder) StoreAuthoredJob(ctx, authoredJob any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAuthoredJob", reflect.TypeOf((*MockPersistenceService)(nil).StoreAuthoredJob), ctx, authoredJob)
}

// TaskTouchedByWorker mocks base method.
func (m *MockPersistenceService) TaskTouchedByWorker(ctx context.Context, taskUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskTouchedByWorker", ctx, taskUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskTouchedByWorker indicates an expected call of TaskTouchedByWorker.
func (mr *MockPersistenceServiceMockRecorder) TaskTouchedByWorker(ctx, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskTouchedByWorker", reflect.TypeOf((*MockPersistenceService)(nil).TaskTouchedByWorker), ctx, taskUUID)
}

// WorkerSeen mocks base method.
func (m *MockPersistenceService) WorkerSeen(ctx context.Context, w *persistence.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerSeen", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkerSeen indicates an expected call of WorkerSeen.
func (mr *MockPersistenceServiceMockRecorder) WorkerSeen(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerSeen", reflect.TypeOf((*MockPersistenceService)(nil).WorkerSeen), ctx, w)
}

// WorkerSetTags mocks base method.
func (m *MockPersistenceService) WorkerSetTags(ctx context.Context, worker *persistence.Worker, tagUUIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerSetTags", ctx, worker, tagUUIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkerSetTags indicates an expected call of WorkerSetTags.
func (mr *MockPersistenceServiceMockRecorder) WorkerSetTags(ctx, worker, tagUUIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerSetTags", reflect.TypeOf((*MockPersistenceService)(nil).WorkerSetTags), ctx, worker, tagUUIDs)
}

// WorkersLeftToRun mocks base method.
func (m *MockPersistenceService) WorkersLeftToRun(ctx context.Context, job *persistence.Job, taskType string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkersLeftToRun", ctx, job, taskType)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkersLeftToRun indicates an expected call of WorkersLeftToRun.
func (mr *MockPersistenceServiceMockRecorder) WorkersLeftToRun(ctx, job, taskType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkersLeftToRun", reflect.TypeOf((*MockPersistenceService)(nil).WorkersLeftToRun), ctx, job, taskType)
}

// MockChangeBroadcaster is a mock of ChangeBroadcaster interface.
type MockChangeBroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockChangeBroadcasterMockRecorder
	isgomock struct{}
}

// MockChangeBroadcasterMockRecorder is the mock recorder for MockChangeBroadcaster.
type MockChangeBroadcasterMockRecorder struct {
	mock *MockChangeBroadcaster
}

// NewMockChangeBroadcaster creates a new mock instance.
func NewMockChangeBroadcaster(ctrl *gomock.Controller) *MockChangeBroadcaster {
	mock := &MockChangeBroadcaster{ctrl: ctrl}
	mock.recorder = &MockChangeBroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeBroadcaster) EXPECT() *MockChangeBroadcasterMockRecorder {
	return m.recorder
}

// BroadcastJobUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastJobUpdate(jobUpdate api.EventJobUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastJobUpdate", jobUpdate)
}

// BroadcastJobUpdate indicates an expected call of BroadcastJobUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastJobUpdate(jobUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastJobUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastJobUpdate), jobUpdate)
}

// BroadcastLastRenderedImage mocks base method.
func (m *MockChangeBroadcaster) BroadcastLastRenderedImage(update api.EventLastRenderedUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastLastRenderedImage", update)
}

// BroadcastLastRenderedImage indicates an expected call of BroadcastLastRenderedImage.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastLastRenderedImage(update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastLastRenderedImage", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastLastRenderedImage), update)
}

// BroadcastNewJob mocks base method.
func (m *MockChangeBroadcaster) BroadcastNewJob(jobUpdate api.EventJobUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastNewJob", jobUpdate)
}

// BroadcastNewJob indicates an expected call of BroadcastNewJob.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastNewJob(jobUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastNewJob", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastNewJob), jobUpdate)
}

// BroadcastNewWorker mocks base method.
func (m *MockChangeBroadcaster) BroadcastNewWorker(workerUpdate api.EventWorkerUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastNewWorker", workerUpdate)
}

// BroadcastNewWorker indicates an expected call of BroadcastNewWorker.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastNewWorker(workerUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastNewWorker", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastNewWorker), workerUpdate)
}

// BroadcastNewWorkerTag mocks base method.
func (m *MockChangeBroadcaster) BroadcastNewWorkerTag(workerTagUpdate api.EventWorkerTagUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastNewWorkerTag", workerTagUpdate)
}

// BroadcastNewWorkerTag indicates an expected call of BroadcastNewWorkerTag.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastNewWorkerTag(workerTagUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastNewWorkerTag", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastNewWorkerTag), workerTagUpdate)
}

// BroadcastTaskUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastTaskUpdate(arg0 api.EventTaskUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastTaskUpdate", arg0)
}

// BroadcastTaskUpdate indicates an expected call of BroadcastTaskUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastTaskUpdate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTaskUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastTaskUpdate), arg0)
}

// BroadcastWorkerTagUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastWorkerTagUpdate(workerTagUpdate api.EventWorkerTagUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastWorkerTagUpdate", workerTagUpdate)
}

// BroadcastWorkerTagUpdate indicates an expected call of BroadcastWorkerTagUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastWorkerTagUpdate(workerTagUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastWorkerTagUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastWorkerTagUpdate), workerTagUpdate)
}

// BroadcastWorkerUpdate mocks base method.
func (m *MockChangeBroadcaster) BroadcastWorkerUpdate(workerUpdate api.EventWorkerUpdate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastWorkerUpdate", workerUpdate)
}

// BroadcastWorkerUpdate indicates an expected call of BroadcastWorkerUpdate.
func (mr *MockChangeBroadcasterMockRecorder) BroadcastWorkerUpdate(workerUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastWorkerUpdate", reflect.TypeOf((*MockChangeBroadcaster)(nil).BroadcastWorkerUpdate), workerUpdate)
}

// MockJobCompiler is a mock of JobCompiler interface.
type MockJobCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockJobCompilerMockRecorder
	isgomock struct{}
}

// MockJobCompilerMockRecorder is the mock recorder for MockJobCompiler.
type MockJobCompilerMockRecorder struct {
	mock *MockJobCompiler
}

// NewMockJobCompiler creates a new mock instance.
func NewMockJobCompiler(ctrl *gomock.Controller) *MockJobCompiler {
	mock := &MockJobCompiler{ctrl: ctrl}
	mock.recorder = &MockJobCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobCompiler) EXPECT() *MockJobCompilerMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockJobCompiler) Compile(ctx context.Context, job api.SubmittedJob) (*job_compilers.AuthoredJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, job)
	ret0, _ := ret[0].(*job_compilers.AuthoredJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockJobCompilerMockRecorder) Compile(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockJobCompiler)(nil).Compile), ctx, job)
}

// GetJobType mocks base method.
func (m *MockJobCompiler) GetJobType(typeName string) (api.AvailableJobType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobType", typeName)
	ret0, _ := ret[0].(api.AvailableJobType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobType indicates an expected call of GetJobType.
func (mr *MockJobCompilerMockRecorder) GetJobType(typeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobType", reflect.TypeOf((*MockJobCompiler)(nil).GetJobType), typeName)
}

// ListJobTypes mocks base method.
func (m *MockJobCompiler) ListJobTypes() api.AvailableJobTypes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobTypes")
	ret0, _ := ret[0].(api.AvailableJobTypes)
	return ret0
}

// ListJobTypes indicates an expected call of ListJobTypes.
func (mr *MockJobCompilerMockRecorder) ListJobTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobTypes", reflect.TypeOf((*MockJobCompiler)(nil).ListJobTypes))
}

// MockLogStorage is a mock of LogStorage interface.
type MockLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLogStorageMockRecorder
	isgomock struct{}
}

// MockLogStorageMockRecorder is the mock recorder for MockLogStorage.
type MockLogStorageMockRecorder struct {
	mock *MockLogStorage
}

// NewMockLogStorage creates a new mock instance.
func NewMockLogStorage(ctrl *gomock.Controller) *MockLogStorage {
	mock := &MockLogStorage{ctrl: ctrl}
	mock.recorder = &MockLogStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStorage) EXPECT() *MockLogStorageMockRecorder {
	return m.recorder
}

// Filepath mocks base method.
func (m *MockLogStorage) Filepath(jobUUID, taskUUID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filepath", jobUUID, taskUUID)
	ret0, _ := ret[0].(string)
	return ret0
}

// Filepath indicates an expected call of Filepath.
func (mr *MockLogStorageMockRecorder) Filepath(jobUUID, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filepath", reflect.TypeOf((*MockLogStorage)(nil).Filepath), jobUUID, taskUUID)
}

// RotateFile mocks base method.
func (m *MockLogStorage) RotateFile(logger zerolog.Logger, jobUUID, taskUUID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RotateFile", logger, jobUUID, taskUUID)
}

// RotateFile indicates an expected call of RotateFile.
func (mr *MockLogStorageMockRecorder) RotateFile(logger, jobUUID, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateFile", reflect.TypeOf((*MockLogStorage)(nil).RotateFile), logger, jobUUID, taskUUID)
}

// Tail mocks base method.
func (m *MockLogStorage) Tail(jobID, taskUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tail", jobID, taskUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tail indicates an expected call of Tail.
func (mr *MockLogStorageMockRecorder) Tail(jobID, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*MockLogStorage)(nil).Tail), jobID, taskUUID)
}

// TaskLogSize mocks base method.
func (m *MockLogStorage) TaskLogSize(jobUUID, taskUUID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskLogSize", jobUUID, taskUUID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskLogSize indicates an expected call of TaskLogSize.
func (mr *MockLogStorageMockRecorder) TaskLogSize(jobUUID, taskUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskLogSize", reflect.TypeOf((*MockLogStorage)(nil).TaskLogSize), jobUUID, taskUUID)
}

// Write mocks base method.
func (m *MockLogStorage) Write(logger zerolog.Logger, jobUUID, taskUUID, logText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", logger, jobUUID, taskUUID, logText)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockLogStorageMockRecorder) Write(logger, jobUUID, taskUUID, logText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLogStorage)(nil).Write), logger, jobUUID, taskUUID, logText)
}

// WriteTimestamped mocks base method.
func (m *MockLogStorage) WriteTimestamped(logger zerolog.Logger, jobUUID, taskUUID, logText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTimestamped", logger, jobUUID, taskUUID, logText)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteTimestamped indicates an expected call of WriteTimestamped.
func (mr *MockLogStorageMockRecorder) WriteTimestamped(logger, jobUUID, taskUUID, logText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTimestamped", reflect.TypeOf((*MockLogStorage)(nil).WriteTimestamped), logger, jobUUID, taskUUID, logText)
}

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
	isgomock struct{}
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// EffectiveStoragePath mocks base method.
func (m *MockConfigService) EffectiveStoragePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EffectiveStoragePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// EffectiveStoragePath indicates an expected call of EffectiveStoragePath.
func (mr *MockConfigServiceMockRecorder) EffectiveStoragePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EffectiveStoragePath", reflect.TypeOf((*MockConfigService)(nil).EffectiveStoragePath))
}

// ForceFirstRun mocks base method.
func (m *MockConfigService) ForceFirstRun() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForceFirstRun")
}

// ForceFirstRun indicates an expected call of ForceFirstRun.
func (mr *MockConfigServiceMockRecorder) ForceFirstRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFirstRun", reflect.TypeOf((*MockConfigService)(nil).ForceFirstRun))
}

// Get mocks base method.
func (m *MockConfigService) Get() *config.Conf {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*config.Conf)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockConfigServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigService)(nil).Get))
}

// Load mocks base method.
func (m *MockConfigService) Load() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigServiceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigService)(nil).Load))
}

// NewVariableExpander mocks base method.
func (m *MockConfigService) NewVariableExpander(audience config.VariableAudience, platform config.VariablePlatform) *config.VariableExpander {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVariableExpander", audience, platform)
	ret0, _ := ret[0].(*config.VariableExpander)
	return ret0
}

// NewVariableExpander indicates an expected call of NewVariableExpander.
func (mr *MockConfigServiceMockRecorder) NewVariableExpander(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVariableExpander", reflect.TypeOf((*MockConfigService)(nil).NewVariableExpander), audience, platform)
}

// NewVariableToValueConverter mocks base method.
func (m *MockConfigService) NewVariableToValueConverter(audience config.VariableAudience, platform config.VariablePlatform) *config.ValueToVariableReplacer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVariableToValueConverter", audience, platform)
	ret0, _ := ret[0].(*config.ValueToVariableReplacer)
	return ret0
}

// NewVariableToValueConverter indicates an expected call of NewVariableToValueConverter.
func (mr *MockConfigServiceMockRecorder) NewVariableToValueConverter(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVariableToValueConverter", reflect.TypeOf((*MockConfigService)(nil).NewVariableToValueConverter), audience, platform)
}

// Replace mocks base method.
func (m *MockConfigService) Replace(arg0 config.Conf) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockConfigServiceMockRecorder) Replace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockConfigService)(nil).Replace), arg0)
}

// ResolveVariables mocks base method.
func (m *MockConfigService) ResolveVariables(audience config.VariableAudience, platform config.VariablePlatform) map[string]config.ResolvedVariable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveVariables", audience, platform)
	ret0, _ := ret[0].(map[string]config.ResolvedVariable)
	return ret0
}

// ResolveVariables indicates an expected call of ResolveVariables.
func (mr *MockConfigServiceMockRecorder) ResolveVariables(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveVariables", reflect.TypeOf((*MockConfigService)(nil).ResolveVariables), audience, platform)
}

// Save mocks base method.
func (m *MockConfigService) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigServiceMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigService)(nil).Save))
}

// MockTaskStateMachine is a mock of TaskStateMachine interface.
type MockTaskStateMachine struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStateMachineMockRecorder
	isgomock struct{}
}

// MockTaskStateMachineMockRecorder is the mock recorder for MockTaskStateMachine.
type MockTaskStateMachineMockRecorder struct {
	mock *MockTaskStateMachine
}

// NewMockTaskStateMachine creates a new mock instance.
func NewMockTaskStateMachine(ctrl *gomock.Controller) *MockTaskStateMachine {
	mock := &MockTaskStateMachine{ctrl: ctrl}
	mock.recorder = &MockTaskStateMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStateMachine) EXPECT() *MockTaskStateMachineMockRecorder {
	return m.recorder
}

// JobStatusChange mocks base method.
func (m *MockTaskStateMachine) JobStatusChange(ctx context.Context, jobUUID string, newJobStatus api.JobStatus, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobStatusChange", ctx, jobUUID, newJobStatus, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// JobStatusChange indicates an expected call of JobStatusChange.
func (mr *MockTaskStateMachineMockRecorder) JobStatusChange(ctx, jobUUID, newJobStatus, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobStatusChange", reflect.TypeOf((*MockTaskStateMachine)(nil).JobStatusChange), ctx, jobUUID, newJobStatus, reason)
}

// RequeueActiveTasksOfWorker mocks base method.
func (m *MockTaskStateMachine) RequeueActiveTasksOfWorker(ctx context.Context, worker *persistence.Worker, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueActiveTasksOfWorker", ctx, worker, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeueActiveTasksOfWorker indicates an expected call of RequeueActiveTasksOfWorker.
func (mr *MockTaskStateMachineMockRecorder) RequeueActiveTasksOfWorker(ctx, worker, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueActiveTasksOfWorker", reflect.TypeOf((*MockTaskStateMachine)(nil).RequeueActiveTasksOfWorker), ctx, worker, reason)
}

// RequeueFailedTasksOfWorkerOfJob mocks base method.
func (m *MockTaskStateMachine) RequeueFailedTasksOfWorkerOfJob(ctx context.Context, worker *persistence.Worker, jobUUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueFailedTasksOfWorkerOfJob", ctx, worker, jobUUID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeueFailedTasksOfWorkerOfJob indicates an expected call of RequeueFailedTasksOfWorkerOfJob.
func (mr *MockTaskStateMachineMockRecorder) RequeueFailedTasksOfWorkerOfJob(ctx, worker, jobUUID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueFailedTasksOfWorkerOfJob", reflect.TypeOf((*MockTaskStateMachine)(nil).RequeueFailedTasksOfWorkerOfJob), ctx, worker, jobUUID, reason)
}

// TaskStatusChange mocks base method.
func (m *MockTaskStateMachine) TaskStatusChange(ctx context.Context, task *persistence.Task, newStatus api.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskStatusChange", ctx, task, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskStatusChange indicates an expected call of TaskStatusChange.
func (mr *MockTaskStateMachineMockRecorder) TaskStatusChange(ctx, task, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskStatusChange", reflect.TypeOf((*MockTaskStateMachine)(nil).TaskStatusChange), ctx, task, newStatus)
}

// MockShaman is a mock of Shaman interface.
type MockShaman struct {
	ctrl     *gomock.Controller
	recorder *MockShamanMockRecorder
	isgomock struct{}
}

// MockShamanMockRecorder is the mock recorder for MockShaman.
type MockShamanMockRecorder struct {
	mock *MockShaman
}

// NewMockShaman creates a new mock instance.
func NewMockShaman(ctrl *gomock.Controller) *MockShaman {
	mock := &MockShaman{ctrl: ctrl}
	mock.recorder = &MockShamanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShaman) EXPECT() *MockShamanMockRecorder {
	return m.recorder
}

// Checkout mocks base method.
func (m *MockShaman) Checkout(ctx context.Context, checkout api.ShamanCheckout) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, checkout)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockShamanMockRecorder) Checkout(ctx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockShaman)(nil).Checkout), ctx, checkout)
}

// EraseCheckout mocks base method.
func (m *MockShaman) EraseCheckout(checkoutID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EraseCheckout", checkoutID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EraseCheckout indicates an expected call of EraseCheckout.
func (mr *MockShamanMockRecorder) EraseCheckout(checkoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EraseCheckout", reflect.TypeOf((*MockShaman)(nil).EraseCheckout), checkoutID)
}

// FileStore mocks base method.
func (m *MockShaman) FileStore(ctx context.Context, file io.ReadCloser, checksum string, filesize int64, canDefer bool, originalFilename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileStore", ctx, file, checksum, filesize, canDefer, originalFilename)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileStore indicates an expected call of FileStore.
func (mr *MockShamanMockRecorder) FileStore(ctx, file, checksum, filesize, canDefer, originalFilename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileStore", reflect.TypeOf((*MockShaman)(nil).FileStore), ctx, file, checksum, filesize, canDefer, originalFilename)
}

// FileStoreCheck mocks base method.
func (m *MockShaman) FileStoreCheck(ctx context.Context, checksum string, filesize int64) api.ShamanFileStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileStoreCheck", ctx, checksum, filesize)
	ret0, _ := ret[0].(api.ShamanFileStatus)
	return ret0
}

// FileStoreCheck indicates an expected call of FileStoreCheck.
func (mr *MockShamanMockRecorder) FileStoreCheck(ctx, checksum, filesize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileStoreCheck", reflect.TypeOf((*MockShaman)(nil).FileStoreCheck), ctx, checksum, filesize)
}

// IsEnabled mocks base method.
func (m *MockShaman) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockShamanMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockShaman)(nil).IsEnabled))
}

// Requirements mocks base method.
func (m *MockShaman) Requirements(ctx context.Context, requirements api.ShamanRequirementsRequest) (api.ShamanRequirementsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Requirements", ctx, requirements)
	ret0, _ := ret[0].(api.ShamanRequirementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Requirements indicates an expected call of Requirements.
func (mr *MockShamanMockRecorder) Requirements(ctx, requirements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requirements", reflect.TypeOf((*MockShaman)(nil).Requirements), ctx, requirements)
}

// MockLastRendered is a mock of LastRendered interface.
type MockLastRendered struct {
	ctrl     *gomock.Controller
	recorder *MockLastRenderedMockRecorder
	isgomock struct{}
}

// MockLastRenderedMockRecorder is the mock recorder for MockLastRendered.
type MockLastRenderedMockRecorder struct {
	mock *MockLastRendered
}

// NewMockLastRendered creates a new mock instance.
func NewMockLastRendered(ctrl *gomock.Controller) *MockLastRendered {
	mock := &MockLastRendered{ctrl: ctrl}
	mock.recorder = &MockLastRenderedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLastRendered) EXPECT() *MockLastRenderedMockRecorder {
	return m.recorder
}

// JobHasImage mocks base method.
func (m *MockLastRendered) JobHasImage(jobUUID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobHasImage", jobUUID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// JobHasImage indicates an expected call of JobHasImage.
func (mr *MockLastRenderedMockRecorder) JobHasImage(jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobHasImage", reflect.TypeOf((*MockLastRendered)(nil).JobHasImage), jobUUID)
}

// PathForJob mocks base method.
func (m *MockLastRendered) PathForJob(jobUUID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathForJob", jobUUID)
	ret0, _ := ret[0].(string)
	return ret0
}

// PathForJob indicates an expected call of PathForJob.
func (mr *MockLastRenderedMockRecorder) PathForJob(jobUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathForJob", reflect.TypeOf((*MockLastRendered)(nil).PathForJob), jobUUID)
}

// QueueImage mocks base method.
func (m *MockLastRendered) QueueImage(payload last_rendered.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueImage", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueImage indicates an expected call of QueueImage.
func (mr *MockLastRenderedMockRecorder) QueueImage(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueImage", reflect.TypeOf((*MockLastRendered)(nil).QueueImage), payload)
}

// ThumbSpecs mocks base method.
func (m *MockLastRendered) ThumbSpecs() []last_rendered.Thumbspec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ThumbSpecs")
	ret0, _ := ret[0].([]last_rendered.Thumbspec)
	return ret0
}

// ThumbSpecs indicates an expected call of ThumbSpecs.
func (mr *MockLastRenderedMockRecorder) ThumbSpecs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThumbSpecs", reflect.TypeOf((*MockLastRendered)(nil).ThumbSpecs))
}

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
	isgomock struct{}
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// RelPath mocks base method.
func (m *MockLocalStorage) RelPath(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelPath", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelPath indicates an expected call of RelPath.
func (mr *MockLocalStorageMockRecorder) RelPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelPath", reflect.TypeOf((*MockLocalStorage)(nil).RelPath), path)
}

// MockWorkerSleepScheduler is a mock of WorkerSleepScheduler interface.
type MockWorkerSleepScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerSleepSchedulerMockRecorder
	isgomock struct{}
}

// MockWorkerSleepSchedulerMockRecorder is the mock recorder for MockWorkerSleepScheduler.
type MockWorkerSleepSchedulerMockRecorder struct {
	mock *MockWorkerSleepScheduler
}

// NewMockWorkerSleepScheduler creates a new mock instance.
func NewMockWorkerSleepScheduler(ctrl *gomock.Controller) *MockWorkerSleepScheduler {
	mock := &MockWorkerSleepScheduler{ctrl: ctrl}
	mock.recorder = &MockWorkerSleepSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerSleepScheduler) EXPECT() *MockWorkerSleepSchedulerMockRecorder {
	return m.recorder
}

// FetchSchedule mocks base method.
func (m *MockWorkerSleepScheduler) FetchSchedule(ctx context.Context, workerUUID string) (*persistence.SleepSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSchedule", ctx, workerUUID)
	ret0, _ := ret[0].(*persistence.SleepSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSchedule indicates an expected call of FetchSchedule.
func (mr *MockWorkerSleepSchedulerMockRecorder) FetchSchedule(ctx, workerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSchedule", reflect.TypeOf((*MockWorkerSleepScheduler)(nil).FetchSchedule), ctx, workerUUID)
}

// SetSchedule mocks base method.
func (m *MockWorkerSleepScheduler) SetSchedule(ctx context.Context, workerUUID string, schedule persistence.SleepSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSchedule", ctx, workerUUID, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSchedule indicates an expected call of SetSchedule.
func (mr *MockWorkerSleepSchedulerMockRecorder) SetSchedule(ctx, workerUUID, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSchedule", reflect.TypeOf((*MockWorkerSleepScheduler)(nil).SetSchedule), ctx, workerUUID, schedule)
}

// WorkerStatus mocks base method.
func (m *MockWorkerSleepScheduler) WorkerStatus(ctx context.Context, workerUUID string) (api.WorkerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerStatus", ctx, workerUUID)
	ret0, _ := ret[0].(api.WorkerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerStatus indicates an expected call of WorkerStatus.
func (mr *MockWorkerSleepSchedulerMockRecorder) WorkerStatus(ctx, workerUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerStatus", reflect.TypeOf((*MockWorkerSleepScheduler)(nil).WorkerStatus), ctx, workerUUID)
}

// MockJobDeleter is a mock of JobDeleter interface.
type MockJobDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockJobDeleterMockRecorder
	isgomock struct{}
}

// MockJobDeleterMockRecorder is the mock recorder for MockJobDeleter.
type MockJobDeleterMockRecorder struct {
	mock *MockJobDeleter
}

// NewMockJobDeleter creates a new mock instance.
func NewMockJobDeleter(ctrl *gomock.Controller) *MockJobDeleter {
	mock := &MockJobDeleter{ctrl: ctrl}
	mock.recorder = &MockJobDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobDeleter) EXPECT() *MockJobDeleterMockRecorder {
	return m.recorder
}

// QueueJobDeletion mocks base method.
func (m *MockJobDeleter) QueueJobDeletion(ctx context.Context, job *persistence.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueJobDeletion", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueJobDeletion indicates an expected call of QueueJobDeletion.
func (mr *MockJobDeleterMockRecorder) QueueJobDeletion(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueJobDeletion", reflect.TypeOf((*MockJobDeleter)(nil).QueueJobDeletion), ctx, job)
}

// QueueMassJobDeletion mocks base method.
func (m *MockJobDeleter) QueueMassJobDeletion(ctx context.Context, lastUpdatedMax time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueMassJobDeletion", ctx, lastUpdatedMax)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueMassJobDeletion indicates an expected call of QueueMassJobDeletion.
func (mr *MockJobDeleterMockRecorder) QueueMassJobDeletion(ctx, lastUpdatedMax any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueMassJobDeletion", reflect.TypeOf((*MockJobDeleter)(nil).QueueMassJobDeletion), ctx, lastUpdatedMax)
}

// WhatWouldBeDeleted mocks base method.
func (m *MockJobDeleter) WhatWouldBeDeleted(job *persistence.Job) api.JobDeletionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhatWouldBeDeleted", job)
	ret0, _ := ret[0].(api.JobDeletionInfo)
	return ret0
}

// WhatWouldBeDeleted indicates an expected call of WhatWouldBeDeleted.
func (mr *MockJobDeleterMockRecorder) WhatWouldBeDeleted(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhatWouldBeDeleted", reflect.TypeOf((*MockJobDeleter)(nil).WhatWouldBeDeleted), job)
}

// MockFarmStatusService is a mock of FarmStatusService interface.
type MockFarmStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockFarmStatusServiceMockRecorder
	isgomock struct{}
}

// MockFarmStatusServiceMockRecorder is the mock recorder for MockFarmStatusService.
type MockFarmStatusServiceMockRecorder struct {
	mock *MockFarmStatusService
}

// NewMockFarmStatusService creates a new mock instance.
func NewMockFarmStatusService(ctrl *gomock.Controller) *MockFarmStatusService {
	mock := &MockFarmStatusService{ctrl: ctrl}
	mock.recorder = &MockFarmStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFarmStatusService) EXPECT() *MockFarmStatusServiceMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockFarmStatusService) Report() api.FarmStatusReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report")
	ret0, _ := ret[0].(api.FarmStatusReport)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockFarmStatusServiceMockRecorder) Report() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockFarmStatusService)(nil).Report))
}
