// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/manager/api_impl (interfaces: VariableReplacer)
//
// Generated by this command:
//
//	mockgen -destination mocks/varrepl.gen.go -package mocks projects.blender.org/studio/flamenco/internal/manager/api_impl VariableReplacer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	config "projects.blender.org/studio/flamenco/internal/manager/config"
)

// MockVariableReplacer is a mock of VariableReplacer interface.
type MockVariableReplacer struct {
	ctrl     *gomock.Controller
	recorder *MockVariableReplacerMockRecorder
	isgomock struct{}
}

// MockVariableReplacerMockRecorder is the mock recorder for MockVariableReplacer.
type MockVariableReplacerMockRecorder struct {
	mock *MockVariableReplacer
}

// NewMockVariableReplacer creates a new mock instance.
func NewMockVariableReplacer(ctrl *gomock.Controller) *MockVariableReplacer {
	mock := &MockVariableReplacer{ctrl: ctrl}
	mock.recorder = &MockVariableReplacerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariableReplacer) EXPECT() *MockVariableReplacerMockRecorder {
	return m.recorder
}

// NewVariableExpander mocks base method.
func (m *MockVariableReplacer) NewVariableExpander(audience config.VariableAudience, platform config.VariablePlatform) *config.VariableExpander {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVariableExpander", audience, platform)
	ret0, _ := ret[0].(*config.VariableExpander)
	return ret0
}

// NewVariableExpander indicates an expected call of NewVariableExpander.
func (mr *MockVariableReplacerMockRecorder) NewVariableExpander(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVariableExpander", reflect.TypeOf((*MockVariableReplacer)(nil).NewVariableExpander), audience, platform)
}

// NewVariableToValueConverter mocks base method.
func (m *MockVariableReplacer) NewVariableToValueConverter(audience config.VariableAudience, platform config.VariablePlatform) *config.ValueToVariableReplacer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewVariableToValueConverter", audience, platform)
	ret0, _ := ret[0].(*config.ValueToVariableReplacer)
	return ret0
}

// NewVariableToValueConverter indicates an expected call of NewVariableToValueConverter.
func (mr *MockVariableReplacerMockRecorder) NewVariableToValueConverter(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewVariableToValueConverter", reflect.TypeOf((*MockVariableReplacer)(nil).NewVariableToValueConverter), audience, platform)
}

// ResolveVariables mocks base method.
func (m *MockVariableReplacer) ResolveVariables(audience config.VariableAudience, platform config.VariablePlatform) map[string]config.ResolvedVariable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveVariables", audience, platform)
	ret0, _ := ret[0].(map[string]config.ResolvedVariable)
	return ret0
}

// ResolveVariables indicates an expected call of ResolveVariables.
func (mr *MockVariableReplacerMockRecorder) ResolveVariables(audience, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveVariables", reflect.TypeOf((*MockVariableReplacer)(nil).ResolveVariables), audience, platform)
}
