// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/worker (interfaces: FlamencoClient)
//
// Generated by this command:
//
//	mockgen -destination mocks/client.gen.go -package mocks projects.blender.org/studio/flamenco/internal/worker FlamencoClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	api "projects.blender.org/studio/flamenco/pkg/api"
)

// MockFlamencoClient is a mock of FlamencoClient interface.
type MockFlamencoClient struct {
	ctrl     *gomock.Controller
	recorder *MockFlamencoClientMockRecorder
	isgomock struct{}
}

// MockFlamencoClientMockRecorder is the mock recorder for MockFlamencoClient.
type MockFlamencoClientMockRecorder struct {
	mock *MockFlamencoClient
}

// NewMockFlamencoClient creates a new mock instance.
func NewMockFlamencoClient(ctrl *gomock.Controller) *MockFlamencoClient {
	mock := &MockFlamencoClient{ctrl: ctrl}
	mock.recorder = &MockFlamencoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlamencoClient) EXPECT() *MockFlamencoClientMockRecorder {
	return m.recorder
}

// CheckBlenderExePathWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) CheckBlenderExePathWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CheckBlenderExePathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckBlenderExePathWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CheckBlenderExePathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBlenderExePathWithBodyWithResponse indicates an expected call of CheckBlenderExePathWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) CheckBlenderExePathWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBlenderExePathWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CheckBlenderExePathWithBodyWithResponse), varargs...)
}

// CheckBlenderExePathWithResponse mocks base method.
func (m *MockFlamencoClient) CheckBlenderExePathWithResponse(ctx context.Context, body api.CheckBlenderExePathJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CheckBlenderExePathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckBlenderExePathWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CheckBlenderExePathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBlenderExePathWithResponse indicates an expected call of CheckBlenderExePathWithResponse.
func (mr *MockFlamencoClientMockRecorder) CheckBlenderExePathWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBlenderExePathWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CheckBlenderExePathWithResponse), varargs...)
}

// CheckSharedStoragePathWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) CheckSharedStoragePathWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CheckSharedStoragePathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckSharedStoragePathWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CheckSharedStoragePathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSharedStoragePathWithBodyWithResponse indicates an expected call of CheckSharedStoragePathWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) CheckSharedStoragePathWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSharedStoragePathWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CheckSharedStoragePathWithBodyWithResponse), varargs...)
}

// CheckSharedStoragePathWithResponse mocks base method.
func (m *MockFlamencoClient) CheckSharedStoragePathWithResponse(ctx context.Context, body api.CheckSharedStoragePathJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CheckSharedStoragePathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckSharedStoragePathWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CheckSharedStoragePathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSharedStoragePathWithResponse indicates an expected call of CheckSharedStoragePathWithResponse.
func (mr *MockFlamencoClientMockRecorder) CheckSharedStoragePathWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSharedStoragePathWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CheckSharedStoragePathWithResponse), varargs...)
}

// CreateWorkerTagWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) CreateWorkerTagWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.CreateWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWorkerTagWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkerTagWithBodyWithResponse indicates an expected call of CreateWorkerTagWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) CreateWorkerTagWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkerTagWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CreateWorkerTagWithBodyWithResponse), varargs...)
}

// CreateWorkerTagWithResponse mocks base method.
func (m *MockFlamencoClient) CreateWorkerTagWithResponse(ctx context.Context, body api.CreateWorkerTagJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.CreateWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWorkerTagWithResponse", varargs...)
	ret0, _ := ret[0].(*api.CreateWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkerTagWithResponse indicates an expected call of CreateWorkerTagWithResponse.
func (mr *MockFlamencoClientMockRecorder) CreateWorkerTagWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkerTagWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).CreateWorkerTagWithResponse), varargs...)
}

// DeleteJobMassWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteJobMassWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.DeleteJobMassResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteJobMassWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteJobMassResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJobMassWithBodyWithResponse indicates an expected call of DeleteJobMassWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteJobMassWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobMassWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteJobMassWithBodyWithResponse), varargs...)
}

// DeleteJobMassWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteJobMassWithResponse(ctx context.Context, body api.DeleteJobMassJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.DeleteJobMassResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteJobMassWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteJobMassResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJobMassWithResponse indicates an expected call of DeleteJobMassWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteJobMassWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobMassWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteJobMassWithResponse), varargs...)
}

// DeleteJobWhatWouldItDoWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteJobWhatWouldItDoWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.DeleteJobWhatWouldItDoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteJobWhatWouldItDoWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteJobWhatWouldItDoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJobWhatWouldItDoWithResponse indicates an expected call of DeleteJobWhatWouldItDoWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteJobWhatWouldItDoWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobWhatWouldItDoWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteJobWhatWouldItDoWithResponse), varargs...)
}

// DeleteJobWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteJobWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.DeleteJobResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteJobWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJobWithResponse indicates an expected call of DeleteJobWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteJobWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteJobWithResponse), varargs...)
}

// DeleteWorkerTagWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteWorkerTagWithResponse(ctx context.Context, tagId string, reqEditors ...api.RequestEditorFn) (*api.DeleteWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tagId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWorkerTagWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkerTagWithResponse indicates an expected call of DeleteWorkerTagWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteWorkerTagWithResponse(ctx, tagId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tagId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkerTagWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteWorkerTagWithResponse), varargs...)
}

// DeleteWorkerWithResponse mocks base method.
func (m *MockFlamencoClient) DeleteWorkerWithResponse(ctx context.Context, workerId string, reqEditors ...api.RequestEditorFn) (*api.DeleteWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWorkerWithResponse", varargs...)
	ret0, _ := ret[0].(*api.DeleteWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkerWithResponse indicates an expected call of DeleteWorkerWithResponse.
func (mr *MockFlamencoClientMockRecorder) DeleteWorkerWithResponse(ctx, workerId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkerWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).DeleteWorkerWithResponse), varargs...)
}

// FetchGlobalLastRenderedInfoWithResponse mocks base method.
func (m *MockFlamencoClient) FetchGlobalLastRenderedInfoWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.FetchGlobalLastRenderedInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchGlobalLastRenderedInfoWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchGlobalLastRenderedInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGlobalLastRenderedInfoWithResponse indicates an expected call of FetchGlobalLastRenderedInfoWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchGlobalLastRenderedInfoWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGlobalLastRenderedInfoWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchGlobalLastRenderedInfoWithResponse), varargs...)
}

// FetchJobBlocklistWithResponse mocks base method.
func (m *MockFlamencoClient) FetchJobBlocklistWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.FetchJobBlocklistResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobBlocklistWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchJobBlocklistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobBlocklistWithResponse indicates an expected call of FetchJobBlocklistWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchJobBlocklistWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobBlocklistWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchJobBlocklistWithResponse), varargs...)
}

// FetchJobLastRenderedInfoWithResponse mocks base method.
func (m *MockFlamencoClient) FetchJobLastRenderedInfoWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.FetchJobLastRenderedInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobLastRenderedInfoWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchJobLastRenderedInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobLastRenderedInfoWithResponse indicates an expected call of FetchJobLastRenderedInfoWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchJobLastRenderedInfoWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobLastRenderedInfoWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchJobLastRenderedInfoWithResponse), varargs...)
}

// FetchJobTasksWithResponse mocks base method.
func (m *MockFlamencoClient) FetchJobTasksWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.FetchJobTasksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobTasksWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchJobTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobTasksWithResponse indicates an expected call of FetchJobTasksWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchJobTasksWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobTasksWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchJobTasksWithResponse), varargs...)
}

// FetchJobWithResponse mocks base method.
func (m *MockFlamencoClient) FetchJobWithResponse(ctx context.Context, jobId string, reqEditors ...api.RequestEditorFn) (*api.FetchJobResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobWithResponse indicates an expected call of FetchJobWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchJobWithResponse(ctx, jobId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchJobWithResponse), varargs...)
}

// FetchJobsWithResponse mocks base method.
func (m *MockFlamencoClient) FetchJobsWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.FetchJobsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchJobsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJobsWithResponse indicates an expected call of FetchJobsWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchJobsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJobsWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchJobsWithResponse), varargs...)
}

// FetchTaskLogInfoWithResponse mocks base method.
func (m *MockFlamencoClient) FetchTaskLogInfoWithResponse(ctx context.Context, taskId string, reqEditors ...api.RequestEditorFn) (*api.FetchTaskLogInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchTaskLogInfoWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchTaskLogInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskLogInfoWithResponse indicates an expected call of FetchTaskLogInfoWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchTaskLogInfoWithResponse(ctx, taskId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskLogInfoWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchTaskLogInfoWithResponse), varargs...)
}

// FetchTaskLogTailWithResponse mocks base method.
func (m *MockFlamencoClient) FetchTaskLogTailWithResponse(ctx context.Context, taskId string, reqEditors ...api.RequestEditorFn) (*api.FetchTaskLogTailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchTaskLogTailWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchTaskLogTailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskLogTailWithResponse indicates an expected call of FetchTaskLogTailWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchTaskLogTailWithResponse(ctx, taskId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskLogTailWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchTaskLogTailWithResponse), varargs...)
}

// FetchTaskWithResponse mocks base method.
func (m *MockFlamencoClient) FetchTaskWithResponse(ctx context.Context, taskId string, reqEditors ...api.RequestEditorFn) (*api.FetchTaskResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchTaskWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTaskWithResponse indicates an expected call of FetchTaskWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchTaskWithResponse(ctx, taskId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTaskWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchTaskWithResponse), varargs...)
}

// FetchWorkerSleepScheduleWithResponse mocks base method.
func (m *MockFlamencoClient) FetchWorkerSleepScheduleWithResponse(ctx context.Context, workerId string, reqEditors ...api.RequestEditorFn) (*api.FetchWorkerSleepScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchWorkerSleepScheduleWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchWorkerSleepScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerSleepScheduleWithResponse indicates an expected call of FetchWorkerSleepScheduleWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchWorkerSleepScheduleWithResponse(ctx, workerId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerSleepScheduleWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchWorkerSleepScheduleWithResponse), varargs...)
}

// FetchWorkerTagWithResponse mocks base method.
func (m *MockFlamencoClient) FetchWorkerTagWithResponse(ctx context.Context, tagId string, reqEditors ...api.RequestEditorFn) (*api.FetchWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tagId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchWorkerTagWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTagWithResponse indicates an expected call of FetchWorkerTagWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchWorkerTagWithResponse(ctx, tagId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tagId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTagWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchWorkerTagWithResponse), varargs...)
}

// FetchWorkerTagsWithResponse mocks base method.
func (m *MockFlamencoClient) FetchWorkerTagsWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.FetchWorkerTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchWorkerTagsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchWorkerTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerTagsWithResponse indicates an expected call of FetchWorkerTagsWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchWorkerTagsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerTagsWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchWorkerTagsWithResponse), varargs...)
}

// FetchWorkerWithResponse mocks base method.
func (m *MockFlamencoClient) FetchWorkerWithResponse(ctx context.Context, workerId string, reqEditors ...api.RequestEditorFn) (*api.FetchWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchWorkerWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkerWithResponse indicates an expected call of FetchWorkerWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchWorkerWithResponse(ctx, workerId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkerWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchWorkerWithResponse), varargs...)
}

// FetchWorkersWithResponse mocks base method.
func (m *MockFlamencoClient) FetchWorkersWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.FetchWorkersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchWorkersWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FetchWorkersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWorkersWithResponse indicates an expected call of FetchWorkersWithResponse.
func (mr *MockFlamencoClientMockRecorder) FetchWorkersWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWorkersWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FetchWorkersWithResponse), varargs...)
}

// FindBlenderExePathWithResponse mocks base method.
func (m *MockFlamencoClient) FindBlenderExePathWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.FindBlenderExePathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindBlenderExePathWithResponse", varargs...)
	ret0, _ := ret[0].(*api.FindBlenderExePathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBlenderExePathWithResponse indicates an expected call of FindBlenderExePathWithResponse.
func (mr *MockFlamencoClientMockRecorder) FindBlenderExePathWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBlenderExePathWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).FindBlenderExePathWithResponse), varargs...)
}

// GetConfigurationFileWithResponse mocks base method.
func (m *MockFlamencoClient) GetConfigurationFileWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetConfigurationFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfigurationFileWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetConfigurationFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigurationFileWithResponse indicates an expected call of GetConfigurationFileWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetConfigurationFileWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationFileWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetConfigurationFileWithResponse), varargs...)
}

// GetConfigurationWithResponse mocks base method.
func (m *MockFlamencoClient) GetConfigurationWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetConfigurationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfigurationWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetConfigurationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigurationWithResponse indicates an expected call of GetConfigurationWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetConfigurationWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetConfigurationWithResponse), varargs...)
}

// GetFarmStatusWithResponse mocks base method.
func (m *MockFlamencoClient) GetFarmStatusWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetFarmStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFarmStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetFarmStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFarmStatusWithResponse indicates an expected call of GetFarmStatusWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetFarmStatusWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFarmStatusWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetFarmStatusWithResponse), varargs...)
}

// GetJobTypeWithResponse mocks base method.
func (m *MockFlamencoClient) GetJobTypeWithResponse(ctx context.Context, typeName string, reqEditors ...api.RequestEditorFn) (*api.GetJobTypeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, typeName}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetJobTypeWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetJobTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobTypeWithResponse indicates an expected call of GetJobTypeWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetJobTypeWithResponse(ctx, typeName any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, typeName}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobTypeWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetJobTypeWithResponse), varargs...)
}

// GetJobTypesWithResponse mocks base method.
func (m *MockFlamencoClient) GetJobTypesWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetJobTypesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetJobTypesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetJobTypesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobTypesWithResponse indicates an expected call of GetJobTypesWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetJobTypesWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobTypesWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetJobTypesWithResponse), varargs...)
}

// GetSharedStorageWithResponse mocks base method.
func (m *MockFlamencoClient) GetSharedStorageWithResponse(ctx context.Context, audience api.ManagerVariableAudience, platform string, reqEditors ...api.RequestEditorFn) (*api.GetSharedStorageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, audience, platform}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSharedStorageWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetSharedStorageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedStorageWithResponse indicates an expected call of GetSharedStorageWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetSharedStorageWithResponse(ctx, audience, platform any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, audience, platform}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedStorageWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetSharedStorageWithResponse), varargs...)
}

// GetVariablesWithResponse mocks base method.
func (m *MockFlamencoClient) GetVariablesWithResponse(ctx context.Context, audience api.ManagerVariableAudience, platform string, reqEditors ...api.RequestEditorFn) (*api.GetVariablesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, audience, platform}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVariablesWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetVariablesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariablesWithResponse indicates an expected call of GetVariablesWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetVariablesWithResponse(ctx, audience, platform any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, audience, platform}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariablesWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetVariablesWithResponse), varargs...)
}

// GetVersionWithResponse mocks base method.
func (m *MockFlamencoClient) GetVersionWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.GetVersionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVersionWithResponse", varargs...)
	ret0, _ := ret[0].(*api.GetVersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersionWithResponse indicates an expected call of GetVersionWithResponse.
func (mr *MockFlamencoClientMockRecorder) GetVersionWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersionWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).GetVersionWithResponse), varargs...)
}

// MayWorkerRunWithResponse mocks base method.
func (m *MockFlamencoClient) MayWorkerRunWithResponse(ctx context.Context, taskId string, reqEditors ...api.RequestEditorFn) (*api.MayWorkerRunResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MayWorkerRunWithResponse", varargs...)
	ret0, _ := ret[0].(*api.MayWorkerRunResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MayWorkerRunWithResponse indicates an expected call of MayWorkerRunWithResponse.
func (mr *MockFlamencoClientMockRecorder) MayWorkerRunWithResponse(ctx, taskId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MayWorkerRunWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).MayWorkerRunWithResponse), varargs...)
}

// RegisterWorkerWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) RegisterWorkerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.RegisterWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterWorkerWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RegisterWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterWorkerWithBodyWithResponse indicates an expected call of RegisterWorkerWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) RegisterWorkerWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWorkerWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RegisterWorkerWithBodyWithResponse), varargs...)
}

// RegisterWorkerWithResponse mocks base method.
func (m *MockFlamencoClient) RegisterWorkerWithResponse(ctx context.Context, body api.RegisterWorkerJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.RegisterWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterWorkerWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RegisterWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterWorkerWithResponse indicates an expected call of RegisterWorkerWithResponse.
func (mr *MockFlamencoClientMockRecorder) RegisterWorkerWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWorkerWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RegisterWorkerWithResponse), varargs...)
}

// RemoveJobBlocklistWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) RemoveJobBlocklistWithBodyWithResponse(ctx context.Context, jobId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.RemoveJobBlocklistResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveJobBlocklistWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RemoveJobBlocklistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveJobBlocklistWithBodyWithResponse indicates an expected call of RemoveJobBlocklistWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) RemoveJobBlocklistWithBodyWithResponse(ctx, jobId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveJobBlocklistWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RemoveJobBlocklistWithBodyWithResponse), varargs...)
}

// RemoveJobBlocklistWithResponse mocks base method.
func (m *MockFlamencoClient) RemoveJobBlocklistWithResponse(ctx context.Context, jobId string, body api.RemoveJobBlocklistJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.RemoveJobBlocklistResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveJobBlocklistWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RemoveJobBlocklistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveJobBlocklistWithResponse indicates an expected call of RemoveJobBlocklistWithResponse.
func (mr *MockFlamencoClientMockRecorder) RemoveJobBlocklistWithResponse(ctx, jobId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveJobBlocklistWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RemoveJobBlocklistWithResponse), varargs...)
}

// RequestWorkerStatusChangeWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) RequestWorkerStatusChangeWithBodyWithResponse(ctx context.Context, workerId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.RequestWorkerStatusChangeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestWorkerStatusChangeWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RequestWorkerStatusChangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestWorkerStatusChangeWithBodyWithResponse indicates an expected call of RequestWorkerStatusChangeWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) RequestWorkerStatusChangeWithBodyWithResponse(ctx, workerId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestWorkerStatusChangeWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RequestWorkerStatusChangeWithBodyWithResponse), varargs...)
}

// RequestWorkerStatusChangeWithResponse mocks base method.
func (m *MockFlamencoClient) RequestWorkerStatusChangeWithResponse(ctx context.Context, workerId string, body api.RequestWorkerStatusChangeJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.RequestWorkerStatusChangeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestWorkerStatusChangeWithResponse", varargs...)
	ret0, _ := ret[0].(*api.RequestWorkerStatusChangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestWorkerStatusChangeWithResponse indicates an expected call of RequestWorkerStatusChangeWithResponse.
func (mr *MockFlamencoClientMockRecorder) RequestWorkerStatusChangeWithResponse(ctx, workerId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestWorkerStatusChangeWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).RequestWorkerStatusChangeWithResponse), varargs...)
}

// SaveSetupAssistantConfigWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SaveSetupAssistantConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SaveSetupAssistantConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveSetupAssistantConfigWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SaveSetupAssistantConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSetupAssistantConfigWithBodyWithResponse indicates an expected call of SaveSetupAssistantConfigWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SaveSetupAssistantConfigWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSetupAssistantConfigWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SaveSetupAssistantConfigWithBodyWithResponse), varargs...)
}

// SaveSetupAssistantConfigWithResponse mocks base method.
func (m *MockFlamencoClient) SaveSetupAssistantConfigWithResponse(ctx context.Context, body api.SaveSetupAssistantConfigJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SaveSetupAssistantConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveSetupAssistantConfigWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SaveSetupAssistantConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSetupAssistantConfigWithResponse indicates an expected call of SaveSetupAssistantConfigWithResponse.
func (mr *MockFlamencoClientMockRecorder) SaveSetupAssistantConfigWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSetupAssistantConfigWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SaveSetupAssistantConfigWithResponse), varargs...)
}

// ScheduleTaskWithResponse mocks base method.
func (m *MockFlamencoClient) ScheduleTaskWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.ScheduleTaskResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScheduleTaskWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ScheduleTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleTaskWithResponse indicates an expected call of ScheduleTaskWithResponse.
func (mr *MockFlamencoClientMockRecorder) ScheduleTaskWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleTaskWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ScheduleTaskWithResponse), varargs...)
}

// SetJobPriorityWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobPriorityWithBodyWithResponse(ctx context.Context, jobId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetJobPriorityResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobPriorityWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobPriorityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobPriorityWithBodyWithResponse indicates an expected call of SetJobPriorityWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobPriorityWithBodyWithResponse(ctx, jobId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobPriorityWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobPriorityWithBodyWithResponse), varargs...)
}

// SetJobPriorityWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobPriorityWithResponse(ctx context.Context, jobId string, body api.SetJobPriorityJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetJobPriorityResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobPriorityWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobPriorityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobPriorityWithResponse indicates an expected call of SetJobPriorityWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobPriorityWithResponse(ctx, jobId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobPriorityWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobPriorityWithResponse), varargs...)
}

// SetJobStatusWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobStatusWithBodyWithResponse(ctx context.Context, jobId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetJobStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobStatusWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobStatusWithBodyWithResponse indicates an expected call of SetJobStatusWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobStatusWithBodyWithResponse(ctx, jobId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobStatusWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobStatusWithBodyWithResponse), varargs...)
}

// SetJobStatusWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobStatusWithResponse(ctx context.Context, jobId string, body api.SetJobStatusJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetJobStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobStatusWithResponse indicates an expected call of SetJobStatusWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobStatusWithResponse(ctx, jobId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobStatusWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobStatusWithResponse), varargs...)
}

// SetJobTagWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobTagWithBodyWithResponse(ctx context.Context, jobId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetJobTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobTagWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobTagWithBodyWithResponse indicates an expected call of SetJobTagWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobTagWithBodyWithResponse(ctx, jobId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobTagWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobTagWithBodyWithResponse), varargs...)
}

// SetJobTagWithResponse mocks base method.
func (m *MockFlamencoClient) SetJobTagWithResponse(ctx context.Context, jobId string, body api.SetJobTagJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetJobTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, jobId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetJobTagWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetJobTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetJobTagWithResponse indicates an expected call of SetJobTagWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetJobTagWithResponse(ctx, jobId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, jobId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobTagWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetJobTagWithResponse), varargs...)
}

// SetTaskStatusWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetTaskStatusWithBodyWithResponse(ctx context.Context, taskId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetTaskStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTaskStatusWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetTaskStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTaskStatusWithBodyWithResponse indicates an expected call of SetTaskStatusWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetTaskStatusWithBodyWithResponse(ctx, taskId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskStatusWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetTaskStatusWithBodyWithResponse), varargs...)
}

// SetTaskStatusWithResponse mocks base method.
func (m *MockFlamencoClient) SetTaskStatusWithResponse(ctx context.Context, taskId string, body api.SetTaskStatusJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetTaskStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTaskStatusWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetTaskStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTaskStatusWithResponse indicates an expected call of SetTaskStatusWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetTaskStatusWithResponse(ctx, taskId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskStatusWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetTaskStatusWithResponse), varargs...)
}

// SetWorkerSleepScheduleWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetWorkerSleepScheduleWithBodyWithResponse(ctx context.Context, workerId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetWorkerSleepScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWorkerSleepScheduleWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetWorkerSleepScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWorkerSleepScheduleWithBodyWithResponse indicates an expected call of SetWorkerSleepScheduleWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetWorkerSleepScheduleWithBodyWithResponse(ctx, workerId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerSleepScheduleWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetWorkerSleepScheduleWithBodyWithResponse), varargs...)
}

// SetWorkerSleepScheduleWithResponse mocks base method.
func (m *MockFlamencoClient) SetWorkerSleepScheduleWithResponse(ctx context.Context, workerId string, body api.SetWorkerSleepScheduleJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetWorkerSleepScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWorkerSleepScheduleWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetWorkerSleepScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWorkerSleepScheduleWithResponse indicates an expected call of SetWorkerSleepScheduleWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetWorkerSleepScheduleWithResponse(ctx, workerId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerSleepScheduleWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetWorkerSleepScheduleWithResponse), varargs...)
}

// SetWorkerTagsWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SetWorkerTagsWithBodyWithResponse(ctx context.Context, workerId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SetWorkerTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWorkerTagsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetWorkerTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWorkerTagsWithBodyWithResponse indicates an expected call of SetWorkerTagsWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetWorkerTagsWithBodyWithResponse(ctx, workerId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerTagsWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetWorkerTagsWithBodyWithResponse), varargs...)
}

// SetWorkerTagsWithResponse mocks base method.
func (m *MockFlamencoClient) SetWorkerTagsWithResponse(ctx context.Context, workerId string, body api.SetWorkerTagsJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SetWorkerTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWorkerTagsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SetWorkerTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWorkerTagsWithResponse indicates an expected call of SetWorkerTagsWithResponse.
func (mr *MockFlamencoClientMockRecorder) SetWorkerTagsWithResponse(ctx, workerId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerTagsWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SetWorkerTagsWithResponse), varargs...)
}

// ShamanCheckoutRequirementsWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanCheckoutRequirementsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ShamanCheckoutRequirementsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanCheckoutRequirementsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanCheckoutRequirementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanCheckoutRequirementsWithBodyWithResponse indicates an expected call of ShamanCheckoutRequirementsWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanCheckoutRequirementsWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanCheckoutRequirementsWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanCheckoutRequirementsWithBodyWithResponse), varargs...)
}

// ShamanCheckoutRequirementsWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanCheckoutRequirementsWithResponse(ctx context.Context, body api.ShamanCheckoutRequirementsJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.ShamanCheckoutRequirementsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanCheckoutRequirementsWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanCheckoutRequirementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanCheckoutRequirementsWithResponse indicates an expected call of ShamanCheckoutRequirementsWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanCheckoutRequirementsWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanCheckoutRequirementsWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanCheckoutRequirementsWithResponse), varargs...)
}

// ShamanCheckoutWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanCheckoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ShamanCheckoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanCheckoutWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanCheckoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanCheckoutWithBodyWithResponse indicates an expected call of ShamanCheckoutWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanCheckoutWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanCheckoutWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanCheckoutWithBodyWithResponse), varargs...)
}

// ShamanCheckoutWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanCheckoutWithResponse(ctx context.Context, body api.ShamanCheckoutJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.ShamanCheckoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanCheckoutWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanCheckoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanCheckoutWithResponse indicates an expected call of ShamanCheckoutWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanCheckoutWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanCheckoutWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanCheckoutWithResponse), varargs...)
}

// ShamanFileStoreCheckWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanFileStoreCheckWithResponse(ctx context.Context, checksum string, filesize int, reqEditors ...api.RequestEditorFn) (*api.ShamanFileStoreCheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, checksum, filesize}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanFileStoreCheckWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanFileStoreCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanFileStoreCheckWithResponse indicates an expected call of ShamanFileStoreCheckWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanFileStoreCheckWithResponse(ctx, checksum, filesize any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, checksum, filesize}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanFileStoreCheckWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanFileStoreCheckWithResponse), varargs...)
}

// ShamanFileStoreWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) ShamanFileStoreWithBodyWithResponse(ctx context.Context, checksum string, filesize int, params *api.ShamanFileStoreParams, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.ShamanFileStoreResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, checksum, filesize, params, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShamanFileStoreWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.ShamanFileStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShamanFileStoreWithBodyWithResponse indicates an expected call of ShamanFileStoreWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) ShamanFileStoreWithBodyWithResponse(ctx, checksum, filesize, params, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, checksum, filesize, params, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShamanFileStoreWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).ShamanFileStoreWithBodyWithResponse), varargs...)
}

// SignOffWithResponse mocks base method.
func (m *MockFlamencoClient) SignOffWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.SignOffResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignOffWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SignOffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignOffWithResponse indicates an expected call of SignOffWithResponse.
func (mr *MockFlamencoClientMockRecorder) SignOffWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOffWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SignOffWithResponse), varargs...)
}

// SignOnWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SignOnWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SignOnResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignOnWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SignOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignOnWithBodyWithResponse indicates an expected call of SignOnWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SignOnWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOnWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SignOnWithBodyWithResponse), varargs...)
}

// SignOnWithResponse mocks base method.
func (m *MockFlamencoClient) SignOnWithResponse(ctx context.Context, body api.SignOnJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SignOnResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SignOnWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SignOnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignOnWithResponse indicates an expected call of SignOnWithResponse.
func (mr *MockFlamencoClientMockRecorder) SignOnWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOnWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SignOnWithResponse), varargs...)
}

// SubmitJobCheckWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SubmitJobCheckWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SubmitJobCheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitJobCheckWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitJobCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJobCheckWithBodyWithResponse indicates an expected call of SubmitJobCheckWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SubmitJobCheckWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJobCheckWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SubmitJobCheckWithBodyWithResponse), varargs...)
}

// SubmitJobCheckWithResponse mocks base method.
func (m *MockFlamencoClient) SubmitJobCheckWithResponse(ctx context.Context, body api.SubmitJobCheckJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SubmitJobCheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitJobCheckWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitJobCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJobCheckWithResponse indicates an expected call of SubmitJobCheckWithResponse.
func (mr *MockFlamencoClientMockRecorder) SubmitJobCheckWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJobCheckWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SubmitJobCheckWithResponse), varargs...)
}

// SubmitJobWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) SubmitJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.SubmitJobResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitJobWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJobWithBodyWithResponse indicates an expected call of SubmitJobWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) SubmitJobWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJobWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SubmitJobWithBodyWithResponse), varargs...)
}

// SubmitJobWithResponse mocks base method.
func (m *MockFlamencoClient) SubmitJobWithResponse(ctx context.Context, body api.SubmitJobJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.SubmitJobResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitJobWithResponse", varargs...)
	ret0, _ := ret[0].(*api.SubmitJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJobWithResponse indicates an expected call of SubmitJobWithResponse.
func (mr *MockFlamencoClientMockRecorder) SubmitJobWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJobWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).SubmitJobWithResponse), varargs...)
}

// TaskOutputProducedWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) TaskOutputProducedWithBodyWithResponse(ctx context.Context, taskId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.TaskOutputProducedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TaskOutputProducedWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.TaskOutputProducedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskOutputProducedWithBodyWithResponse indicates an expected call of TaskOutputProducedWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) TaskOutputProducedWithBodyWithResponse(ctx, taskId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskOutputProducedWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).TaskOutputProducedWithBodyWithResponse), varargs...)
}

// TaskUpdateWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) TaskUpdateWithBodyWithResponse(ctx context.Context, taskId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.TaskUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TaskUpdateWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.TaskUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskUpdateWithBodyWithResponse indicates an expected call of TaskUpdateWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) TaskUpdateWithBodyWithResponse(ctx, taskId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskUpdateWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).TaskUpdateWithBodyWithResponse), varargs...)
}

// TaskUpdateWithResponse mocks base method.
func (m *MockFlamencoClient) TaskUpdateWithResponse(ctx context.Context, taskId string, body api.TaskUpdateJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.TaskUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TaskUpdateWithResponse", varargs...)
	ret0, _ := ret[0].(*api.TaskUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskUpdateWithResponse indicates an expected call of TaskUpdateWithResponse.
func (mr *MockFlamencoClientMockRecorder) TaskUpdateWithResponse(ctx, taskId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskUpdateWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).TaskUpdateWithResponse), varargs...)
}

// UpdateConfigurationFileWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) UpdateConfigurationFileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.UpdateConfigurationFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateConfigurationFileWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdateConfigurationFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfigurationFileWithBodyWithResponse indicates an expected call of UpdateConfigurationFileWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) UpdateConfigurationFileWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigurationFileWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).UpdateConfigurationFileWithBodyWithResponse), varargs...)
}

// UpdateConfigurationFileWithResponse mocks base method.
func (m *MockFlamencoClient) UpdateConfigurationFileWithResponse(ctx context.Context, body api.UpdateConfigurationFileJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.UpdateConfigurationFileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateConfigurationFileWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdateConfigurationFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfigurationFileWithResponse indicates an expected call of UpdateConfigurationFileWithResponse.
func (mr *MockFlamencoClientMockRecorder) UpdateConfigurationFileWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigurationFileWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).UpdateConfigurationFileWithResponse), varargs...)
}

// UpdateWorkerTagWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) UpdateWorkerTagWithBodyWithResponse(ctx context.Context, tagId, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.UpdateWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tagId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateWorkerTagWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdateWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkerTagWithBodyWithResponse indicates an expected call of UpdateWorkerTagWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) UpdateWorkerTagWithBodyWithResponse(ctx, tagId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tagId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerTagWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).UpdateWorkerTagWithBodyWithResponse), varargs...)
}

// UpdateWorkerTagWithResponse mocks base method.
func (m *MockFlamencoClient) UpdateWorkerTagWithResponse(ctx context.Context, tagId string, body api.UpdateWorkerTagJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.UpdateWorkerTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tagId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateWorkerTagWithResponse", varargs...)
	ret0, _ := ret[0].(*api.UpdateWorkerTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWorkerTagWithResponse indicates an expected call of UpdateWorkerTagWithResponse.
func (mr *MockFlamencoClientMockRecorder) UpdateWorkerTagWithResponse(ctx, tagId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tagId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerTagWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).UpdateWorkerTagWithResponse), varargs...)
}

// WorkerStateChangedWithBodyWithResponse mocks base method.
func (m *MockFlamencoClient) WorkerStateChangedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...api.RequestEditorFn) (*api.WorkerStateChangedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WorkerStateChangedWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*api.WorkerStateChangedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerStateChangedWithBodyWithResponse indicates an expected call of WorkerStateChangedWithBodyWithResponse.
func (mr *MockFlamencoClientMockRecorder) WorkerStateChangedWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerStateChangedWithBodyWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).WorkerStateChangedWithBodyWithResponse), varargs...)
}

// WorkerStateChangedWithResponse mocks base method.
func (m *MockFlamencoClient) WorkerStateChangedWithResponse(ctx context.Context, body api.WorkerStateChangedJSONRequestBody, reqEditors ...api.RequestEditorFn) (*api.WorkerStateChangedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WorkerStateChangedWithResponse", varargs...)
	ret0, _ := ret[0].(*api.WorkerStateChangedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerStateChangedWithResponse indicates an expected call of WorkerStateChangedWithResponse.
func (mr *MockFlamencoClientMockRecorder) WorkerStateChangedWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerStateChangedWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).WorkerStateChangedWithResponse), varargs...)
}

// WorkerStateWithResponse mocks base method.
func (m *MockFlamencoClient) WorkerStateWithResponse(ctx context.Context, reqEditors ...api.RequestEditorFn) (*api.WorkerStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WorkerStateWithResponse", varargs...)
	ret0, _ := ret[0].(*api.WorkerStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerStateWithResponse indicates an expected call of WorkerStateWithResponse.
func (mr *MockFlamencoClientMockRecorder) WorkerStateWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerStateWithResponse", reflect.TypeOf((*MockFlamencoClient)(nil).WorkerStateWithResponse), varargs...)
}
