// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/worker (interfaces: CommandListener)
//
// Generated by this command:
//
//	mockgen -destination mocks/command_listener.gen.go -package mocks projects.blender.org/studio/flamenco/internal/worker CommandListener
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandListener is a mock of CommandListener interface.
type MockCommandListener struct {
	ctrl     *gomock.Controller
	recorder *MockCommandListenerMockRecorder
	isgomock struct{}
}

// MockCommandListenerMockRecorder is the mock recorder for MockCommandListener.
type MockCommandListenerMockRecorder struct {
	mock *MockCommandListener
}

// NewMockCommandListener creates a new mock instance.
func NewMockCommandListener(ctrl *gomock.Controller) *MockCommandListener {
	mock := &MockCommandListener{ctrl: ctrl}
	mock.recorder = &MockCommandListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandListener) EXPECT() *MockCommandListenerMockRecorder {
	return m.recorder
}

// LogProduced mocks base method.
func (m *MockCommandListener) LogProduced(ctx context.Context, taskID string, logLines ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskID}
	for _, a := range logLines {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogProduced", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogProduced indicates an expected call of LogProduced.
func (mr *MockCommandListenerMockRecorder) LogProduced(ctx, taskID any, logLines ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskID}, logLines...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogProduced", reflect.TypeOf((*MockCommandListener)(nil).LogProduced), varargs...)
}

// OutputProduced mocks base method.
func (m *MockCommandListener) OutputProduced(ctx context.Context, taskID, outputLocation string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutputProduced", ctx, taskID, outputLocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// OutputProduced indicates an expected call of OutputProduced.
func (mr *MockCommandListenerMockRecorder) OutputProduced(ctx, taskID, outputLocation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputProduced", reflect.TypeOf((*MockCommandListener)(nil).OutputProduced), ctx, taskID, outputLocation)
}

// TaskStep mocks base method.
func (m *MockCommandListener) TaskStep(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskStep", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskStep indicates an expected call of TaskStep.
func (mr *MockCommandListenerMockRecorder) TaskStep(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskStep", reflect.TypeOf((*MockCommandListener)(nil).TaskStep), ctx, taskID)
}
