// Code generated by MockGen. DO NOT EDIT.
// Source: projects.blender.org/studio/flamenco/internal/worker (interfaces: CommandRunner,TaskExecutionListener)
//
// Generated by this command:
//
//	mockgen -destination mocks/task_exe_listener.gen.go -package mocks projects.blender.org/studio/flamenco/internal/worker CommandRunner,TaskExecutionListener
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	api "projects.blender.org/studio/flamenco/pkg/api"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockCommandRunner) Run(ctx context.Context, taskID string, cmd api.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, taskID, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCommandRunnerMockRecorder) Run(ctx, taskID, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommandRunner)(nil).Run), ctx, taskID, cmd)
}

// MockTaskExecutionListener is a mock of TaskExecutionListener interface.
type MockTaskExecutionListener struct {
	ctrl     *gomock.Controller
	recorder *MockTaskExecutionListenerMockRecorder
	isgomock struct{}
}

// MockTaskExecutionListenerMockRecorder is the mock recorder for MockTaskExecutionListener.
type MockTaskExecutionListenerMockRecorder struct {
	mock *MockTaskExecutionListener
}

// NewMockTaskExecutionListener creates a new mock instance.
func NewMockTaskExecutionListener(ctrl *gomock.Controller) *MockTaskExecutionListener {
	mock := &MockTaskExecutionListener{ctrl: ctrl}
	mock.recorder = &MockTaskExecutionListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskExecutionListener) EXPECT() *MockTaskExecutionListenerMockRecorder {
	return m.recorder
}

// TaskCompleted mocks base method.
func (m *MockTaskExecutionListener) TaskCompleted(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskCompleted", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskCompleted indicates an expected call of TaskCompleted.
func (mr *MockTaskExecutionListenerMockRecorder) TaskCompleted(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskCompleted", reflect.TypeOf((*MockTaskExecutionListener)(nil).TaskCompleted), ctx, taskID)
}

// TaskFailed mocks base method.
func (m *MockTaskExecutionListener) TaskFailed(ctx context.Context, taskID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskFailed", ctx, taskID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskFailed indicates an expected call of TaskFailed.
func (mr *MockTaskExecutionListenerMockRecorder) TaskFailed(ctx, taskID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskFailed", reflect.TypeOf((*MockTaskExecutionListener)(nil).TaskFailed), ctx, taskID, reason)
}

// TaskStarted mocks base method.
func (m *MockTaskExecutionListener) TaskStarted(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskStarted", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskStarted indicates an expected call of TaskStarted.
func (mr *MockTaskExecutionListenerMockRecorder) TaskStarted(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskStarted", reflect.TypeOf((*MockTaskExecutionListener)(nil).TaskStarted), ctx, taskID)
}

// TaskStep mocks base method.
func (m *MockTaskExecutionListener) TaskStep(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskStep", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskStep indicates an expected call of TaskStep.
func (mr *MockTaskExecutionListenerMockRecorder) TaskStep(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskStep", reflect.TypeOf((*MockTaskExecutionListener)(nil).TaskStep), ctx, taskID)
}
