// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const countTaskUpdates = `-- name: CountTaskUpdates :one
SELECT count(*) as count from task_updates
`

func (q *Queries) CountTaskUpdates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskUpdates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTaskUpdate = `-- name: DeleteTaskUpdate :exec
DELETE FROM task_updates WHERE id=?1
`

func (q *Queries) DeleteTaskUpdate(ctx context.Context, taskUpdateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskUpdate, taskUpdateID)
	return err
}

const firstTaskUpdate = `-- name: FirstTaskUpdate :one
SELECT id, created_at, task_id, payload FROM task_updates ORDER BY id LIMIT 1
`

func (q *Queries) FirstTaskUpdate(ctx context.Context) (TaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, firstTaskUpdate)
	var i TaskUpdate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TaskID,
		&i.Payload,
	)
	return i, err
}

const insertTaskUpdate = `-- name: InsertTaskUpdate :exec
INSERT INTO task_updates (
  created_at,
  task_id,
  payload
) VALUES (
  ?1,
  ?2,
  ?3
)
`

type InsertTaskUpdateParams struct {
	CreatedAt time.Time
	TaskID    string
	Payload   []byte
}

func (q *Queries) InsertTaskUpdate(ctx context.Context, arg InsertTaskUpdateParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskUpdate, arg.CreatedAt, arg.TaskID, arg.Payload)
	return err
}
